
//input ports
add mapped point in1[31] in1[31] -type PI PI
add mapped point in1[30] in1[30] -type PI PI
add mapped point in1[29] in1[29] -type PI PI
add mapped point in1[28] in1[28] -type PI PI
add mapped point in1[27] in1[27] -type PI PI
add mapped point in1[26] in1[26] -type PI PI
add mapped point in1[25] in1[25] -type PI PI
add mapped point in1[24] in1[24] -type PI PI
add mapped point in1[23] in1[23] -type PI PI
add mapped point in1[22] in1[22] -type PI PI
add mapped point in1[21] in1[21] -type PI PI
add mapped point in1[20] in1[20] -type PI PI
add mapped point in1[19] in1[19] -type PI PI
add mapped point in1[18] in1[18] -type PI PI
add mapped point in1[17] in1[17] -type PI PI
add mapped point in1[16] in1[16] -type PI PI
add mapped point in1[15] in1[15] -type PI PI
add mapped point in1[14] in1[14] -type PI PI
add mapped point in1[13] in1[13] -type PI PI
add mapped point in1[12] in1[12] -type PI PI
add mapped point in1[11] in1[11] -type PI PI
add mapped point in1[10] in1[10] -type PI PI
add mapped point in1[9] in1[9] -type PI PI
add mapped point in1[8] in1[8] -type PI PI
add mapped point in1[7] in1[7] -type PI PI
add mapped point in1[6] in1[6] -type PI PI
add mapped point in1[5] in1[5] -type PI PI
add mapped point in1[4] in1[4] -type PI PI
add mapped point in1[3] in1[3] -type PI PI
add mapped point in1[2] in1[2] -type PI PI
add mapped point in1[1] in1[1] -type PI PI
add mapped point in1[0] in1[0] -type PI PI
add mapped point in2[31] in2[31] -type PI PI
add mapped point in2[30] in2[30] -type PI PI
add mapped point in2[29] in2[29] -type PI PI
add mapped point in2[28] in2[28] -type PI PI
add mapped point in2[27] in2[27] -type PI PI
add mapped point in2[26] in2[26] -type PI PI
add mapped point in2[25] in2[25] -type PI PI
add mapped point in2[24] in2[24] -type PI PI
add mapped point in2[23] in2[23] -type PI PI
add mapped point in2[22] in2[22] -type PI PI
add mapped point in2[21] in2[21] -type PI PI
add mapped point in2[20] in2[20] -type PI PI
add mapped point in2[19] in2[19] -type PI PI
add mapped point in2[18] in2[18] -type PI PI
add mapped point in2[17] in2[17] -type PI PI
add mapped point in2[16] in2[16] -type PI PI
add mapped point in2[15] in2[15] -type PI PI
add mapped point in2[14] in2[14] -type PI PI
add mapped point in2[13] in2[13] -type PI PI
add mapped point in2[12] in2[12] -type PI PI
add mapped point in2[11] in2[11] -type PI PI
add mapped point in2[10] in2[10] -type PI PI
add mapped point in2[9] in2[9] -type PI PI
add mapped point in2[8] in2[8] -type PI PI
add mapped point in2[7] in2[7] -type PI PI
add mapped point in2[6] in2[6] -type PI PI
add mapped point in2[5] in2[5] -type PI PI
add mapped point in2[4] in2[4] -type PI PI
add mapped point in2[3] in2[3] -type PI PI
add mapped point in2[2] in2[2] -type PI PI
add mapped point in2[1] in2[1] -type PI PI
add mapped point in2[0] in2[0] -type PI PI
add mapped point start start -type PI PI
add mapped point reset reset -type PI PI
add mapped point clk clk -type PI PI

//output ports
add mapped point out[63] out[63] -type PO PO
add mapped point out[62] out[62] -type PO PO
add mapped point out[61] out[61] -type PO PO
add mapped point out[60] out[60] -type PO PO
add mapped point out[59] out[59] -type PO PO
add mapped point out[58] out[58] -type PO PO
add mapped point out[57] out[57] -type PO PO
add mapped point out[56] out[56] -type PO PO
add mapped point out[55] out[55] -type PO PO
add mapped point out[54] out[54] -type PO PO
add mapped point out[53] out[53] -type PO PO
add mapped point out[52] out[52] -type PO PO
add mapped point out[51] out[51] -type PO PO
add mapped point out[50] out[50] -type PO PO
add mapped point out[49] out[49] -type PO PO
add mapped point out[48] out[48] -type PO PO
add mapped point out[47] out[47] -type PO PO
add mapped point out[46] out[46] -type PO PO
add mapped point out[45] out[45] -type PO PO
add mapped point out[44] out[44] -type PO PO
add mapped point out[43] out[43] -type PO PO
add mapped point out[42] out[42] -type PO PO
add mapped point out[41] out[41] -type PO PO
add mapped point out[40] out[40] -type PO PO
add mapped point out[39] out[39] -type PO PO
add mapped point out[38] out[38] -type PO PO
add mapped point out[37] out[37] -type PO PO
add mapped point out[36] out[36] -type PO PO
add mapped point out[35] out[35] -type PO PO
add mapped point out[34] out[34] -type PO PO
add mapped point out[33] out[33] -type PO PO
add mapped point out[32] out[32] -type PO PO
add mapped point out[31] out[31] -type PO PO
add mapped point out[30] out[30] -type PO PO
add mapped point out[29] out[29] -type PO PO
add mapped point out[28] out[28] -type PO PO
add mapped point out[27] out[27] -type PO PO
add mapped point out[26] out[26] -type PO PO
add mapped point out[25] out[25] -type PO PO
add mapped point out[24] out[24] -type PO PO
add mapped point out[23] out[23] -type PO PO
add mapped point out[22] out[22] -type PO PO
add mapped point out[21] out[21] -type PO PO
add mapped point out[20] out[20] -type PO PO
add mapped point out[19] out[19] -type PO PO
add mapped point out[18] out[18] -type PO PO
add mapped point out[17] out[17] -type PO PO
add mapped point out[16] out[16] -type PO PO
add mapped point out[15] out[15] -type PO PO
add mapped point out[14] out[14] -type PO PO
add mapped point out[13] out[13] -type PO PO
add mapped point out[12] out[12] -type PO PO
add mapped point out[11] out[11] -type PO PO
add mapped point out[10] out[10] -type PO PO
add mapped point out[9] out[9] -type PO PO
add mapped point out[8] out[8] -type PO PO
add mapped point out[7] out[7] -type PO PO
add mapped point out[6] out[6] -type PO PO
add mapped point out[5] out[5] -type PO PO
add mapped point out[4] out[4] -type PO PO
add mapped point out[3] out[3] -type PO PO
add mapped point out[2] out[2] -type PO PO
add mapped point out[1] out[1] -type PO PO
add mapped point out[0] out[0] -type PO PO
add mapped point done done -type PO PO

//inout ports




//Sequential Pins
add mapped point par_out_a[0]/q par_out_a_reg_0/QN  -type DFF DFF
add mapped point par_out_a[1]/q par_out_a_reg_1/QN  -type DFF DFF
add mapped point par_out_a[2]/q par_out_a_reg_2/QN  -type DFF DFF
add mapped point par_out_a[3]/q par_out_a_reg_3/QN  -type DFF DFF
add mapped point par_out_a[4]/q par_out_a_reg_4/QN  -type DFF DFF
add mapped point par_out_a[5]/q par_out_a_reg_5/QN  -type DFF DFF
add mapped point par_out_a[6]/q par_out_a_reg_6/Q  -type DFF DFF
add mapped point par_out_a[7]/q par_out_a_reg_7/QN  -type DFF DFF
add mapped point par_out_a[8]/q par_out_a_reg_8/QN  -type DFF DFF
add mapped point par_out_a[9]/q par_out_a_reg_9/QN  -type DFF DFF
add mapped point par_out_a[10]/q par_out_a_reg_10/QN  -type DFF DFF
add mapped point par_out_a[11]/q par_out_a_reg_11/QN  -type DFF DFF
add mapped point par_out_a[12]/q par_out_a_reg_12/QN  -type DFF DFF
add mapped point par_out_a[13]/q par_out_a_reg_13/QN  -type DFF DFF
add mapped point par_out_a[14]/q par_out_a_reg_14/QN  -type DFF DFF
add mapped point par_out_a[15]/q par_out_a_reg_15/QN  -type DFF DFF
add mapped point par_out_a[16]/q par_out_a_reg_16/QN  -type DFF DFF
add mapped point par_out_a[17]/q par_out_a_reg_17/QN  -type DFF DFF
add mapped point par_out_a[18]/q par_out_a_reg_18/QN  -type DFF DFF
add mapped point par_out_a[19]/q par_out_a_reg_19/QN  -type DFF DFF
add mapped point par_out_a[20]/q par_out_a_reg_20/QN  -type DFF DFF
add mapped point par_out_a[21]/q par_out_a_reg_21/QN  -type DFF DFF
add mapped point par_out_a[22]/q par_out_a_reg_22/QN  -type DFF DFF
add mapped point par_out_a[23]/q par_out_a_reg_23/QN  -type DFF DFF
add mapped point par_out_a[24]/q par_out_a_reg_24/QN  -type DFF DFF
add mapped point par_out_a[25]/q par_out_a_reg_25/QN  -type DFF DFF
add mapped point par_out_a[26]/q par_out_a_reg_26/QN  -type DFF DFF
add mapped point par_out_a[27]/q par_out_a_reg_27/QN  -type DFF DFF
add mapped point par_out_a[28]/q par_out_a_reg_28/QN  -type DFF DFF
add mapped point par_out_a[29]/q par_out_a_reg_29/QN  -type DFF DFF
add mapped point par_out_a[30]/q par_out_a_reg_30/QN  -type DFF DFF
add mapped point par_out_a[31]/q par_out_a_reg_31/QN  -type DFF DFF
add mapped point par_out_a[32]/q par_out_a_reg_32/QN  -type DFF DFF
add mapped point par_out_a[33]/q par_out_a_reg_33/QN  -type DFF DFF
add mapped point par_out_a[34]/q par_out_a_reg_34/QN  -type DFF DFF
add mapped point par_out_a[35]/q par_out_a_reg_35/QN  -type DFF DFF
add mapped point par_out_a[36]/q par_out_a_reg_36/QN  -type DFF DFF
add mapped point par_out_a[37]/q par_out_a_reg_37/QN  -type DFF DFF
add mapped point par_out_a[38]/q par_out_a_reg_38/QN  -type DFF DFF
add mapped point par_out_a[39]/q par_out_a_reg_39/QN  -type DFF DFF
add mapped point par_out_a[40]/q par_out_a_reg_40/QN  -type DFF DFF
add mapped point par_out_a[41]/q par_out_a_reg_41/QN  -type DFF DFF
add mapped point par_out_a[42]/q par_out_a_reg_42/QN  -type DFF DFF
add mapped point par_out_a[43]/q par_out_a_reg_43/QN  -type DFF DFF
add mapped point par_out_a[44]/q par_out_a_reg_44/QN  -type DFF DFF
add mapped point par_out_a[45]/q par_out_a_reg_45/QN  -type DFF DFF
add mapped point par_out_a[46]/q par_out_a_reg_46/QN  -type DFF DFF
add mapped point par_out_a[47]/q par_out_a_reg_47/QN  -type DFF DFF
add mapped point par_out_a[48]/q par_out_a_reg_48/QN  -type DFF DFF
add mapped point par_out_a[49]/q par_out_a_reg_49/QN  -type DFF DFF
add mapped point par_out_a[50]/q par_out_a_reg_50/QN  -type DFF DFF
add mapped point par_out_a[51]/q par_out_a_reg_51/QN  -type DFF DFF
add mapped point par_out_a[52]/q par_out_a_reg_52/QN  -type DFF DFF
add mapped point par_out_a[53]/q par_out_a_reg_53/QN  -type DFF DFF
add mapped point par_out_a[54]/q par_out_a_reg_54/QN  -type DFF DFF
add mapped point par_out_a[55]/q par_out_a_reg_55/QN  -type DFF DFF
add mapped point par_out_a[56]/q par_out_a_reg_56/QN  -type DFF DFF
add mapped point par_out_a[57]/q par_out_a_reg_57/QN  -type DFF DFF
add mapped point par_out_a[58]/q par_out_a_reg_58/QN  -type DFF DFF
add mapped point par_out_a[59]/q par_out_a_reg_59/QN  -type DFF DFF
add mapped point par_out_a[60]/q par_out_a_reg_60/QN  -type DFF DFF
add mapped point par_out_a[61]/q par_out_a_reg_61/QN  -type DFF DFF
add mapped point par_out_a[62]/q par_out_a_reg_62/QN  -type DFF DFF
add mapped point par_out_a[63]/q par_out_a_reg_63/QN  -type DFF DFF
add mapped point par_out_b[0]/q par_out_b_reg_0/QN  -type DFF DFF
add mapped point par_out_b[1]/q par_out_b_reg_1/Q  -type DFF DFF
add mapped point par_out_b[2]/q par_out_b_reg_2/Q  -type DFF DFF
add mapped point par_out_b[3]/q par_out_b_reg_3/Q  -type DFF DFF
add mapped point par_out_b[4]/q par_out_b_reg_4/Q  -type DFF DFF
add mapped point par_out_b[5]/q par_out_b_reg_5/Q  -type DFF DFF
add mapped point par_out_b[6]/q par_out_b_reg_6/Q  -type DFF DFF
add mapped point par_out_b[7]/q par_out_b_reg_7/Q  -type DFF DFF
add mapped point par_out_b[8]/q par_out_b_reg_8/Q  -type DFF DFF
add mapped point par_out_b[9]/q par_out_b_reg_9/Q  -type DFF DFF
add mapped point par_out_b[10]/q par_out_b_reg_10/Q  -type DFF DFF
add mapped point par_out_b[11]/q par_out_b_reg_11/Q  -type DFF DFF
add mapped point par_out_b[12]/q par_out_b_reg_12/Q  -type DFF DFF
add mapped point par_out_b[13]/q par_out_b_reg_13/Q  -type DFF DFF
add mapped point par_out_b[14]/q par_out_b_reg_14/Q  -type DFF DFF
add mapped point par_out_b[15]/q par_out_b_reg_15/Q  -type DFF DFF
add mapped point par_out_b[16]/q par_out_b_reg_16/Q  -type DFF DFF
add mapped point par_out_b[17]/q par_out_b_reg_17/Q  -type DFF DFF
add mapped point par_out_b[18]/q par_out_b_reg_18/Q  -type DFF DFF
add mapped point par_out_b[19]/q par_out_b_reg_19/Q  -type DFF DFF
add mapped point par_out_b[20]/q par_out_b_reg_20/Q  -type DFF DFF
add mapped point par_out_b[21]/q par_out_b_reg_21/Q  -type DFF DFF
add mapped point par_out_b[22]/q par_out_b_reg_22/Q  -type DFF DFF
add mapped point par_out_b[23]/q par_out_b_reg_23/Q  -type DFF DFF
add mapped point par_out_b[24]/q par_out_b_reg_24/Q  -type DFF DFF
add mapped point par_out_b[25]/q par_out_b_reg_25/Q  -type DFF DFF
add mapped point par_out_b[26]/q par_out_b_reg_26/Q  -type DFF DFF
add mapped point par_out_b[27]/q par_out_b_reg_27/Q  -type DFF DFF
add mapped point par_out_b[28]/q par_out_b_reg_28/Q  -type DFF DFF
add mapped point par_out_b[29]/q par_out_b_reg_29/Q  -type DFF DFF
add mapped point par_out_b[30]/q par_out_b_reg_30/Q  -type DFF DFF
add mapped point par_out_b[31]/q par_out_b_reg_31/Q  -type DFF DFF
add mapped point state[0]/q state_reg_0/Q  -type DFF DFF
add mapped point state[1]/q state_reg_1/Q  -type DFF DFF
add mapped point count[5]/q count_reg_5/Q  -type DFF DFF
add mapped point out[12]/q out_reg_12/Q  -type DFF DFF
add mapped point out[44]/q out_reg_44/Q  -type DFF DFF
add mapped point out[45]/q out_reg_45/Q  -type DFF DFF
add mapped point out[46]/q out_reg_46/Q  -type DFF DFF
add mapped point out[47]/q out_reg_47/Q  -type DFF DFF
add mapped point out[48]/q out_reg_48/Q  -type DFF DFF
add mapped point out[49]/q out_reg_49/Q  -type DFF DFF
add mapped point out[50]/q out_reg_50/Q  -type DFF DFF
add mapped point out[51]/q out_reg_51/Q  -type DFF DFF
add mapped point out[52]/q out_reg_52/Q  -type DFF DFF
add mapped point out[53]/q out_reg_53/Q  -type DFF DFF
add mapped point out[54]/q out_reg_54/Q  -type DFF DFF
add mapped point out[55]/q out_reg_55/Q  -type DFF DFF
add mapped point out[56]/q out_reg_56/Q  -type DFF DFF
add mapped point out[57]/q out_reg_57/Q  -type DFF DFF
add mapped point out[0]/q out_reg_0/Q  -type DFF DFF
add mapped point out[60]/q out_reg_60/Q  -type DFF DFF
add mapped point out[61]/q out_reg_61/Q  -type DFF DFF
add mapped point out[42]/q out_reg_42/Q  -type DFF DFF
add mapped point out[63]/q out_reg_63/Q  -type DFF DFF
add mapped point out[58]/q out_reg_58/Q  -type DFF DFF
add mapped point out[62]/q out_reg_62/Q  -type DFF DFF
add mapped point out[59]/q out_reg_59/Q  -type DFF DFF
add mapped point out[1]/q out_reg_1/Q  -type DFF DFF
add mapped point out[2]/q out_reg_2/Q  -type DFF DFF
add mapped point out[3]/q out_reg_3/Q  -type DFF DFF
add mapped point out[4]/q out_reg_4/Q  -type DFF DFF
add mapped point out[5]/q out_reg_5/Q  -type DFF DFF
add mapped point out[6]/q out_reg_6/Q  -type DFF DFF
add mapped point out[7]/q out_reg_7/Q  -type DFF DFF
add mapped point out[8]/q out_reg_8/Q  -type DFF DFF
add mapped point out[9]/q out_reg_9/Q  -type DFF DFF
add mapped point out[10]/q out_reg_10/Q  -type DFF DFF
add mapped point out[11]/q out_reg_11/Q  -type DFF DFF
add mapped point out[43]/q out_reg_43/Q  -type DFF DFF
add mapped point out[14]/q out_reg_14/Q  -type DFF DFF
add mapped point out[15]/q out_reg_15/Q  -type DFF DFF
add mapped point out[16]/q out_reg_16/Q  -type DFF DFF
add mapped point out[17]/q out_reg_17/Q  -type DFF DFF
add mapped point out[18]/q out_reg_18/Q  -type DFF DFF
add mapped point out[19]/q out_reg_19/Q  -type DFF DFF
add mapped point out[20]/q out_reg_20/Q  -type DFF DFF
add mapped point out[21]/q out_reg_21/Q  -type DFF DFF
add mapped point out[22]/q out_reg_22/Q  -type DFF DFF
add mapped point out[23]/q out_reg_23/Q  -type DFF DFF
add mapped point out[24]/q out_reg_24/Q  -type DFF DFF
add mapped point out[25]/q out_reg_25/Q  -type DFF DFF
add mapped point out[26]/q out_reg_26/Q  -type DFF DFF
add mapped point out[27]/q out_reg_27/Q  -type DFF DFF
add mapped point out[28]/q out_reg_28/Q  -type DFF DFF
add mapped point out[29]/q out_reg_29/Q  -type DFF DFF
add mapped point out[30]/q out_reg_30/Q  -type DFF DFF
add mapped point out[31]/q out_reg_31/Q  -type DFF DFF
add mapped point out[32]/q out_reg_32/Q  -type DFF DFF
add mapped point out[33]/q out_reg_33/Q  -type DFF DFF
add mapped point out[34]/q out_reg_34/Q  -type DFF DFF
add mapped point out[35]/q out_reg_35/Q  -type DFF DFF
add mapped point out[36]/q out_reg_36/Q  -type DFF DFF
add mapped point out[37]/q out_reg_37/Q  -type DFF DFF
add mapped point out[38]/q out_reg_38/Q  -type DFF DFF
add mapped point out[39]/q out_reg_39/Q  -type DFF DFF
add mapped point out[40]/q out_reg_40/Q  -type DFF DFF
add mapped point out[41]/q out_reg_41/Q  -type DFF DFF
add mapped point out[13]/q out_reg_13/Q  -type DFF DFF
add mapped point count[4]/q count_reg_4/Q  -type DFF DFF
add mapped point count[2]/q count_reg_2/Q  -type DFF DFF
add mapped point count[1]/q count_reg_1/Q  -type DFF DFF
add mapped point count[3]/q count_reg_3/Q  -type DFF DFF
add mapped point count[0]/q count_reg_0/Q  -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
