# ####################################################################

#  Created by Genus(TM) Synthesis Solution 21.12-s068_1 on Thu Jun 11 20:12:34 -03 2026

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design multiplier_param

create_clock -name "clk" -period 2.0 -waveform {0.0 1.0} [get_ports clk]
set_load -pin_load -min 0.0014 [get_ports {out[31]}]
set_load -pin_load -max 0.32 [get_ports {out[31]}]
set_load -pin_load -min 0.0014 [get_ports {out[30]}]
set_load -pin_load -max 0.32 [get_ports {out[30]}]
set_load -pin_load -min 0.0014 [get_ports {out[29]}]
set_load -pin_load -max 0.32 [get_ports {out[29]}]
set_load -pin_load -min 0.0014 [get_ports {out[28]}]
set_load -pin_load -max 0.32 [get_ports {out[28]}]
set_load -pin_load -min 0.0014 [get_ports {out[27]}]
set_load -pin_load -max 0.32 [get_ports {out[27]}]
set_load -pin_load -min 0.0014 [get_ports {out[26]}]
set_load -pin_load -max 0.32 [get_ports {out[26]}]
set_load -pin_load -min 0.0014 [get_ports {out[25]}]
set_load -pin_load -max 0.32 [get_ports {out[25]}]
set_load -pin_load -min 0.0014 [get_ports {out[24]}]
set_load -pin_load -max 0.32 [get_ports {out[24]}]
set_load -pin_load -min 0.0014 [get_ports {out[23]}]
set_load -pin_load -max 0.32 [get_ports {out[23]}]
set_load -pin_load -min 0.0014 [get_ports {out[22]}]
set_load -pin_load -max 0.32 [get_ports {out[22]}]
set_load -pin_load -min 0.0014 [get_ports {out[21]}]
set_load -pin_load -max 0.32 [get_ports {out[21]}]
set_load -pin_load -min 0.0014 [get_ports {out[20]}]
set_load -pin_load -max 0.32 [get_ports {out[20]}]
set_load -pin_load -min 0.0014 [get_ports {out[19]}]
set_load -pin_load -max 0.32 [get_ports {out[19]}]
set_load -pin_load -min 0.0014 [get_ports {out[18]}]
set_load -pin_load -max 0.32 [get_ports {out[18]}]
set_load -pin_load -min 0.0014 [get_ports {out[17]}]
set_load -pin_load -max 0.32 [get_ports {out[17]}]
set_load -pin_load -min 0.0014 [get_ports {out[16]}]
set_load -pin_load -max 0.32 [get_ports {out[16]}]
set_load -pin_load -min 0.0014 [get_ports {out[15]}]
set_load -pin_load -max 0.32 [get_ports {out[15]}]
set_load -pin_load -min 0.0014 [get_ports {out[14]}]
set_load -pin_load -max 0.32 [get_ports {out[14]}]
set_load -pin_load -min 0.0014 [get_ports {out[13]}]
set_load -pin_load -max 0.32 [get_ports {out[13]}]
set_load -pin_load -min 0.0014 [get_ports {out[12]}]
set_load -pin_load -max 0.32 [get_ports {out[12]}]
set_load -pin_load -min 0.0014 [get_ports {out[11]}]
set_load -pin_load -max 0.32 [get_ports {out[11]}]
set_load -pin_load -min 0.0014 [get_ports {out[10]}]
set_load -pin_load -max 0.32 [get_ports {out[10]}]
set_load -pin_load -min 0.0014 [get_ports {out[9]}]
set_load -pin_load -max 0.32 [get_ports {out[9]}]
set_load -pin_load -min 0.0014 [get_ports {out[8]}]
set_load -pin_load -max 0.32 [get_ports {out[8]}]
set_load -pin_load -min 0.0014 [get_ports {out[7]}]
set_load -pin_load -max 0.32 [get_ports {out[7]}]
set_load -pin_load -min 0.0014 [get_ports {out[6]}]
set_load -pin_load -max 0.32 [get_ports {out[6]}]
set_load -pin_load -min 0.0014 [get_ports {out[5]}]
set_load -pin_load -max 0.32 [get_ports {out[5]}]
set_load -pin_load -min 0.0014 [get_ports {out[4]}]
set_load -pin_load -max 0.32 [get_ports {out[4]}]
set_load -pin_load -min 0.0014 [get_ports {out[3]}]
set_load -pin_load -max 0.32 [get_ports {out[3]}]
set_load -pin_load -min 0.0014 [get_ports {out[2]}]
set_load -pin_load -max 0.32 [get_ports {out[2]}]
set_load -pin_load -min 0.0014 [get_ports {out[1]}]
set_load -pin_load -max 0.32 [get_ports {out[1]}]
set_load -pin_load -min 0.0014 [get_ports {out[0]}]
set_load -pin_load -max 0.32 [get_ports {out[0]}]
set_load -pin_load -min 0.0014 [get_ports done]
set_load -pin_load -max 0.32 [get_ports done]
set_false_path -from [get_ports reset]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[15]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[14]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[13]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[12]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[11]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[10]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[9]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[8]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[7]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[6]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[5]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[4]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[3]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[2]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[1]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[0]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[15]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[14]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[13]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[12]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[11]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[10]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[9]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[8]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[7]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[6]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[5]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[4]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[3]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[2]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[1]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[0]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports start]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports reset]
set_input_transition -min 0.003 [get_ports {in1[15]}]
set_input_transition -max 0.16 [get_ports {in1[15]}]
set_input_transition -min 0.003 [get_ports {in1[14]}]
set_input_transition -max 0.16 [get_ports {in1[14]}]
set_input_transition -min 0.003 [get_ports {in1[13]}]
set_input_transition -max 0.16 [get_ports {in1[13]}]
set_input_transition -min 0.003 [get_ports {in1[12]}]
set_input_transition -max 0.16 [get_ports {in1[12]}]
set_input_transition -min 0.003 [get_ports {in1[11]}]
set_input_transition -max 0.16 [get_ports {in1[11]}]
set_input_transition -min 0.003 [get_ports {in1[10]}]
set_input_transition -max 0.16 [get_ports {in1[10]}]
set_input_transition -min 0.003 [get_ports {in1[9]}]
set_input_transition -max 0.16 [get_ports {in1[9]}]
set_input_transition -min 0.003 [get_ports {in1[8]}]
set_input_transition -max 0.16 [get_ports {in1[8]}]
set_input_transition -min 0.003 [get_ports {in1[7]}]
set_input_transition -max 0.16 [get_ports {in1[7]}]
set_input_transition -min 0.003 [get_ports {in1[6]}]
set_input_transition -max 0.16 [get_ports {in1[6]}]
set_input_transition -min 0.003 [get_ports {in1[5]}]
set_input_transition -max 0.16 [get_ports {in1[5]}]
set_input_transition -min 0.003 [get_ports {in1[4]}]
set_input_transition -max 0.16 [get_ports {in1[4]}]
set_input_transition -min 0.003 [get_ports {in1[3]}]
set_input_transition -max 0.16 [get_ports {in1[3]}]
set_input_transition -min 0.003 [get_ports {in1[2]}]
set_input_transition -max 0.16 [get_ports {in1[2]}]
set_input_transition -min 0.003 [get_ports {in1[1]}]
set_input_transition -max 0.16 [get_ports {in1[1]}]
set_input_transition -min 0.003 [get_ports {in1[0]}]
set_input_transition -max 0.16 [get_ports {in1[0]}]
set_input_transition -min 0.003 [get_ports {in2[15]}]
set_input_transition -max 0.16 [get_ports {in2[15]}]
set_input_transition -min 0.003 [get_ports {in2[14]}]
set_input_transition -max 0.16 [get_ports {in2[14]}]
set_input_transition -min 0.003 [get_ports {in2[13]}]
set_input_transition -max 0.16 [get_ports {in2[13]}]
set_input_transition -min 0.003 [get_ports {in2[12]}]
set_input_transition -max 0.16 [get_ports {in2[12]}]
set_input_transition -min 0.003 [get_ports {in2[11]}]
set_input_transition -max 0.16 [get_ports {in2[11]}]
set_input_transition -min 0.003 [get_ports {in2[10]}]
set_input_transition -max 0.16 [get_ports {in2[10]}]
set_input_transition -min 0.003 [get_ports {in2[9]}]
set_input_transition -max 0.16 [get_ports {in2[9]}]
set_input_transition -min 0.003 [get_ports {in2[8]}]
set_input_transition -max 0.16 [get_ports {in2[8]}]
set_input_transition -min 0.003 [get_ports {in2[7]}]
set_input_transition -max 0.16 [get_ports {in2[7]}]
set_input_transition -min 0.003 [get_ports {in2[6]}]
set_input_transition -max 0.16 [get_ports {in2[6]}]
set_input_transition -min 0.003 [get_ports {in2[5]}]
set_input_transition -max 0.16 [get_ports {in2[5]}]
set_input_transition -min 0.003 [get_ports {in2[4]}]
set_input_transition -max 0.16 [get_ports {in2[4]}]
set_input_transition -min 0.003 [get_ports {in2[3]}]
set_input_transition -max 0.16 [get_ports {in2[3]}]
set_input_transition -min 0.003 [get_ports {in2[2]}]
set_input_transition -max 0.16 [get_ports {in2[2]}]
set_input_transition -min 0.003 [get_ports {in2[1]}]
set_input_transition -max 0.16 [get_ports {in2[1]}]
set_input_transition -min 0.003 [get_ports {in2[0]}]
set_input_transition -max 0.16 [get_ports {in2[0]}]
set_input_transition -min 0.003 [get_ports start]
set_input_transition -max 0.16 [get_ports start]
set_input_transition -min 0.003 [get_ports reset]
set_input_transition -max 0.16 [get_ports reset]
set_input_transition -min 0.003 [get_ports clk]
set_input_transition -max 0.16 [get_ports clk]
