set_db {port:multiplier_param_N32/in1[31]} .original_name {in1[31]}
set_db {port:multiplier_param_N32/in1[30]} .original_name {in1[30]}
set_db {port:multiplier_param_N32/in1[29]} .original_name {in1[29]}
set_db {port:multiplier_param_N32/in1[28]} .original_name {in1[28]}
set_db {port:multiplier_param_N32/in1[27]} .original_name {in1[27]}
set_db {port:multiplier_param_N32/in1[26]} .original_name {in1[26]}
set_db {port:multiplier_param_N32/in1[25]} .original_name {in1[25]}
set_db {port:multiplier_param_N32/in1[24]} .original_name {in1[24]}
set_db {port:multiplier_param_N32/in1[23]} .original_name {in1[23]}
set_db {port:multiplier_param_N32/in1[22]} .original_name {in1[22]}
set_db {port:multiplier_param_N32/in1[21]} .original_name {in1[21]}
set_db {port:multiplier_param_N32/in1[20]} .original_name {in1[20]}
set_db {port:multiplier_param_N32/in1[19]} .original_name {in1[19]}
set_db {port:multiplier_param_N32/in1[18]} .original_name {in1[18]}
set_db {port:multiplier_param_N32/in1[17]} .original_name {in1[17]}
set_db {port:multiplier_param_N32/in1[16]} .original_name {in1[16]}
set_db {port:multiplier_param_N32/in1[15]} .original_name {in1[15]}
set_db {port:multiplier_param_N32/in1[14]} .original_name {in1[14]}
set_db {port:multiplier_param_N32/in1[13]} .original_name {in1[13]}
set_db {port:multiplier_param_N32/in1[12]} .original_name {in1[12]}
set_db {port:multiplier_param_N32/in1[11]} .original_name {in1[11]}
set_db {port:multiplier_param_N32/in1[10]} .original_name {in1[10]}
set_db {port:multiplier_param_N32/in1[9]} .original_name {in1[9]}
set_db {port:multiplier_param_N32/in1[8]} .original_name {in1[8]}
set_db {port:multiplier_param_N32/in1[7]} .original_name {in1[7]}
set_db {port:multiplier_param_N32/in1[6]} .original_name {in1[6]}
set_db {port:multiplier_param_N32/in1[5]} .original_name {in1[5]}
set_db {port:multiplier_param_N32/in1[4]} .original_name {in1[4]}
set_db {port:multiplier_param_N32/in1[3]} .original_name {in1[3]}
set_db {port:multiplier_param_N32/in1[2]} .original_name {in1[2]}
set_db {port:multiplier_param_N32/in1[1]} .original_name {in1[1]}
set_db {port:multiplier_param_N32/in1[0]} .original_name {in1[0]}
set_db {port:multiplier_param_N32/in2[31]} .original_name {in2[31]}
set_db {port:multiplier_param_N32/in2[30]} .original_name {in2[30]}
set_db {port:multiplier_param_N32/in2[29]} .original_name {in2[29]}
set_db {port:multiplier_param_N32/in2[28]} .original_name {in2[28]}
set_db {port:multiplier_param_N32/in2[27]} .original_name {in2[27]}
set_db {port:multiplier_param_N32/in2[26]} .original_name {in2[26]}
set_db {port:multiplier_param_N32/in2[25]} .original_name {in2[25]}
set_db {port:multiplier_param_N32/in2[24]} .original_name {in2[24]}
set_db {port:multiplier_param_N32/in2[23]} .original_name {in2[23]}
set_db {port:multiplier_param_N32/in2[22]} .original_name {in2[22]}
set_db {port:multiplier_param_N32/in2[21]} .original_name {in2[21]}
set_db {port:multiplier_param_N32/in2[20]} .original_name {in2[20]}
set_db {port:multiplier_param_N32/in2[19]} .original_name {in2[19]}
set_db {port:multiplier_param_N32/in2[18]} .original_name {in2[18]}
set_db {port:multiplier_param_N32/in2[17]} .original_name {in2[17]}
set_db {port:multiplier_param_N32/in2[16]} .original_name {in2[16]}
set_db {port:multiplier_param_N32/in2[15]} .original_name {in2[15]}
set_db {port:multiplier_param_N32/in2[14]} .original_name {in2[14]}
set_db {port:multiplier_param_N32/in2[13]} .original_name {in2[13]}
set_db {port:multiplier_param_N32/in2[12]} .original_name {in2[12]}
set_db {port:multiplier_param_N32/in2[11]} .original_name {in2[11]}
set_db {port:multiplier_param_N32/in2[10]} .original_name {in2[10]}
set_db {port:multiplier_param_N32/in2[9]} .original_name {in2[9]}
set_db {port:multiplier_param_N32/in2[8]} .original_name {in2[8]}
set_db {port:multiplier_param_N32/in2[7]} .original_name {in2[7]}
set_db {port:multiplier_param_N32/in2[6]} .original_name {in2[6]}
set_db {port:multiplier_param_N32/in2[5]} .original_name {in2[5]}
set_db {port:multiplier_param_N32/in2[4]} .original_name {in2[4]}
set_db {port:multiplier_param_N32/in2[3]} .original_name {in2[3]}
set_db {port:multiplier_param_N32/in2[2]} .original_name {in2[2]}
set_db {port:multiplier_param_N32/in2[1]} .original_name {in2[1]}
set_db {port:multiplier_param_N32/in2[0]} .original_name {in2[0]}
set_db port:multiplier_param_N32/start .original_name {start}
set_db port:multiplier_param_N32/reset .original_name {reset}
set_db port:multiplier_param_N32/clk .original_name {clk}
set_db {port:multiplier_param_N32/out[63]} .original_name {out[63]}
set_db {port:multiplier_param_N32/out[62]} .original_name {out[62]}
set_db {port:multiplier_param_N32/out[61]} .original_name {out[61]}
set_db {port:multiplier_param_N32/out[60]} .original_name {out[60]}
set_db {port:multiplier_param_N32/out[59]} .original_name {out[59]}
set_db {port:multiplier_param_N32/out[58]} .original_name {out[58]}
set_db {port:multiplier_param_N32/out[57]} .original_name {out[57]}
set_db {port:multiplier_param_N32/out[56]} .original_name {out[56]}
set_db {port:multiplier_param_N32/out[55]} .original_name {out[55]}
set_db {port:multiplier_param_N32/out[54]} .original_name {out[54]}
set_db {port:multiplier_param_N32/out[53]} .original_name {out[53]}
set_db {port:multiplier_param_N32/out[52]} .original_name {out[52]}
set_db {port:multiplier_param_N32/out[51]} .original_name {out[51]}
set_db {port:multiplier_param_N32/out[50]} .original_name {out[50]}
set_db {port:multiplier_param_N32/out[49]} .original_name {out[49]}
set_db {port:multiplier_param_N32/out[48]} .original_name {out[48]}
set_db {port:multiplier_param_N32/out[47]} .original_name {out[47]}
set_db {port:multiplier_param_N32/out[46]} .original_name {out[46]}
set_db {port:multiplier_param_N32/out[45]} .original_name {out[45]}
set_db {port:multiplier_param_N32/out[44]} .original_name {out[44]}
set_db {port:multiplier_param_N32/out[43]} .original_name {out[43]}
set_db {port:multiplier_param_N32/out[42]} .original_name {out[42]}
set_db {port:multiplier_param_N32/out[41]} .original_name {out[41]}
set_db {port:multiplier_param_N32/out[40]} .original_name {out[40]}
set_db {port:multiplier_param_N32/out[39]} .original_name {out[39]}
set_db {port:multiplier_param_N32/out[38]} .original_name {out[38]}
set_db {port:multiplier_param_N32/out[37]} .original_name {out[37]}
set_db {port:multiplier_param_N32/out[36]} .original_name {out[36]}
set_db {port:multiplier_param_N32/out[35]} .original_name {out[35]}
set_db {port:multiplier_param_N32/out[34]} .original_name {out[34]}
set_db {port:multiplier_param_N32/out[33]} .original_name {out[33]}
set_db {port:multiplier_param_N32/out[32]} .original_name {out[32]}
set_db {port:multiplier_param_N32/out[31]} .original_name {out[31]}
set_db {port:multiplier_param_N32/out[30]} .original_name {out[30]}
set_db {port:multiplier_param_N32/out[29]} .original_name {out[29]}
set_db {port:multiplier_param_N32/out[28]} .original_name {out[28]}
set_db {port:multiplier_param_N32/out[27]} .original_name {out[27]}
set_db {port:multiplier_param_N32/out[26]} .original_name {out[26]}
set_db {port:multiplier_param_N32/out[25]} .original_name {out[25]}
set_db {port:multiplier_param_N32/out[24]} .original_name {out[24]}
set_db {port:multiplier_param_N32/out[23]} .original_name {out[23]}
set_db {port:multiplier_param_N32/out[22]} .original_name {out[22]}
set_db {port:multiplier_param_N32/out[21]} .original_name {out[21]}
set_db {port:multiplier_param_N32/out[20]} .original_name {out[20]}
set_db {port:multiplier_param_N32/out[19]} .original_name {out[19]}
set_db {port:multiplier_param_N32/out[18]} .original_name {out[18]}
set_db {port:multiplier_param_N32/out[17]} .original_name {out[17]}
set_db {port:multiplier_param_N32/out[16]} .original_name {out[16]}
set_db {port:multiplier_param_N32/out[15]} .original_name {out[15]}
set_db {port:multiplier_param_N32/out[14]} .original_name {out[14]}
set_db {port:multiplier_param_N32/out[13]} .original_name {out[13]}
set_db {port:multiplier_param_N32/out[12]} .original_name {out[12]}
set_db {port:multiplier_param_N32/out[11]} .original_name {out[11]}
set_db {port:multiplier_param_N32/out[10]} .original_name {out[10]}
set_db {port:multiplier_param_N32/out[9]} .original_name {out[9]}
set_db {port:multiplier_param_N32/out[8]} .original_name {out[8]}
set_db {port:multiplier_param_N32/out[7]} .original_name {out[7]}
set_db {port:multiplier_param_N32/out[6]} .original_name {out[6]}
set_db {port:multiplier_param_N32/out[5]} .original_name {out[5]}
set_db {port:multiplier_param_N32/out[4]} .original_name {out[4]}
set_db {port:multiplier_param_N32/out[3]} .original_name {out[3]}
set_db {port:multiplier_param_N32/out[2]} .original_name {out[2]}
set_db {port:multiplier_param_N32/out[1]} .original_name {out[1]}
set_db {port:multiplier_param_N32/out[0]} .original_name {out[0]}
set_db port:multiplier_param_N32/done .original_name {done}



set_db pin:multiplier_param_N32/par_out_a_reg_1/QN .original_name {par_out_a[1]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_2/QN .original_name {par_out_a[2]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_3/QN .original_name {par_out_a[3]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_4/QN .original_name {par_out_a[4]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_5/QN .original_name {par_out_a[5]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_6/Q .original_name {par_out_a[6]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_7/QN .original_name {par_out_a[7]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_8/QN .original_name {par_out_a[8]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_9/QN .original_name {par_out_a[9]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_10/QN .original_name {par_out_a[10]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_11/QN .original_name {par_out_a[11]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_12/QN .original_name {par_out_a[12]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_13/QN .original_name {par_out_a[13]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_14/QN .original_name {par_out_a[14]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_15/QN .original_name {par_out_a[15]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_16/QN .original_name {par_out_a[16]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_17/QN .original_name {par_out_a[17]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_18/QN .original_name {par_out_a[18]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_19/QN .original_name {par_out_a[19]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_20/QN .original_name {par_out_a[20]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_21/QN .original_name {par_out_a[21]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_22/QN .original_name {par_out_a[22]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_23/QN .original_name {par_out_a[23]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_24/QN .original_name {par_out_a[24]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_25/QN .original_name {par_out_a[25]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_26/QN .original_name {par_out_a[26]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_27/QN .original_name {par_out_a[27]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_28/QN .original_name {par_out_a[28]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_29/QN .original_name {par_out_a[29]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_30/QN .original_name {par_out_a[30]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_31/QN .original_name {par_out_a[31]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_0/QN .original_name {par_out_b[0]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_1/Q .original_name {par_out_b[1]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_2/Q .original_name {par_out_b[2]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_3/Q .original_name {par_out_b[3]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_4/Q .original_name {par_out_b[4]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_5/Q .original_name {par_out_b[5]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_6/Q .original_name {par_out_b[6]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_7/Q .original_name {par_out_b[7]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_8/Q .original_name {par_out_b[8]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_9/Q .original_name {par_out_b[9]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_10/Q .original_name {par_out_b[10]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_11/Q .original_name {par_out_b[11]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_12/Q .original_name {par_out_b[12]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_13/Q .original_name {par_out_b[13]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_14/Q .original_name {par_out_b[14]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_15/Q .original_name {par_out_b[15]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_16/Q .original_name {par_out_b[16]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_17/Q .original_name {par_out_b[17]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_18/Q .original_name {par_out_b[18]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_19/Q .original_name {par_out_b[19]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_20/Q .original_name {par_out_b[20]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_21/Q .original_name {par_out_b[21]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_22/Q .original_name {par_out_b[22]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_23/Q .original_name {par_out_b[23]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_24/Q .original_name {par_out_b[24]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_25/Q .original_name {par_out_b[25]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_26/Q .original_name {par_out_b[26]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_27/Q .original_name {par_out_b[27]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_28/Q .original_name {par_out_b[28]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_29/Q .original_name {par_out_b[29]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_30/Q .original_name {par_out_b[30]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_0/QN .original_name {par_out_a[0]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_32/QN .original_name {par_out_a[32]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_33/QN .original_name {par_out_a[33]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_34/QN .original_name {par_out_a[34]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_35/QN .original_name {par_out_a[35]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_36/QN .original_name {par_out_a[36]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_37/QN .original_name {par_out_a[37]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_38/QN .original_name {par_out_a[38]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_39/QN .original_name {par_out_a[39]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_40/QN .original_name {par_out_a[40]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_41/QN .original_name {par_out_a[41]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_42/QN .original_name {par_out_a[42]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_43/QN .original_name {par_out_a[43]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_44/QN .original_name {par_out_a[44]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_45/QN .original_name {par_out_a[45]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_46/QN .original_name {par_out_a[46]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_47/QN .original_name {par_out_a[47]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_48/QN .original_name {par_out_a[48]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_49/QN .original_name {par_out_a[49]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_50/QN .original_name {par_out_a[50]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_51/QN .original_name {par_out_a[51]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_52/QN .original_name {par_out_a[52]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_53/QN .original_name {par_out_a[53]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_54/QN .original_name {par_out_a[54]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_55/QN .original_name {par_out_a[55]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_56/QN .original_name {par_out_a[56]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_57/QN .original_name {par_out_a[57]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_58/QN .original_name {par_out_a[58]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_59/QN .original_name {par_out_a[59]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_60/QN .original_name {par_out_a[60]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_61/QN .original_name {par_out_a[61]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_62/QN .original_name {par_out_a[62]/q}
set_db pin:multiplier_param_N32/par_out_a_reg_63/QN .original_name {par_out_a[63]/q}
set_db pin:multiplier_param_N32/par_out_b_reg_31/Q .original_name {par_out_b[31]/q}
set_db pin:multiplier_param_N32/state_reg_0/Q .original_name {state[0]/q}
set_db pin:multiplier_param_N32/state_reg_1/Q .original_name {state[1]/q}
set_db pin:multiplier_param_N32/count_reg_5/Q .original_name {count[5]/q}
set_db pin:multiplier_param_N32/out_reg_12/Q .original_name {out[12]/q}
set_db pin:multiplier_param_N32/out_reg_44/Q .original_name {out[44]/q}
set_db pin:multiplier_param_N32/out_reg_45/Q .original_name {out[45]/q}
set_db pin:multiplier_param_N32/out_reg_46/Q .original_name {out[46]/q}
set_db pin:multiplier_param_N32/out_reg_47/Q .original_name {out[47]/q}
set_db pin:multiplier_param_N32/out_reg_48/Q .original_name {out[48]/q}
set_db pin:multiplier_param_N32/out_reg_49/Q .original_name {out[49]/q}
set_db pin:multiplier_param_N32/out_reg_50/Q .original_name {out[50]/q}
set_db pin:multiplier_param_N32/out_reg_51/Q .original_name {out[51]/q}
set_db pin:multiplier_param_N32/out_reg_52/Q .original_name {out[52]/q}
set_db pin:multiplier_param_N32/out_reg_53/Q .original_name {out[53]/q}
set_db pin:multiplier_param_N32/out_reg_54/Q .original_name {out[54]/q}
set_db pin:multiplier_param_N32/out_reg_55/Q .original_name {out[55]/q}
set_db pin:multiplier_param_N32/out_reg_56/Q .original_name {out[56]/q}
set_db pin:multiplier_param_N32/out_reg_57/Q .original_name {out[57]/q}
set_db pin:multiplier_param_N32/out_reg_0/Q .original_name {out[0]/q}
set_db pin:multiplier_param_N32/out_reg_60/Q .original_name {out[60]/q}
set_db pin:multiplier_param_N32/out_reg_61/Q .original_name {out[61]/q}
set_db pin:multiplier_param_N32/out_reg_42/Q .original_name {out[42]/q}
set_db pin:multiplier_param_N32/out_reg_63/Q .original_name {out[63]/q}
set_db pin:multiplier_param_N32/out_reg_58/Q .original_name {out[58]/q}
set_db pin:multiplier_param_N32/out_reg_62/Q .original_name {out[62]/q}
set_db pin:multiplier_param_N32/out_reg_59/Q .original_name {out[59]/q}
set_db pin:multiplier_param_N32/out_reg_1/Q .original_name {out[1]/q}
set_db pin:multiplier_param_N32/out_reg_2/Q .original_name {out[2]/q}
set_db pin:multiplier_param_N32/out_reg_3/Q .original_name {out[3]/q}
set_db pin:multiplier_param_N32/out_reg_4/Q .original_name {out[4]/q}
set_db pin:multiplier_param_N32/out_reg_5/Q .original_name {out[5]/q}
set_db pin:multiplier_param_N32/out_reg_6/Q .original_name {out[6]/q}
set_db pin:multiplier_param_N32/out_reg_7/Q .original_name {out[7]/q}
set_db pin:multiplier_param_N32/out_reg_8/Q .original_name {out[8]/q}
set_db pin:multiplier_param_N32/out_reg_9/Q .original_name {out[9]/q}
set_db pin:multiplier_param_N32/out_reg_10/Q .original_name {out[10]/q}
set_db pin:multiplier_param_N32/out_reg_11/Q .original_name {out[11]/q}
set_db pin:multiplier_param_N32/out_reg_43/Q .original_name {out[43]/q}
set_db pin:multiplier_param_N32/out_reg_14/Q .original_name {out[14]/q}
set_db pin:multiplier_param_N32/out_reg_15/Q .original_name {out[15]/q}
set_db pin:multiplier_param_N32/out_reg_16/Q .original_name {out[16]/q}
set_db pin:multiplier_param_N32/out_reg_17/Q .original_name {out[17]/q}
set_db pin:multiplier_param_N32/out_reg_18/Q .original_name {out[18]/q}
set_db pin:multiplier_param_N32/out_reg_19/Q .original_name {out[19]/q}
set_db pin:multiplier_param_N32/out_reg_20/Q .original_name {out[20]/q}
set_db pin:multiplier_param_N32/out_reg_21/Q .original_name {out[21]/q}
set_db pin:multiplier_param_N32/out_reg_22/Q .original_name {out[22]/q}
set_db pin:multiplier_param_N32/out_reg_23/Q .original_name {out[23]/q}
set_db pin:multiplier_param_N32/out_reg_24/Q .original_name {out[24]/q}
set_db pin:multiplier_param_N32/out_reg_25/Q .original_name {out[25]/q}
set_db pin:multiplier_param_N32/out_reg_26/Q .original_name {out[26]/q}
set_db pin:multiplier_param_N32/out_reg_27/Q .original_name {out[27]/q}
set_db pin:multiplier_param_N32/out_reg_28/Q .original_name {out[28]/q}
set_db pin:multiplier_param_N32/out_reg_29/Q .original_name {out[29]/q}
set_db pin:multiplier_param_N32/out_reg_30/Q .original_name {out[30]/q}
set_db pin:multiplier_param_N32/out_reg_31/Q .original_name {out[31]/q}
set_db pin:multiplier_param_N32/out_reg_32/Q .original_name {out[32]/q}
set_db pin:multiplier_param_N32/out_reg_33/Q .original_name {out[33]/q}
set_db pin:multiplier_param_N32/out_reg_34/Q .original_name {out[34]/q}
set_db pin:multiplier_param_N32/out_reg_35/Q .original_name {out[35]/q}
set_db pin:multiplier_param_N32/out_reg_36/Q .original_name {out[36]/q}
set_db pin:multiplier_param_N32/out_reg_37/Q .original_name {out[37]/q}
set_db pin:multiplier_param_N32/out_reg_38/Q .original_name {out[38]/q}
set_db pin:multiplier_param_N32/out_reg_39/Q .original_name {out[39]/q}
set_db pin:multiplier_param_N32/out_reg_40/Q .original_name {out[40]/q}
set_db pin:multiplier_param_N32/out_reg_41/Q .original_name {out[41]/q}
set_db pin:multiplier_param_N32/out_reg_13/Q .original_name {out[13]/q}
set_db pin:multiplier_param_N32/count_reg_4/Q .original_name {count[4]/q}
set_db pin:multiplier_param_N32/count_reg_2/Q .original_name {count[2]/q}
set_db pin:multiplier_param_N32/count_reg_1/Q .original_name {count[1]/q}
set_db pin:multiplier_param_N32/count_reg_3/Q .original_name {count[3]/q}
set_db pin:multiplier_param_N32/count_reg_0/Q .original_name {count[0]/q}
