set_db {port:multiplier/in1[15]} .original_name {in1[15]}
set_db {port:multiplier/in1[14]} .original_name {in1[14]}
set_db {port:multiplier/in1[13]} .original_name {in1[13]}
set_db {port:multiplier/in1[12]} .original_name {in1[12]}
set_db {port:multiplier/in1[11]} .original_name {in1[11]}
set_db {port:multiplier/in1[10]} .original_name {in1[10]}
set_db {port:multiplier/in1[9]} .original_name {in1[9]}
set_db {port:multiplier/in1[8]} .original_name {in1[8]}
set_db {port:multiplier/in1[7]} .original_name {in1[7]}
set_db {port:multiplier/in1[6]} .original_name {in1[6]}
set_db {port:multiplier/in1[5]} .original_name {in1[5]}
set_db {port:multiplier/in1[4]} .original_name {in1[4]}
set_db {port:multiplier/in1[3]} .original_name {in1[3]}
set_db {port:multiplier/in1[2]} .original_name {in1[2]}
set_db {port:multiplier/in1[1]} .original_name {in1[1]}
set_db {port:multiplier/in1[0]} .original_name {in1[0]}
set_db {port:multiplier/in2[15]} .original_name {in2[15]}
set_db {port:multiplier/in2[14]} .original_name {in2[14]}
set_db {port:multiplier/in2[13]} .original_name {in2[13]}
set_db {port:multiplier/in2[12]} .original_name {in2[12]}
set_db {port:multiplier/in2[11]} .original_name {in2[11]}
set_db {port:multiplier/in2[10]} .original_name {in2[10]}
set_db {port:multiplier/in2[9]} .original_name {in2[9]}
set_db {port:multiplier/in2[8]} .original_name {in2[8]}
set_db {port:multiplier/in2[7]} .original_name {in2[7]}
set_db {port:multiplier/in2[6]} .original_name {in2[6]}
set_db {port:multiplier/in2[5]} .original_name {in2[5]}
set_db {port:multiplier/in2[4]} .original_name {in2[4]}
set_db {port:multiplier/in2[3]} .original_name {in2[3]}
set_db {port:multiplier/in2[2]} .original_name {in2[2]}
set_db {port:multiplier/in2[1]} .original_name {in2[1]}
set_db {port:multiplier/in2[0]} .original_name {in2[0]}
set_db port:multiplier/start .original_name {start}
set_db port:multiplier/reset .original_name {reset}
set_db port:multiplier/clk .original_name {clk}
set_db {port:multiplier/out[31]} .original_name {out[31]}
set_db {port:multiplier/out[30]} .original_name {out[30]}
set_db {port:multiplier/out[29]} .original_name {out[29]}
set_db {port:multiplier/out[28]} .original_name {out[28]}
set_db {port:multiplier/out[27]} .original_name {out[27]}
set_db {port:multiplier/out[26]} .original_name {out[26]}
set_db {port:multiplier/out[25]} .original_name {out[25]}
set_db {port:multiplier/out[24]} .original_name {out[24]}
set_db {port:multiplier/out[23]} .original_name {out[23]}
set_db {port:multiplier/out[22]} .original_name {out[22]}
set_db {port:multiplier/out[21]} .original_name {out[21]}
set_db {port:multiplier/out[20]} .original_name {out[20]}
set_db {port:multiplier/out[19]} .original_name {out[19]}
set_db {port:multiplier/out[18]} .original_name {out[18]}
set_db {port:multiplier/out[17]} .original_name {out[17]}
set_db {port:multiplier/out[16]} .original_name {out[16]}
set_db {port:multiplier/out[15]} .original_name {out[15]}
set_db {port:multiplier/out[14]} .original_name {out[14]}
set_db {port:multiplier/out[13]} .original_name {out[13]}
set_db {port:multiplier/out[12]} .original_name {out[12]}
set_db {port:multiplier/out[11]} .original_name {out[11]}
set_db {port:multiplier/out[10]} .original_name {out[10]}
set_db {port:multiplier/out[9]} .original_name {out[9]}
set_db {port:multiplier/out[8]} .original_name {out[8]}
set_db {port:multiplier/out[7]} .original_name {out[7]}
set_db {port:multiplier/out[6]} .original_name {out[6]}
set_db {port:multiplier/out[5]} .original_name {out[5]}
set_db {port:multiplier/out[4]} .original_name {out[4]}
set_db {port:multiplier/out[3]} .original_name {out[3]}
set_db {port:multiplier/out[2]} .original_name {out[2]}
set_db {port:multiplier/out[1]} .original_name {out[1]}
set_db {port:multiplier/out[0]} .original_name {out[0]}
set_db port:multiplier/done .original_name {done}



set_db pin:multiplier/par_out_a_reg_1/QN .original_name {par_out_a[1]/q}
set_db pin:multiplier/par_out_a_reg_2/QN .original_name {par_out_a[2]/q}
set_db pin:multiplier/par_out_a_reg_3/Q .original_name {par_out_a[3]/q}
set_db pin:multiplier/par_out_a_reg_4/Q .original_name {par_out_a[4]/q}
set_db pin:multiplier/par_out_a_reg_5/Q .original_name {par_out_a[5]/q}
set_db pin:multiplier/par_out_a_reg_6/Q .original_name {par_out_a[6]/q}
set_db pin:multiplier/par_out_a_reg_7/QN .original_name {par_out_a[7]/q}
set_db pin:multiplier/par_out_a_reg_8/QN .original_name {par_out_a[8]/q}
set_db pin:multiplier/par_out_a_reg_9/QN .original_name {par_out_a[9]/q}
set_db pin:multiplier/par_out_a_reg_10/QN .original_name {par_out_a[10]/q}
set_db pin:multiplier/par_out_a_reg_11/QN .original_name {par_out_a[11]/q}
set_db pin:multiplier/par_out_a_reg_12/QN .original_name {par_out_a[12]/q}
set_db pin:multiplier/par_out_a_reg_13/QN .original_name {par_out_a[13]/q}
set_db pin:multiplier/par_out_a_reg_14/QN .original_name {par_out_a[14]/q}
set_db pin:multiplier/par_out_a_reg_15/QN .original_name {par_out_a[15]/q}
set_db pin:multiplier/par_out_b_reg_0/QN .original_name {par_out_b[0]/q}
set_db pin:multiplier/par_out_b_reg_1/Q .original_name {par_out_b[1]/q}
set_db pin:multiplier/par_out_b_reg_2/Q .original_name {par_out_b[2]/q}
set_db pin:multiplier/par_out_b_reg_3/Q .original_name {par_out_b[3]/q}
set_db pin:multiplier/par_out_b_reg_4/Q .original_name {par_out_b[4]/q}
set_db pin:multiplier/par_out_b_reg_5/Q .original_name {par_out_b[5]/q}
set_db pin:multiplier/par_out_b_reg_6/Q .original_name {par_out_b[6]/q}
set_db pin:multiplier/par_out_b_reg_7/Q .original_name {par_out_b[7]/q}
set_db pin:multiplier/par_out_b_reg_8/Q .original_name {par_out_b[8]/q}
set_db pin:multiplier/par_out_b_reg_9/Q .original_name {par_out_b[9]/q}
set_db pin:multiplier/par_out_b_reg_10/Q .original_name {par_out_b[10]/q}
set_db pin:multiplier/par_out_b_reg_11/Q .original_name {par_out_b[11]/q}
set_db pin:multiplier/par_out_b_reg_12/Q .original_name {par_out_b[12]/q}
set_db pin:multiplier/par_out_b_reg_13/Q .original_name {par_out_b[13]/q}
set_db pin:multiplier/par_out_b_reg_14/Q .original_name {par_out_b[14]/q}
set_db pin:multiplier/par_out_a_reg_0/QN .original_name {par_out_a[0]/q}
set_db pin:multiplier/par_out_a_reg_16/QN .original_name {par_out_a[16]/q}
set_db pin:multiplier/par_out_a_reg_17/QN .original_name {par_out_a[17]/q}
set_db pin:multiplier/par_out_a_reg_18/QN .original_name {par_out_a[18]/q}
set_db pin:multiplier/par_out_a_reg_19/QN .original_name {par_out_a[19]/q}
set_db pin:multiplier/par_out_a_reg_20/QN .original_name {par_out_a[20]/q}
set_db pin:multiplier/par_out_a_reg_21/QN .original_name {par_out_a[21]/q}
set_db pin:multiplier/par_out_a_reg_22/QN .original_name {par_out_a[22]/q}
set_db pin:multiplier/par_out_a_reg_23/QN .original_name {par_out_a[23]/q}
set_db pin:multiplier/par_out_a_reg_24/QN .original_name {par_out_a[24]/q}
set_db pin:multiplier/par_out_a_reg_25/QN .original_name {par_out_a[25]/q}
set_db pin:multiplier/par_out_a_reg_26/QN .original_name {par_out_a[26]/q}
set_db pin:multiplier/par_out_a_reg_27/QN .original_name {par_out_a[27]/q}
set_db pin:multiplier/par_out_a_reg_28/QN .original_name {par_out_a[28]/q}
set_db pin:multiplier/par_out_a_reg_29/QN .original_name {par_out_a[29]/q}
set_db pin:multiplier/par_out_a_reg_30/QN .original_name {par_out_a[30]/q}
set_db pin:multiplier/par_out_a_reg_31/QN .original_name {par_out_a[31]/q}
set_db pin:multiplier/par_out_b_reg_15/Q .original_name {par_out_b[15]/q}
set_db pin:multiplier/state_reg_0/Q .original_name {state[0]/q}
set_db pin:multiplier/count_reg_4/Q .original_name {count[4]/q}
set_db pin:multiplier/state_reg_1/Q .original_name {state[1]/q}
set_db pin:multiplier/count_reg_3/Q .original_name {count[3]/q}
set_db pin:multiplier/out_reg_22/Q .original_name {out[22]/q}
set_db pin:multiplier/out_reg_14/Q .original_name {out[14]/q}
set_db pin:multiplier/out_reg_15/Q .original_name {out[15]/q}
set_db pin:multiplier/out_reg_16/Q .original_name {out[16]/q}
set_db pin:multiplier/out_reg_17/Q .original_name {out[17]/q}
set_db pin:multiplier/out_reg_18/Q .original_name {out[18]/q}
set_db pin:multiplier/out_reg_19/Q .original_name {out[19]/q}
set_db pin:multiplier/out_reg_20/Q .original_name {out[20]/q}
set_db pin:multiplier/out_reg_21/Q .original_name {out[21]/q}
set_db pin:multiplier/out_reg_13/Q .original_name {out[13]/q}
set_db pin:multiplier/out_reg_23/Q .original_name {out[23]/q}
set_db pin:multiplier/out_reg_24/Q .original_name {out[24]/q}
set_db pin:multiplier/out_reg_25/Q .original_name {out[25]/q}
set_db pin:multiplier/out_reg_26/Q .original_name {out[26]/q}
set_db pin:multiplier/out_reg_27/Q .original_name {out[27]/q}
set_db pin:multiplier/out_reg_28/Q .original_name {out[28]/q}
set_db pin:multiplier/out_reg_29/Q .original_name {out[29]/q}
set_db pin:multiplier/out_reg_30/Q .original_name {out[30]/q}
set_db pin:multiplier/out_reg_8/Q .original_name {out[8]/q}
set_db pin:multiplier/out_reg_0/Q .original_name {out[0]/q}
set_db pin:multiplier/out_reg_1/Q .original_name {out[1]/q}
set_db pin:multiplier/out_reg_2/Q .original_name {out[2]/q}
set_db pin:multiplier/out_reg_3/Q .original_name {out[3]/q}
set_db pin:multiplier/out_reg_4/Q .original_name {out[4]/q}
set_db pin:multiplier/out_reg_5/Q .original_name {out[5]/q}
set_db pin:multiplier/out_reg_6/Q .original_name {out[6]/q}
set_db pin:multiplier/out_reg_7/Q .original_name {out[7]/q}
set_db pin:multiplier/out_reg_31/Q .original_name {out[31]/q}
set_db pin:multiplier/out_reg_9/Q .original_name {out[9]/q}
set_db pin:multiplier/out_reg_10/Q .original_name {out[10]/q}
set_db pin:multiplier/out_reg_11/Q .original_name {out[11]/q}
set_db pin:multiplier/out_reg_12/Q .original_name {out[12]/q}
set_db pin:multiplier/count_reg_2/Q .original_name {count[2]/q}
set_db pin:multiplier/count_reg_1/Q .original_name {count[1]/q}
set_db pin:multiplier/count_reg_0/Q .original_name {count[0]/q}
