set_db {port:multiplier_param_N8/in1[7]} .original_name {in1[7]}
set_db {port:multiplier_param_N8/in1[6]} .original_name {in1[6]}
set_db {port:multiplier_param_N8/in1[5]} .original_name {in1[5]}
set_db {port:multiplier_param_N8/in1[4]} .original_name {in1[4]}
set_db {port:multiplier_param_N8/in1[3]} .original_name {in1[3]}
set_db {port:multiplier_param_N8/in1[2]} .original_name {in1[2]}
set_db {port:multiplier_param_N8/in1[1]} .original_name {in1[1]}
set_db {port:multiplier_param_N8/in1[0]} .original_name {in1[0]}
set_db {port:multiplier_param_N8/in2[7]} .original_name {in2[7]}
set_db {port:multiplier_param_N8/in2[6]} .original_name {in2[6]}
set_db {port:multiplier_param_N8/in2[5]} .original_name {in2[5]}
set_db {port:multiplier_param_N8/in2[4]} .original_name {in2[4]}
set_db {port:multiplier_param_N8/in2[3]} .original_name {in2[3]}
set_db {port:multiplier_param_N8/in2[2]} .original_name {in2[2]}
set_db {port:multiplier_param_N8/in2[1]} .original_name {in2[1]}
set_db {port:multiplier_param_N8/in2[0]} .original_name {in2[0]}
set_db port:multiplier_param_N8/start .original_name {start}
set_db port:multiplier_param_N8/reset .original_name {reset}
set_db port:multiplier_param_N8/clk .original_name {clk}
set_db {port:multiplier_param_N8/out[15]} .original_name {out[15]}
set_db {port:multiplier_param_N8/out[14]} .original_name {out[14]}
set_db {port:multiplier_param_N8/out[13]} .original_name {out[13]}
set_db {port:multiplier_param_N8/out[12]} .original_name {out[12]}
set_db {port:multiplier_param_N8/out[11]} .original_name {out[11]}
set_db {port:multiplier_param_N8/out[10]} .original_name {out[10]}
set_db {port:multiplier_param_N8/out[9]} .original_name {out[9]}
set_db {port:multiplier_param_N8/out[8]} .original_name {out[8]}
set_db {port:multiplier_param_N8/out[7]} .original_name {out[7]}
set_db {port:multiplier_param_N8/out[6]} .original_name {out[6]}
set_db {port:multiplier_param_N8/out[5]} .original_name {out[5]}
set_db {port:multiplier_param_N8/out[4]} .original_name {out[4]}
set_db {port:multiplier_param_N8/out[3]} .original_name {out[3]}
set_db {port:multiplier_param_N8/out[2]} .original_name {out[2]}
set_db {port:multiplier_param_N8/out[1]} .original_name {out[1]}
set_db {port:multiplier_param_N8/out[0]} .original_name {out[0]}
set_db port:multiplier_param_N8/done .original_name {done}



set_db pin:multiplier_param_N8/par_out_b_reg_0/QN .original_name {par_out_b[0]/q}
set_db pin:multiplier_param_N8/par_out_a_reg_7/QN .original_name {par_out_a[7]/q}
set_db pin:multiplier_param_N8/par_out_b_reg_1/Q .original_name {par_out_b[1]/q}
set_db pin:multiplier_param_N8/par_out_a_reg_6/QN .original_name {par_out_a[6]/q}
set_db pin:multiplier_param_N8/par_out_b_reg_2/Q .original_name {par_out_b[2]/q}
set_db pin:multiplier_param_N8/par_out_a_reg_5/QN .original_name {par_out_a[5]/q}
set_db pin:multiplier_param_N8/par_out_b_reg_3/Q .original_name {par_out_b[3]/q}
set_db pin:multiplier_param_N8/par_out_a_reg_4/QN .original_name {par_out_a[4]/q}
set_db pin:multiplier_param_N8/par_out_b_reg_4/Q .original_name {par_out_b[4]/q}
set_db pin:multiplier_param_N8/par_out_a_reg_3/QN .original_name {par_out_a[3]/q}
set_db pin:multiplier_param_N8/par_out_a_reg_2/QN .original_name {par_out_a[2]/q}
set_db pin:multiplier_param_N8/par_out_b_reg_5/Q .original_name {par_out_b[5]/q}
set_db pin:multiplier_param_N8/par_out_a_reg_1/QN .original_name {par_out_a[1]/q}
set_db pin:multiplier_param_N8/par_out_b_reg_6/Q .original_name {par_out_b[6]/q}
set_db pin:multiplier_param_N8/par_out_a_reg_15/QN .original_name {par_out_a[15]/q}
set_db pin:multiplier_param_N8/par_out_a_reg_14/QN .original_name {par_out_a[14]/q}
set_db pin:multiplier_param_N8/par_out_a_reg_13/QN .original_name {par_out_a[13]/q}
set_db pin:multiplier_param_N8/par_out_a_reg_12/QN .original_name {par_out_a[12]/q}
set_db pin:multiplier_param_N8/par_out_a_reg_11/QN .original_name {par_out_a[11]/q}
set_db pin:multiplier_param_N8/par_out_a_reg_10/QN .original_name {par_out_a[10]/q}
set_db pin:multiplier_param_N8/par_out_a_reg_9/QN .original_name {par_out_a[9]/q}
set_db pin:multiplier_param_N8/par_out_a_reg_8/QN .original_name {par_out_a[8]/q}
set_db pin:multiplier_param_N8/par_out_a_reg_0/QN .original_name {par_out_a[0]/q}
set_db pin:multiplier_param_N8/par_out_b_reg_7/Q .original_name {par_out_b[7]/q}
set_db pin:multiplier_param_N8/state_reg_0/Q .original_name {state[0]/q}
set_db pin:multiplier_param_N8/count_reg_3/Q .original_name {count[3]/q}
set_db pin:multiplier_param_N8/state_reg_1/Q .original_name {state[1]/q}
set_db pin:multiplier_param_N8/out_reg_0/Q .original_name {out[0]/q}
set_db pin:multiplier_param_N8/out_reg_1/Q .original_name {out[1]/q}
set_db pin:multiplier_param_N8/out_reg_2/Q .original_name {out[2]/q}
set_db pin:multiplier_param_N8/out_reg_3/Q .original_name {out[3]/q}
set_db pin:multiplier_param_N8/out_reg_4/Q .original_name {out[4]/q}
set_db pin:multiplier_param_N8/out_reg_5/Q .original_name {out[5]/q}
set_db pin:multiplier_param_N8/out_reg_6/Q .original_name {out[6]/q}
set_db pin:multiplier_param_N8/out_reg_7/Q .original_name {out[7]/q}
set_db pin:multiplier_param_N8/out_reg_8/Q .original_name {out[8]/q}
set_db pin:multiplier_param_N8/out_reg_9/Q .original_name {out[9]/q}
set_db pin:multiplier_param_N8/out_reg_10/Q .original_name {out[10]/q}
set_db pin:multiplier_param_N8/out_reg_11/Q .original_name {out[11]/q}
set_db pin:multiplier_param_N8/out_reg_12/Q .original_name {out[12]/q}
set_db pin:multiplier_param_N8/out_reg_13/Q .original_name {out[13]/q}
set_db pin:multiplier_param_N8/out_reg_14/Q .original_name {out[14]/q}
set_db pin:multiplier_param_N8/out_reg_15/Q .original_name {out[15]/q}
set_db pin:multiplier_param_N8/count_reg_2/Q .original_name {count[2]/q}
set_db pin:multiplier_param_N8/count_reg_1/Q .original_name {count[1]/q}
set_db pin:multiplier_param_N8/count_reg_0/Q .original_name {count[0]/q}
