# ####################################################################

#  Created by Genus(TM) Synthesis Solution 21.12-s068_1 on Thu Jun 11 20:30:43 -03 2026

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design multiplier_param_N32

create_clock -name "clk" -period 2.0 -waveform {0.0 1.0} [get_ports clk]
set_load -pin_load -min 0.0014 [get_ports {out[63]}]
set_load -pin_load -max 0.32 [get_ports {out[63]}]
set_load -pin_load -min 0.0014 [get_ports {out[62]}]
set_load -pin_load -max 0.32 [get_ports {out[62]}]
set_load -pin_load -min 0.0014 [get_ports {out[61]}]
set_load -pin_load -max 0.32 [get_ports {out[61]}]
set_load -pin_load -min 0.0014 [get_ports {out[60]}]
set_load -pin_load -max 0.32 [get_ports {out[60]}]
set_load -pin_load -min 0.0014 [get_ports {out[59]}]
set_load -pin_load -max 0.32 [get_ports {out[59]}]
set_load -pin_load -min 0.0014 [get_ports {out[58]}]
set_load -pin_load -max 0.32 [get_ports {out[58]}]
set_load -pin_load -min 0.0014 [get_ports {out[57]}]
set_load -pin_load -max 0.32 [get_ports {out[57]}]
set_load -pin_load -min 0.0014 [get_ports {out[56]}]
set_load -pin_load -max 0.32 [get_ports {out[56]}]
set_load -pin_load -min 0.0014 [get_ports {out[55]}]
set_load -pin_load -max 0.32 [get_ports {out[55]}]
set_load -pin_load -min 0.0014 [get_ports {out[54]}]
set_load -pin_load -max 0.32 [get_ports {out[54]}]
set_load -pin_load -min 0.0014 [get_ports {out[53]}]
set_load -pin_load -max 0.32 [get_ports {out[53]}]
set_load -pin_load -min 0.0014 [get_ports {out[52]}]
set_load -pin_load -max 0.32 [get_ports {out[52]}]
set_load -pin_load -min 0.0014 [get_ports {out[51]}]
set_load -pin_load -max 0.32 [get_ports {out[51]}]
set_load -pin_load -min 0.0014 [get_ports {out[50]}]
set_load -pin_load -max 0.32 [get_ports {out[50]}]
set_load -pin_load -min 0.0014 [get_ports {out[49]}]
set_load -pin_load -max 0.32 [get_ports {out[49]}]
set_load -pin_load -min 0.0014 [get_ports {out[48]}]
set_load -pin_load -max 0.32 [get_ports {out[48]}]
set_load -pin_load -min 0.0014 [get_ports {out[47]}]
set_load -pin_load -max 0.32 [get_ports {out[47]}]
set_load -pin_load -min 0.0014 [get_ports {out[46]}]
set_load -pin_load -max 0.32 [get_ports {out[46]}]
set_load -pin_load -min 0.0014 [get_ports {out[45]}]
set_load -pin_load -max 0.32 [get_ports {out[45]}]
set_load -pin_load -min 0.0014 [get_ports {out[44]}]
set_load -pin_load -max 0.32 [get_ports {out[44]}]
set_load -pin_load -min 0.0014 [get_ports {out[43]}]
set_load -pin_load -max 0.32 [get_ports {out[43]}]
set_load -pin_load -min 0.0014 [get_ports {out[42]}]
set_load -pin_load -max 0.32 [get_ports {out[42]}]
set_load -pin_load -min 0.0014 [get_ports {out[41]}]
set_load -pin_load -max 0.32 [get_ports {out[41]}]
set_load -pin_load -min 0.0014 [get_ports {out[40]}]
set_load -pin_load -max 0.32 [get_ports {out[40]}]
set_load -pin_load -min 0.0014 [get_ports {out[39]}]
set_load -pin_load -max 0.32 [get_ports {out[39]}]
set_load -pin_load -min 0.0014 [get_ports {out[38]}]
set_load -pin_load -max 0.32 [get_ports {out[38]}]
set_load -pin_load -min 0.0014 [get_ports {out[37]}]
set_load -pin_load -max 0.32 [get_ports {out[37]}]
set_load -pin_load -min 0.0014 [get_ports {out[36]}]
set_load -pin_load -max 0.32 [get_ports {out[36]}]
set_load -pin_load -min 0.0014 [get_ports {out[35]}]
set_load -pin_load -max 0.32 [get_ports {out[35]}]
set_load -pin_load -min 0.0014 [get_ports {out[34]}]
set_load -pin_load -max 0.32 [get_ports {out[34]}]
set_load -pin_load -min 0.0014 [get_ports {out[33]}]
set_load -pin_load -max 0.32 [get_ports {out[33]}]
set_load -pin_load -min 0.0014 [get_ports {out[32]}]
set_load -pin_load -max 0.32 [get_ports {out[32]}]
set_load -pin_load -min 0.0014 [get_ports {out[31]}]
set_load -pin_load -max 0.32 [get_ports {out[31]}]
set_load -pin_load -min 0.0014 [get_ports {out[30]}]
set_load -pin_load -max 0.32 [get_ports {out[30]}]
set_load -pin_load -min 0.0014 [get_ports {out[29]}]
set_load -pin_load -max 0.32 [get_ports {out[29]}]
set_load -pin_load -min 0.0014 [get_ports {out[28]}]
set_load -pin_load -max 0.32 [get_ports {out[28]}]
set_load -pin_load -min 0.0014 [get_ports {out[27]}]
set_load -pin_load -max 0.32 [get_ports {out[27]}]
set_load -pin_load -min 0.0014 [get_ports {out[26]}]
set_load -pin_load -max 0.32 [get_ports {out[26]}]
set_load -pin_load -min 0.0014 [get_ports {out[25]}]
set_load -pin_load -max 0.32 [get_ports {out[25]}]
set_load -pin_load -min 0.0014 [get_ports {out[24]}]
set_load -pin_load -max 0.32 [get_ports {out[24]}]
set_load -pin_load -min 0.0014 [get_ports {out[23]}]
set_load -pin_load -max 0.32 [get_ports {out[23]}]
set_load -pin_load -min 0.0014 [get_ports {out[22]}]
set_load -pin_load -max 0.32 [get_ports {out[22]}]
set_load -pin_load -min 0.0014 [get_ports {out[21]}]
set_load -pin_load -max 0.32 [get_ports {out[21]}]
set_load -pin_load -min 0.0014 [get_ports {out[20]}]
set_load -pin_load -max 0.32 [get_ports {out[20]}]
set_load -pin_load -min 0.0014 [get_ports {out[19]}]
set_load -pin_load -max 0.32 [get_ports {out[19]}]
set_load -pin_load -min 0.0014 [get_ports {out[18]}]
set_load -pin_load -max 0.32 [get_ports {out[18]}]
set_load -pin_load -min 0.0014 [get_ports {out[17]}]
set_load -pin_load -max 0.32 [get_ports {out[17]}]
set_load -pin_load -min 0.0014 [get_ports {out[16]}]
set_load -pin_load -max 0.32 [get_ports {out[16]}]
set_load -pin_load -min 0.0014 [get_ports {out[15]}]
set_load -pin_load -max 0.32 [get_ports {out[15]}]
set_load -pin_load -min 0.0014 [get_ports {out[14]}]
set_load -pin_load -max 0.32 [get_ports {out[14]}]
set_load -pin_load -min 0.0014 [get_ports {out[13]}]
set_load -pin_load -max 0.32 [get_ports {out[13]}]
set_load -pin_load -min 0.0014 [get_ports {out[12]}]
set_load -pin_load -max 0.32 [get_ports {out[12]}]
set_load -pin_load -min 0.0014 [get_ports {out[11]}]
set_load -pin_load -max 0.32 [get_ports {out[11]}]
set_load -pin_load -min 0.0014 [get_ports {out[10]}]
set_load -pin_load -max 0.32 [get_ports {out[10]}]
set_load -pin_load -min 0.0014 [get_ports {out[9]}]
set_load -pin_load -max 0.32 [get_ports {out[9]}]
set_load -pin_load -min 0.0014 [get_ports {out[8]}]
set_load -pin_load -max 0.32 [get_ports {out[8]}]
set_load -pin_load -min 0.0014 [get_ports {out[7]}]
set_load -pin_load -max 0.32 [get_ports {out[7]}]
set_load -pin_load -min 0.0014 [get_ports {out[6]}]
set_load -pin_load -max 0.32 [get_ports {out[6]}]
set_load -pin_load -min 0.0014 [get_ports {out[5]}]
set_load -pin_load -max 0.32 [get_ports {out[5]}]
set_load -pin_load -min 0.0014 [get_ports {out[4]}]
set_load -pin_load -max 0.32 [get_ports {out[4]}]
set_load -pin_load -min 0.0014 [get_ports {out[3]}]
set_load -pin_load -max 0.32 [get_ports {out[3]}]
set_load -pin_load -min 0.0014 [get_ports {out[2]}]
set_load -pin_load -max 0.32 [get_ports {out[2]}]
set_load -pin_load -min 0.0014 [get_ports {out[1]}]
set_load -pin_load -max 0.32 [get_ports {out[1]}]
set_load -pin_load -min 0.0014 [get_ports {out[0]}]
set_load -pin_load -max 0.32 [get_ports {out[0]}]
set_load -pin_load -min 0.0014 [get_ports done]
set_load -pin_load -max 0.32 [get_ports done]
set_false_path -from [get_ports reset]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[31]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[30]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[29]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[28]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[27]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[26]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[25]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[24]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[23]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[22]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[21]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[20]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[19]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[18]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[17]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[16]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[15]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[14]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[13]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[12]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[11]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[10]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[9]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[8]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[7]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[6]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[5]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[4]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[3]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[2]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[1]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in1[0]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[31]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[30]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[29]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[28]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[27]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[26]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[25]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[24]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[23]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[22]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[21]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[20]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[19]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[18]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[17]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[16]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[15]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[14]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[13]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[12]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[11]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[10]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[9]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[8]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[7]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[6]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[5]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[4]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[3]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[2]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[1]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports {in2[0]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports start]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.2 [get_ports reset]
set_input_transition -min 0.003 [get_ports {in1[31]}]
set_input_transition -max 0.16 [get_ports {in1[31]}]
set_input_transition -min 0.003 [get_ports {in1[30]}]
set_input_transition -max 0.16 [get_ports {in1[30]}]
set_input_transition -min 0.003 [get_ports {in1[29]}]
set_input_transition -max 0.16 [get_ports {in1[29]}]
set_input_transition -min 0.003 [get_ports {in1[28]}]
set_input_transition -max 0.16 [get_ports {in1[28]}]
set_input_transition -min 0.003 [get_ports {in1[27]}]
set_input_transition -max 0.16 [get_ports {in1[27]}]
set_input_transition -min 0.003 [get_ports {in1[26]}]
set_input_transition -max 0.16 [get_ports {in1[26]}]
set_input_transition -min 0.003 [get_ports {in1[25]}]
set_input_transition -max 0.16 [get_ports {in1[25]}]
set_input_transition -min 0.003 [get_ports {in1[24]}]
set_input_transition -max 0.16 [get_ports {in1[24]}]
set_input_transition -min 0.003 [get_ports {in1[23]}]
set_input_transition -max 0.16 [get_ports {in1[23]}]
set_input_transition -min 0.003 [get_ports {in1[22]}]
set_input_transition -max 0.16 [get_ports {in1[22]}]
set_input_transition -min 0.003 [get_ports {in1[21]}]
set_input_transition -max 0.16 [get_ports {in1[21]}]
set_input_transition -min 0.003 [get_ports {in1[20]}]
set_input_transition -max 0.16 [get_ports {in1[20]}]
set_input_transition -min 0.003 [get_ports {in1[19]}]
set_input_transition -max 0.16 [get_ports {in1[19]}]
set_input_transition -min 0.003 [get_ports {in1[18]}]
set_input_transition -max 0.16 [get_ports {in1[18]}]
set_input_transition -min 0.003 [get_ports {in1[17]}]
set_input_transition -max 0.16 [get_ports {in1[17]}]
set_input_transition -min 0.003 [get_ports {in1[16]}]
set_input_transition -max 0.16 [get_ports {in1[16]}]
set_input_transition -min 0.003 [get_ports {in1[15]}]
set_input_transition -max 0.16 [get_ports {in1[15]}]
set_input_transition -min 0.003 [get_ports {in1[14]}]
set_input_transition -max 0.16 [get_ports {in1[14]}]
set_input_transition -min 0.003 [get_ports {in1[13]}]
set_input_transition -max 0.16 [get_ports {in1[13]}]
set_input_transition -min 0.003 [get_ports {in1[12]}]
set_input_transition -max 0.16 [get_ports {in1[12]}]
set_input_transition -min 0.003 [get_ports {in1[11]}]
set_input_transition -max 0.16 [get_ports {in1[11]}]
set_input_transition -min 0.003 [get_ports {in1[10]}]
set_input_transition -max 0.16 [get_ports {in1[10]}]
set_input_transition -min 0.003 [get_ports {in1[9]}]
set_input_transition -max 0.16 [get_ports {in1[9]}]
set_input_transition -min 0.003 [get_ports {in1[8]}]
set_input_transition -max 0.16 [get_ports {in1[8]}]
set_input_transition -min 0.003 [get_ports {in1[7]}]
set_input_transition -max 0.16 [get_ports {in1[7]}]
set_input_transition -min 0.003 [get_ports {in1[6]}]
set_input_transition -max 0.16 [get_ports {in1[6]}]
set_input_transition -min 0.003 [get_ports {in1[5]}]
set_input_transition -max 0.16 [get_ports {in1[5]}]
set_input_transition -min 0.003 [get_ports {in1[4]}]
set_input_transition -max 0.16 [get_ports {in1[4]}]
set_input_transition -min 0.003 [get_ports {in1[3]}]
set_input_transition -max 0.16 [get_ports {in1[3]}]
set_input_transition -min 0.003 [get_ports {in1[2]}]
set_input_transition -max 0.16 [get_ports {in1[2]}]
set_input_transition -min 0.003 [get_ports {in1[1]}]
set_input_transition -max 0.16 [get_ports {in1[1]}]
set_input_transition -min 0.003 [get_ports {in1[0]}]
set_input_transition -max 0.16 [get_ports {in1[0]}]
set_input_transition -min 0.003 [get_ports {in2[31]}]
set_input_transition -max 0.16 [get_ports {in2[31]}]
set_input_transition -min 0.003 [get_ports {in2[30]}]
set_input_transition -max 0.16 [get_ports {in2[30]}]
set_input_transition -min 0.003 [get_ports {in2[29]}]
set_input_transition -max 0.16 [get_ports {in2[29]}]
set_input_transition -min 0.003 [get_ports {in2[28]}]
set_input_transition -max 0.16 [get_ports {in2[28]}]
set_input_transition -min 0.003 [get_ports {in2[27]}]
set_input_transition -max 0.16 [get_ports {in2[27]}]
set_input_transition -min 0.003 [get_ports {in2[26]}]
set_input_transition -max 0.16 [get_ports {in2[26]}]
set_input_transition -min 0.003 [get_ports {in2[25]}]
set_input_transition -max 0.16 [get_ports {in2[25]}]
set_input_transition -min 0.003 [get_ports {in2[24]}]
set_input_transition -max 0.16 [get_ports {in2[24]}]
set_input_transition -min 0.003 [get_ports {in2[23]}]
set_input_transition -max 0.16 [get_ports {in2[23]}]
set_input_transition -min 0.003 [get_ports {in2[22]}]
set_input_transition -max 0.16 [get_ports {in2[22]}]
set_input_transition -min 0.003 [get_ports {in2[21]}]
set_input_transition -max 0.16 [get_ports {in2[21]}]
set_input_transition -min 0.003 [get_ports {in2[20]}]
set_input_transition -max 0.16 [get_ports {in2[20]}]
set_input_transition -min 0.003 [get_ports {in2[19]}]
set_input_transition -max 0.16 [get_ports {in2[19]}]
set_input_transition -min 0.003 [get_ports {in2[18]}]
set_input_transition -max 0.16 [get_ports {in2[18]}]
set_input_transition -min 0.003 [get_ports {in2[17]}]
set_input_transition -max 0.16 [get_ports {in2[17]}]
set_input_transition -min 0.003 [get_ports {in2[16]}]
set_input_transition -max 0.16 [get_ports {in2[16]}]
set_input_transition -min 0.003 [get_ports {in2[15]}]
set_input_transition -max 0.16 [get_ports {in2[15]}]
set_input_transition -min 0.003 [get_ports {in2[14]}]
set_input_transition -max 0.16 [get_ports {in2[14]}]
set_input_transition -min 0.003 [get_ports {in2[13]}]
set_input_transition -max 0.16 [get_ports {in2[13]}]
set_input_transition -min 0.003 [get_ports {in2[12]}]
set_input_transition -max 0.16 [get_ports {in2[12]}]
set_input_transition -min 0.003 [get_ports {in2[11]}]
set_input_transition -max 0.16 [get_ports {in2[11]}]
set_input_transition -min 0.003 [get_ports {in2[10]}]
set_input_transition -max 0.16 [get_ports {in2[10]}]
set_input_transition -min 0.003 [get_ports {in2[9]}]
set_input_transition -max 0.16 [get_ports {in2[9]}]
set_input_transition -min 0.003 [get_ports {in2[8]}]
set_input_transition -max 0.16 [get_ports {in2[8]}]
set_input_transition -min 0.003 [get_ports {in2[7]}]
set_input_transition -max 0.16 [get_ports {in2[7]}]
set_input_transition -min 0.003 [get_ports {in2[6]}]
set_input_transition -max 0.16 [get_ports {in2[6]}]
set_input_transition -min 0.003 [get_ports {in2[5]}]
set_input_transition -max 0.16 [get_ports {in2[5]}]
set_input_transition -min 0.003 [get_ports {in2[4]}]
set_input_transition -max 0.16 [get_ports {in2[4]}]
set_input_transition -min 0.003 [get_ports {in2[3]}]
set_input_transition -max 0.16 [get_ports {in2[3]}]
set_input_transition -min 0.003 [get_ports {in2[2]}]
set_input_transition -max 0.16 [get_ports {in2[2]}]
set_input_transition -min 0.003 [get_ports {in2[1]}]
set_input_transition -max 0.16 [get_ports {in2[1]}]
set_input_transition -min 0.003 [get_ports {in2[0]}]
set_input_transition -max 0.16 [get_ports {in2[0]}]
set_input_transition -min 0.003 [get_ports start]
set_input_transition -max 0.16 [get_ports start]
set_input_transition -min 0.003 [get_ports reset]
set_input_transition -max 0.16 [get_ports reset]
set_input_transition -min 0.003 [get_ports clk]
set_input_transition -max 0.16 [get_ports clk]
