set_db port:busca_padrao/Bus2IP_Clk .original_name {Bus2IP_Clk}
set_db port:busca_padrao/Bus2IP_Reset .original_name {Bus2IP_Reset}
set_db {port:busca_padrao/Bus2IP_Data[7]} .original_name {Bus2IP_Data[7]}
set_db {port:busca_padrao/Bus2IP_Data[6]} .original_name {Bus2IP_Data[6]}
set_db {port:busca_padrao/Bus2IP_Data[5]} .original_name {Bus2IP_Data[5]}
set_db {port:busca_padrao/Bus2IP_Data[4]} .original_name {Bus2IP_Data[4]}
set_db {port:busca_padrao/Bus2IP_Data[3]} .original_name {Bus2IP_Data[3]}
set_db {port:busca_padrao/Bus2IP_Data[2]} .original_name {Bus2IP_Data[2]}
set_db {port:busca_padrao/Bus2IP_Data[1]} .original_name {Bus2IP_Data[1]}
set_db {port:busca_padrao/Bus2IP_Data[0]} .original_name {Bus2IP_Data[0]}
set_db {port:busca_padrao/Bus2IP_RdCE[0]} .original_name {Bus2IP_RdCE[0]}
set_db {port:busca_padrao/Bus2IP_RdCE[1]} .original_name {Bus2IP_RdCE[1]}
set_db {port:busca_padrao/Bus2IP_RdCE[2]} .original_name {Bus2IP_RdCE[2]}
set_db {port:busca_padrao/Bus2IP_RdCE[3]} .original_name {Bus2IP_RdCE[3]}
set_db {port:busca_padrao/Bus2IP_RdCE[4]} .original_name {Bus2IP_RdCE[4]}
set_db {port:busca_padrao/Bus2IP_RdCE[5]} .original_name {Bus2IP_RdCE[5]}
set_db {port:busca_padrao/Bus2IP_RdCE[6]} .original_name {Bus2IP_RdCE[6]}
set_db {port:busca_padrao/Bus2IP_RdCE[7]} .original_name {Bus2IP_RdCE[7]}
set_db {port:busca_padrao/Bus2IP_RdCE[8]} .original_name {Bus2IP_RdCE[8]}
set_db {port:busca_padrao/Bus2IP_RdCE[9]} .original_name {Bus2IP_RdCE[9]}
set_db {port:busca_padrao/Bus2IP_RdCE[10]} .original_name {Bus2IP_RdCE[10]}
set_db {port:busca_padrao/Bus2IP_RdCE[11]} .original_name {Bus2IP_RdCE[11]}
set_db {port:busca_padrao/Bus2IP_RdCE[12]} .original_name {Bus2IP_RdCE[12]}
set_db {port:busca_padrao/Bus2IP_RdCE[13]} .original_name {Bus2IP_RdCE[13]}
set_db {port:busca_padrao/Bus2IP_RdCE[14]} .original_name {Bus2IP_RdCE[14]}
set_db {port:busca_padrao/Bus2IP_WrCE[0]} .original_name {Bus2IP_WrCE[0]}
set_db {port:busca_padrao/Bus2IP_WrCE[1]} .original_name {Bus2IP_WrCE[1]}
set_db {port:busca_padrao/Bus2IP_WrCE[2]} .original_name {Bus2IP_WrCE[2]}
set_db {port:busca_padrao/Bus2IP_WrCE[3]} .original_name {Bus2IP_WrCE[3]}
set_db {port:busca_padrao/Bus2IP_WrCE[4]} .original_name {Bus2IP_WrCE[4]}
set_db {port:busca_padrao/Bus2IP_WrCE[5]} .original_name {Bus2IP_WrCE[5]}
set_db {port:busca_padrao/Bus2IP_WrCE[6]} .original_name {Bus2IP_WrCE[6]}
set_db {port:busca_padrao/Bus2IP_WrCE[7]} .original_name {Bus2IP_WrCE[7]}
set_db {port:busca_padrao/Bus2IP_WrCE[8]} .original_name {Bus2IP_WrCE[8]}
set_db {port:busca_padrao/Bus2IP_WrCE[9]} .original_name {Bus2IP_WrCE[9]}
set_db {port:busca_padrao/Bus2IP_WrCE[10]} .original_name {Bus2IP_WrCE[10]}
set_db {port:busca_padrao/Bus2IP_WrCE[11]} .original_name {Bus2IP_WrCE[11]}
set_db {port:busca_padrao/Bus2IP_WrCE[12]} .original_name {Bus2IP_WrCE[12]}
set_db {port:busca_padrao/Bus2IP_WrCE[13]} .original_name {Bus2IP_WrCE[13]}
set_db {port:busca_padrao/Bus2IP_WrCE[14]} .original_name {Bus2IP_WrCE[14]}
set_db {port:busca_padrao/IP2Bus_Data[7]} .original_name {IP2Bus_Data[7]}
set_db {port:busca_padrao/IP2Bus_Data[6]} .original_name {IP2Bus_Data[6]}
set_db {port:busca_padrao/IP2Bus_Data[5]} .original_name {IP2Bus_Data[5]}
set_db {port:busca_padrao/IP2Bus_Data[4]} .original_name {IP2Bus_Data[4]}
set_db {port:busca_padrao/IP2Bus_Data[3]} .original_name {IP2Bus_Data[3]}
set_db {port:busca_padrao/IP2Bus_Data[2]} .original_name {IP2Bus_Data[2]}
set_db {port:busca_padrao/IP2Bus_Data[1]} .original_name {IP2Bus_Data[1]}
set_db {port:busca_padrao/IP2Bus_Data[0]} .original_name {IP2Bus_Data[0]}
set_db port:busca_padrao/user_int .original_name {user_int}



set_db pin:busca_padrao/slv_reg_reg_4_2/Q .original_name {slv_reg[4][2]/q}
set_db pin:busca_padrao/slv_reg_reg_6_5/Q .original_name {slv_reg[6][5]/q}
set_db pin:busca_padrao/slv_reg_reg_5_1/Q .original_name {slv_reg[5][1]/q}
set_db pin:busca_padrao/slv_reg_reg_6_7/Q .original_name {slv_reg[6][7]/q}
set_db pin:busca_padrao/slv_reg_reg_4_3/Q .original_name {slv_reg[4][3]/q}
set_db pin:busca_padrao/slv_reg_reg_4_1/Q .original_name {slv_reg[4][1]/q}
set_db pin:busca_padrao/slv_reg_reg_5_5/Q .original_name {slv_reg[5][5]/q}
set_db pin:busca_padrao/slv_reg_reg_9_0/Q .original_name {slv_reg[9][0]/q}
set_db pin:busca_padrao/slv_reg_reg_4_0/Q .original_name {slv_reg[4][0]/q}
set_db pin:busca_padrao/slv_reg_reg_4_6/Q .original_name {slv_reg[4][6]/q}
set_db pin:busca_padrao/slv_reg_reg_4_7/Q .original_name {slv_reg[4][7]/q}
set_db pin:busca_padrao/slv_reg_reg_4_5/Q .original_name {slv_reg[4][5]/q}
set_db pin:busca_padrao/slv_reg_reg_6_1/Q .original_name {slv_reg[6][1]/q}
set_db pin:busca_padrao/slv_reg_reg_5_0/Q .original_name {slv_reg[5][0]/q}
set_db pin:busca_padrao/slv_reg_reg_7_0/Q .original_name {slv_reg[7][0]/q}
set_db pin:busca_padrao/slv_reg_reg_7_5/Q .original_name {slv_reg[7][5]/q}
set_db pin:busca_padrao/slv_reg_reg_7_6/Q .original_name {slv_reg[7][6]/q}
set_db pin:busca_padrao/slv_reg_reg_7_7/Q .original_name {slv_reg[7][7]/q}
set_db pin:busca_padrao/slv_reg_reg_7_4/Q .original_name {slv_reg[7][4]/q}
set_db pin:busca_padrao/slv_reg_reg_5_2/Q .original_name {slv_reg[5][2]/q}
set_db pin:busca_padrao/slv_reg_reg_4_4/Q .original_name {slv_reg[4][4]/q}
set_db pin:busca_padrao/slv_reg_reg_7_1/Q .original_name {slv_reg[7][1]/q}
set_db pin:busca_padrao/slv_reg_reg_5_6/Q .original_name {slv_reg[5][6]/q}
set_db pin:busca_padrao/slv_reg_reg_5_7/Q .original_name {slv_reg[5][7]/q}
set_db pin:busca_padrao/slv_reg_reg_6_0/Q .original_name {slv_reg[6][0]/q}
set_db pin:busca_padrao/slv_reg_reg_6_2/Q .original_name {slv_reg[6][2]/q}
set_db pin:busca_padrao/slv_reg_reg_6_3/Q .original_name {slv_reg[6][3]/q}
set_db pin:busca_padrao/slv_reg_reg_6_4/Q .original_name {slv_reg[6][4]/q}
set_db pin:busca_padrao/slv_reg_reg_6_6/Q .original_name {slv_reg[6][6]/q}
set_db pin:busca_padrao/slv_reg_reg_7_2/Q .original_name {slv_reg[7][2]/q}
set_db pin:busca_padrao/slv_reg_reg_7_3/Q .original_name {slv_reg[7][3]/q}
set_db pin:busca_padrao/slv_reg_reg_5_4/Q .original_name {slv_reg[5][4]/q}
set_db pin:busca_padrao/slv_reg_reg_5_3/Q .original_name {slv_reg[5][3]/q}
set_db pin:busca_padrao/slv_reg_reg_3_1/Q .original_name {slv_reg[3][1]/q}
set_db pin:busca_padrao/slv_reg_reg_2_1/Q .original_name {slv_reg[2][1]/q}
set_db pin:busca_padrao/slv_reg_reg_0_5/Q .original_name {slv_reg[0][5]/q}
set_db pin:busca_padrao/slv_reg_reg_1_3/Q .original_name {slv_reg[1][3]/q}
set_db pin:busca_padrao/slv_reg_reg_3_5/Q .original_name {slv_reg[3][5]/q}
set_db pin:busca_padrao/slv_reg_reg_1_0/Q .original_name {slv_reg[1][0]/q}
set_db pin:busca_padrao/slv_reg_reg_1_1/Q .original_name {slv_reg[1][1]/q}
set_db pin:busca_padrao/slv_reg_reg_0_1/Q .original_name {slv_reg[0][1]/q}
set_db pin:busca_padrao/slv_reg_reg_0_7/Q .original_name {slv_reg[0][7]/q}
set_db pin:busca_padrao/slv_reg_reg_2_2/Q .original_name {slv_reg[2][2]/q}
set_db pin:busca_padrao/slv_reg_reg_0_0/Q .original_name {slv_reg[0][0]/q}
set_db pin:busca_padrao/slv_reg_reg_0_2/Q .original_name {slv_reg[0][2]/q}
set_db pin:busca_padrao/slv_reg_reg_0_3/Q .original_name {slv_reg[0][3]/q}
set_db pin:busca_padrao/slv_reg_reg_0_6/Q .original_name {slv_reg[0][6]/q}
set_db pin:busca_padrao/slv_reg_reg_0_4/Q .original_name {slv_reg[0][4]/q}
set_db pin:busca_padrao/slv_reg_reg_1_5/Q .original_name {slv_reg[1][5]/q}
set_db pin:busca_padrao/slv_reg_reg_3_7/Q .original_name {slv_reg[3][7]/q}
set_db pin:busca_padrao/slv_reg_reg_2_3/Q .original_name {slv_reg[2][3]/q}
set_db pin:busca_padrao/slv_reg_reg_2_6/Q .original_name {slv_reg[2][6]/q}
set_db pin:busca_padrao/slv_reg_reg_2_7/Q .original_name {slv_reg[2][7]/q}
set_db pin:busca_padrao/slv_reg_reg_1_2/Q .original_name {slv_reg[1][2]/q}
set_db pin:busca_padrao/slv_reg_reg_3_2/Q .original_name {slv_reg[3][2]/q}
set_db pin:busca_padrao/slv_reg_reg_2_0/Q .original_name {slv_reg[2][0]/q}
set_db pin:busca_padrao/slv_reg_reg_1_7/Q .original_name {slv_reg[1][7]/q}
set_db pin:busca_padrao/slv_reg_reg_2_5/Q .original_name {slv_reg[2][5]/q}
set_db pin:busca_padrao/slv_reg_reg_3_6/Q .original_name {slv_reg[3][6]/q}
set_db pin:busca_padrao/slv_reg_reg_1_4/Q .original_name {slv_reg[1][4]/q}
set_db pin:busca_padrao/slv_reg_reg_1_6/Q .original_name {slv_reg[1][6]/q}
set_db pin:busca_padrao/slv_reg_reg_2_4/Q .original_name {slv_reg[2][4]/q}
set_db pin:busca_padrao/slv_reg_reg_3_3/Q .original_name {slv_reg[3][3]/q}
set_db pin:busca_padrao/slv_reg_reg_3_4/Q .original_name {slv_reg[3][4]/q}
set_db pin:busca_padrao/slv_reg_reg_3_0/Q .original_name {slv_reg[3][0]/q}
set_db pin:busca_padrao/slv_reg_reg_10_4/Q .original_name {slv_reg[10][4]/q}
set_db pin:busca_padrao/slv_reg_reg_10_3/Q .original_name {slv_reg[10][3]/q}
set_db pin:busca_padrao/slv_reg_reg_13_1/Q .original_name {slv_reg[13][1]/q}
set_db pin:busca_padrao/slv_reg_reg_13_2/Q .original_name {slv_reg[13][2]/q}
set_db pin:busca_padrao/endy_reg_1/Q .original_name {endy[1]/q}
set_db pin:busca_padrao/slv_reg_reg_14_1/Q .original_name {slv_reg[14][1]/q}
set_db pin:busca_padrao/slv_reg_reg_14_2/Q .original_name {slv_reg[14][2]/q}
set_db pin:busca_padrao/slv_reg_reg_14_3/Q .original_name {slv_reg[14][3]/q}
set_db pin:busca_padrao/slv_reg_reg_13_0/Q .original_name {slv_reg[13][0]/q}
set_db pin:busca_padrao/slv_reg_reg_14_0/Q .original_name {slv_reg[14][0]/q}
set_db pin:busca_padrao/slv_reg_reg_13_3/Q .original_name {slv_reg[13][3]/q}
set_db pin:busca_padrao/endy_reg_2/Q .original_name {endy[2]/q}
set_db pin:busca_padrao/endy_reg_0/Q .original_name {endy[0]/q}
set_db pin:busca_padrao/endy_reg_3/Q .original_name {endy[3]/q}
set_db pin:busca_padrao/slv_reg_reg_12_3/Q .original_name {slv_reg[12][3]/q}
set_db pin:busca_padrao/slv_reg_reg_11_1/Q .original_name {slv_reg[11][1]/q}
set_db pin:busca_padrao/slv_reg_reg_12_0/Q .original_name {slv_reg[12][0]/q}
set_db pin:busca_padrao/slv_reg_reg_12_1/Q .original_name {slv_reg[12][1]/q}
set_db pin:busca_padrao/slv_reg_reg_12_2/Q .original_name {slv_reg[12][2]/q}
set_db pin:busca_padrao/slv_reg_reg_11_3/Q .original_name {slv_reg[11][3]/q}
set_db pin:busca_padrao/slv_reg_reg_11_2/Q .original_name {slv_reg[11][2]/q}
set_db pin:busca_padrao/slv_reg_reg_11_0/Q .original_name {slv_reg[11][0]/q}
set_db pin:busca_padrao/slv_reg_reg_10_2/Q .original_name {slv_reg[10][2]/q}
set_db pin:busca_padrao/slv_reg_reg_10_0/Q .original_name {slv_reg[10][0]/q}
set_db pin:busca_padrao/slv_reg_reg_10_1/Q .original_name {slv_reg[10][1]/q}
set_db pin:busca_padrao/EA_reg_3/Q .original_name {EA[3]/q}
set_db pin:busca_padrao/EA_reg_1/Q .original_name {EA[1]/q}
set_db pin:busca_padrao/EA_reg_2/Q .original_name {EA[2]/q}
set_db pin:busca_padrao/EA_reg_0/Q .original_name {EA[0]/q}
set_db pin:busca_padrao/address_reg_7/QN .original_name {address[7]/q}
set_db pin:busca_padrao/address_reg_3/QN .original_name {address[3]/q}
set_db pin:busca_padrao/address_reg_0/QN .original_name {address[0]/q}
set_db pin:busca_padrao/address_reg_1/QN .original_name {address[1]/q}
set_db pin:busca_padrao/address_reg_2/QN .original_name {address[2]/q}
set_db pin:busca_padrao/address_reg_4/QN .original_name {address[4]/q}
set_db pin:busca_padrao/address_reg_6/Q .original_name {address[6]/q}
set_db pin:busca_padrao/address_reg_5/QN .original_name {address[5]/q}
set_db pin:busca_padrao/user_int_reg/Q .original_name {user_int/q}
set_db pin:busca_padrao/reseta_bit_slv_reg0_reg/Q .original_name {reseta_bit_slv_reg0/q}
set_db pin:busca_padrao/endx_reg_0/Q .original_name {endx[0]/q}
set_db pin:busca_padrao/slv_reg_reg_8_1/Q .original_name {slv_reg[8][1]/q}
set_db pin:busca_padrao/slv_reg_reg_8_7/Q .original_name {slv_reg[8][7]/q}
set_db pin:busca_padrao/slv_reg_reg_8_6/Q .original_name {slv_reg[8][6]/q}
set_db pin:busca_padrao/slv_reg_reg_8_4/Q .original_name {slv_reg[8][4]/q}
set_db pin:busca_padrao/slv_reg_reg_8_2/Q .original_name {slv_reg[8][2]/q}
set_db pin:busca_padrao/slv_reg_reg_8_0/Q .original_name {slv_reg[8][0]/q}
set_db pin:busca_padrao/slv_reg_reg_8_5/Q .original_name {slv_reg[8][5]/q}
set_db pin:busca_padrao/slv_reg_reg_8_3/Q .original_name {slv_reg[8][3]/q}
set_db pin:busca_padrao/endx_reg_3/Q .original_name {endx[3]/q}
set_db pin:busca_padrao/endx_reg_1/Q .original_name {endx[1]/q}
set_db pin:busca_padrao/endx_reg_2/Q .original_name {endx[2]/q}
