
// Generated by Cadence Genus(TM) Synthesis Solution 21.12-s068_1
// Generated on: Jun  2 2026 19:39:03 -03 (Jun  2 2026 22:39:03 UTC)

// Verification Directory fv/busca_padrao 

module busca_padrao(Bus2IP_Clk, Bus2IP_Reset, Bus2IP_Data, Bus2IP_RdCE,
     Bus2IP_WrCE, IP2Bus_Data, user_int, chip_scan_se, chip_scan_tm,
     chip_sdi_1, chip_sdo_1, chip_sdi_2, chip_sdo_2);
  input Bus2IP_Clk, Bus2IP_Reset, chip_scan_se, chip_scan_tm,
       chip_sdi_1, chip_sdi_2;
  input [7:0] Bus2IP_Data;
  input [0:14] Bus2IP_RdCE, Bus2IP_WrCE;
  output [7:0] IP2Bus_Data;
  output user_int, chip_sdo_1, chip_sdo_2;
  wire Bus2IP_Clk, Bus2IP_Reset, chip_scan_se, chip_scan_tm,
       chip_sdi_1, chip_sdi_2;
  wire [7:0] Bus2IP_Data;
  wire [0:14] Bus2IP_RdCE, Bus2IP_WrCE;
  wire [7:0] IP2Bus_Data;
  wire user_int, chip_sdo_1, chip_sdo_2;
  wire EA_0, EA_1, EA_2, EA_3, address_0, address_1, address_2,
       address_3;
  wire address_4, address_5, address_6, address_7, endx_0, endy_0,
       endy_1, endy_2;
  wire n_1, n_2, n_20, n_21, n_23, n_28, n_34, n_35;
  wire n_39, n_41, n_43, n_46, n_49, n_53, n_55, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_75, n_81, n_82;
  wire n_83, n_84, n_85, n_86, n_89, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_106, n_107, n_108, n_109;
  wire n_110, n_111, n_112, n_113, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_126, n_127, n_128, n_129, n_130;
  wire n_131, n_132, n_133, n_134, n_135, n_136, n_137, n_138;
  wire n_139, n_140, n_141, n_142, n_143, n_144, n_145, n_146;
  wire n_147, n_148, n_149, n_150, n_151, n_152, n_153, n_154;
  wire n_155, n_156, n_157, n_158, n_159, n_160, n_161, n_162;
  wire n_163, n_164, n_165, n_166, n_167, n_168, n_169, n_170;
  wire n_171, n_172, n_173, n_176, n_177, n_178, n_179, n_180;
  wire n_181, n_182, n_183, n_184, n_185, n_186, n_187, n_188;
  wire n_189, n_190, n_191, n_192, n_193, n_194, n_195, n_196;
  wire n_197, n_199, n_200, n_201, n_202, n_203, n_204, n_205;
  wire n_206, n_207, n_208, n_209, n_210, n_211, n_212, n_213;
  wire n_214, n_215, n_216, n_217, n_218, n_219, n_220, n_221;
  wire n_222, n_223, n_224, n_225, n_226, n_227, n_228, n_229;
  wire n_230, n_231, n_232, n_233, n_234, n_235, n_236, n_237;
  wire n_238, n_239, n_240, n_241, n_242, n_243, n_244, n_245;
  wire n_246, n_247, n_248, n_249, n_250, n_251, n_252, n_253;
  wire n_254, n_255, n_256, n_257, n_259, n_260, n_261, n_262;
  wire n_263, n_264, n_265, n_266, n_267, n_268, n_269, n_270;
  wire n_271, n_273, n_274, n_275, n_276, n_277, n_278, n_279;
  wire n_280, n_281, n_282, n_283, n_284, n_285, n_286, n_287;
  wire n_288, n_289, n_290, n_291, n_292, n_293, n_294, n_295;
  wire n_296, n_297, n_298, n_299, n_300, n_302, n_303, n_304;
  wire n_305, n_306, n_307, n_308, n_309, n_310, n_311, n_312;
  wire n_313, n_314, n_315, n_316, n_317, n_318, n_319, n_320;
  wire n_321, n_322, n_323, n_324, n_325, n_326, n_327, n_328;
  wire n_329, n_330, n_331, n_332, n_333, n_334, n_335, n_336;
  wire n_337, n_338, n_339, n_340, n_341, n_342, n_343, n_344;
  wire n_345, n_346, n_347, n_348, n_349, n_350, n_351, n_352;
  wire n_353, n_354, n_355, n_356, n_357, n_358, n_359, n_360;
  wire n_361, n_362, n_363, n_364, n_365, n_366, n_367, n_368;
  wire n_369, n_370, n_371, n_372, n_373, n_374, n_375, n_376;
  wire n_377, n_378, n_379, n_380, n_381, n_382, n_383, n_386;
  wire n_387, n_388, n_389, n_390, n_391, n_392, n_393, n_394;
  wire n_395, n_396, n_397, n_398, n_399, n_400, n_401, n_402;
  wire n_403, n_404, n_405, n_406, n_408, n_409, n_410, n_411;
  wire n_412, n_413, n_414, n_415, n_416, n_417, n_418, n_419;
  wire n_420, n_421, n_422, n_423, n_424, n_425, n_426, n_427;
  wire n_428, n_429, n_430, n_431, n_432, n_433, n_434, n_435;
  wire n_436, n_437, n_438, n_440, n_441, n_442, n_443, n_444;
  wire n_445, n_446, n_447, n_448, n_449, n_450, n_451, n_452;
  wire n_455, n_456, n_457, n_458, n_459, n_460, n_461, n_462;
  wire n_463, n_464, n_465, n_466, n_467, n_468, n_469, n_470;
  wire n_471, n_472, n_473, n_474, n_475, n_476, n_477, n_480;
  wire n_483, n_484, n_485, n_486, n_487, n_488, n_489, n_490;
  wire n_491, n_494, n_497, n_498, n_499, n_500, n_501, n_502;
  wire n_503, n_506, n_507, n_508, n_509, n_510, n_511, n_512;
  wire n_513, n_514, n_515, n_516, n_517, n_518, n_519, n_520;
  wire n_521, n_522, n_523, n_524, n_525, n_526, n_527, n_528;
  wire n_529, n_531, n_532, n_533, n_534, n_535, n_536, n_537;
  wire n_538, n_539, n_542, n_543, n_545, n_546, n_554, n_556;
  wire n_559, n_560, n_561, n_562, n_563, n_564, n_565, n_566;
  wire n_567, n_568, n_570, n_571, n_572, n_573, n_574, n_575;
  wire n_576, n_577, n_578, n_579, n_580, n_581, n_582, n_583;
  wire n_584, n_585, n_586, n_587, n_588, n_589, n_590, n_592;
  wire n_593, n_594, n_595, n_596, n_597, n_598, n_599, n_600;
  wire n_601, n_602, n_604, n_605, n_606, n_607, n_608, n_609;
  wire n_610, n_611, n_612, n_613, n_614, n_615, n_616, n_617;
  wire n_618, n_619, n_620, n_621, n_622, n_624, n_625, n_626;
  wire n_627, n_628, n_629, n_630, n_631, n_632, n_633, n_634;
  wire n_635, n_636, n_637, n_638, n_639, n_640, n_641, n_642;
  wire n_643, n_644, n_645, n_646, n_647, n_648, n_649, n_650;
  wire n_651, n_652, n_653, n_654, n_655, n_656, n_657, n_658;
  wire n_659, n_660, n_661, n_662, n_663, n_664, n_665, n_666;
  wire n_667, n_668, n_669, n_670, n_671, n_672, n_673, n_674;
  wire n_675, n_676, n_677, n_678, n_679, n_680, n_681, n_682;
  wire n_683, n_684, n_685, n_686, n_687, n_689, n_690, n_691;
  wire n_692, n_693, n_694, n_695, n_696, n_700, n_726, n_727;
  wire n_728, n_729, n_730, n_731, n_732, n_733, n_734, n_744;
  wire n_745, n_746, n_747, n_748, n_749, n_750, n_751, n_752;
  wire n_753, n_754, n_755, n_756, n_757, n_758, n_759, n_760;
  wire n_761, n_762, n_763, n_764, n_765, n_766, n_767, n_768;
  wire n_769, n_770, n_771, n_772, n_773, n_774, n_775, n_776;
  wire n_777, n_778, n_779, n_780, n_781, n_782, n_783, n_784;
  wire n_785, n_786, n_787, n_788, n_789, n_790, n_791, n_792;
  wire n_793, n_794, n_795, n_796, n_797, n_798, n_799, n_800;
  wire n_801, n_802, n_803, n_804, n_805, n_806, n_807, n_808;
  wire n_809, n_810, n_811, n_812, n_813, n_814, n_815, n_816;
  wire n_817, n_818, n_819, n_820, n_821, n_822, n_823, n_824;
  wire n_825, n_826, n_827, n_828, n_829, n_830, n_831, n_832;
  wire n_833, n_834, n_835, n_836, n_837, n_838, n_839, n_840;
  wire n_841, n_842, n_843, n_844, n_845, n_846, n_847, n_848;
  wire n_849, n_850, n_851, n_852, n_853, n_854, n_855, n_857;
  wire n_861, reseta_bit_slv_reg0, slv_reg_0_0, slv_reg_0_1,
       slv_reg_0_2, slv_reg_0_3, slv_reg_0_4, slv_reg_0_5;
  wire slv_reg_0_6, slv_reg_0_7, slv_reg_1_0, slv_reg_1_1, slv_reg_1_2,
       slv_reg_1_3, slv_reg_1_4, slv_reg_1_5;
  wire slv_reg_1_6, slv_reg_1_7, slv_reg_2_0, slv_reg_2_1, slv_reg_2_2,
       slv_reg_2_3, slv_reg_2_4, slv_reg_2_5;
  wire slv_reg_2_6, slv_reg_2_7, slv_reg_3_0, slv_reg_3_1, slv_reg_3_2,
       slv_reg_3_3, slv_reg_3_4, slv_reg_3_5;
  wire slv_reg_3_6, slv_reg_3_7, slv_reg_4_0, slv_reg_4_1, slv_reg_4_2,
       slv_reg_4_3, slv_reg_4_4, slv_reg_4_5;
  wire slv_reg_4_6, slv_reg_4_7, slv_reg_5_0, slv_reg_5_1, slv_reg_5_2,
       slv_reg_5_3, slv_reg_5_4, slv_reg_5_5;
  wire slv_reg_5_6, slv_reg_5_7, slv_reg_6_0, slv_reg_6_1, slv_reg_6_2,
       slv_reg_6_3, slv_reg_6_4, slv_reg_6_5;
  wire slv_reg_6_6, slv_reg_6_7, slv_reg_7_0, slv_reg_7_1, slv_reg_7_2,
       slv_reg_7_3, slv_reg_7_4, slv_reg_7_5;
  wire slv_reg_7_6, slv_reg_7_7, slv_reg_9_0, slv_reg_10_0,
       slv_reg_10_1, slv_reg_10_2, slv_reg_10_3, slv_reg_10_4;
  wire slv_reg_11_0, slv_reg_11_1, slv_reg_11_2, slv_reg_11_3,
       slv_reg_12_0, slv_reg_12_1, slv_reg_12_2, slv_reg_12_3;
  wire slv_reg_13_0, slv_reg_13_1, slv_reg_13_2, slv_reg_13_3,
       slv_reg_14_0, slv_reg_14_1, slv_reg_14_2, slv_reg_14_3;
  assign chip_sdo_2 = user_int;
  assign IP2Bus_Data[5] = 1'b0;
  assign IP2Bus_Data[6] = 1'b0;
  assign IP2Bus_Data[7] = 1'b0;
  HS65_GS_NOR3X4 g23649__2398(.A (n_687), .B (n_682), .C (n_691), .Z
       (n_695));
  HS65_GS_AOI112X4 g23650__5107(.A (n_726), .B (n_685), .C (n_690), .D
       (n_692), .Z (n_694));
  HS65_GS_OR2X9 g23651__6260(.A (n_692), .B (n_691), .Z (n_693));
  HS65_GS_OAI112X5 g23656__4319(.A (n_605), .B (n_675), .C (n_422), .D
       (n_686), .Z (n_690));
  HS65_GS_AO311X9 g23652__8428(.A (n_726), .B (n_684), .C (n_683), .D
       (n_687), .E (n_681), .Z (n_689));
  HS65_GS_OAI311X5 g23657__5526(.A (n_652), .B (n_648), .C (n_664), .D
       (n_686), .E (n_679), .Z (n_691));
  HS65_GS_AO12X9 g23655__6783(.A (n_684), .B (n_683), .C (n_585), .Z
       (n_685));
  HS65_GS_OAI12X6 g23659__3680(.A (n_625), .B (n_678), .C (n_680), .Z
       (n_692));
  HS65_GS_NAND4ABX6 g23661__1617(.A (n_635), .B (n_645), .C (n_647), .D
       (n_677), .Z (n_686));
  HS65_GS_AO311X9 g23653__2802(.A (n_577), .B (n_653), .C (n_674), .D
       (n_423), .E (n_676), .Z (n_682));
  HS65_GS_NOR3X4 g23660__1705(.A (n_580), .B (n_660), .C (n_673), .Z
       (n_683));
  HS65_GS_NAND4ABX3 g23654__5122(.A (n_183), .B (n_451), .C (n_680), .D
       (n_679), .Z (n_681));
  HS65_GS_NAND4ABX3 g23668__8246(.A (n_671), .B (n_575), .C (n_621), .D
       (n_649), .Z (n_678));
  HS65_GS_NOR2X6 g23658__7098(.A (n_596), .B (n_672), .Z (n_687));
  HS65_GS_NOR3X4 g23666__6131(.A (n_578), .B (n_595), .C (n_670), .Z
       (n_677));
  HS65_GS_IVX9 g23662(.A (n_680), .Z (n_676));
  HS65_GS_NAND4ABX3 g23667__1881(.A (n_601), .B (n_659), .C (n_634), .D
       (n_665), .Z (n_675));
  HS65_GS_NOR3X4 g23670__5115(.A (n_572), .B (n_598), .C (n_669), .Z
       (n_674));
  HS65_GS_NAND4ABX3 g23671__7482(.A (n_597), .B (n_563), .C (n_620), .D
       (n_661), .Z (n_673));
  HS65_GS_NAND4ABX3 g23663__4733(.A (n_568), .B (n_579), .C (n_654), .D
       (n_666), .Z (n_672));
  HS65_GS_NAND4ABX3 g23664__6161(.A (n_668), .B (n_662), .C (n_611), .D
       (n_650), .Z (n_679));
  HS65_GS_NAND4ABX6 g23665__9315(.A (n_612), .B (n_663), .C (n_651), .D
       (n_655), .Z (n_680));
  HS65_GS_OAI211X5 g23674__9945(.A (n_769), .B (n_667), .C (n_657), .D
       (n_730), .Z (n_671));
  HS65_GS_NAND3X5 g23679__2883(.A (n_656), .B (n_571), .C (n_600), .Z
       (n_670));
  HS65_GS_NAND4ABX3 g23675__2346(.A (n_646), .B (n_607), .C (n_631), .D
       (n_615), .Z (n_669));
  HS65_GS_OAI211X5 g23672__1666(.A (slv_reg_5_0), .B (n_667), .C
       (n_566), .D (n_641), .Z (n_668));
  HS65_GS_NOR4ABX4 g23669__7410(.A (n_613), .B (n_636), .C (n_642), .D
       (n_626), .Z (n_666));
  HS65_GS_NOR3X4 g23676__6417(.A (n_624), .B (n_610), .C (n_629), .Z
       (n_665));
  HS65_GS_NAND4ABX3 g23680__5477(.A (n_630), .B (n_609), .C (n_639), .D
       (n_619), .Z (n_664));
  HS65_GS_NAND3X5 g23678__2398(.A (n_627), .B (n_640), .C (n_616), .Z
       (n_663));
  HS65_GS_NAND3X5 g23677__5107(.A (n_633), .B (n_637), .C (n_617), .Z
       (n_662));
  HS65_GS_NOR3X4 g23683__6260(.A (n_604), .B (n_644), .C (n_608), .Z
       (n_661));
  HS65_GSS_XNOR2X6 g23701__4319(.A (slv_reg_7_2), .B (n_658), .Z
       (n_660));
  HS65_GSS_XNOR2X6 g23698__8428(.A (slv_reg_6_2), .B (n_658), .Z
       (n_659));
  HS65_GSS_XOR2X6 g23696__5526(.A (n_764), .B (n_658), .Z (n_657));
  HS65_GSS_XOR2X6 g23704__6783(.A (slv_reg_2_2), .B (n_658), .Z
       (n_656));
  HS65_GS_AOI211X4 g23673__3680(.A (slv_reg_3_0), .B (n_667), .C
       (n_567), .D (n_614), .Z (n_655));
  HS65_GSS_XOR2X6 g23713__1617(.A (slv_reg_1_2), .B (n_658), .Z
       (n_654));
  HS65_GSS_XOR2X6 g23708__2802(.A (slv_reg_0_2), .B (n_658), .Z
       (n_653));
  HS65_GSS_XNOR2X6 g23705__1705(.A (slv_reg_4_2), .B (n_658), .Z
       (n_652));
  HS65_GSS_XOR2X6 g23716__5122(.A (slv_reg_3_2), .B (n_658), .Z
       (n_651));
  HS65_GSS_XOR2X6 g23717__8246(.A (slv_reg_5_2), .B (n_658), .Z
       (n_650));
  HS65_GS_AOI211X4 g23681__7098(.A (n_771), .B (n_638), .C (n_594), .D
       (n_606), .Z (n_649));
  HS65_GS_NAND3X5 g23682__6131(.A (n_570), .B (n_581), .C (n_599), .Z
       (n_648));
  HS65_GS_AOI21X2 g23688__1881(.A (slv_reg_2_4), .B (n_632), .C
       (n_586), .Z (n_647));
  HS65_GSS_XNOR2X6 g23740__5115(.A (slv_reg_0_7), .B (n_643), .Z
       (n_646));
  HS65_GSS_XNOR2X6 g23687__7482(.A (slv_reg_2_6), .B (n_628), .Z
       (n_645));
  HS65_GSS_XNOR2X6 g23741__4733(.A (slv_reg_7_7), .B (n_643), .Z
       (n_644));
  HS65_GSS_XNOR2X6 g23742__6161(.A (slv_reg_1_7), .B (n_643), .Z
       (n_642));
  HS65_GS_AOI21X6 g23686__9315(.A (slv_reg_5_3), .B (n_622), .C
       (n_602), .Z (n_641));
  HS65_GSS_XOR2X6 g23744__9945(.A (slv_reg_3_7), .B (n_643), .Z
       (n_640));
  HS65_GS_AOI21X2 g23689__2883(.A (slv_reg_4_5), .B (n_638), .C
       (n_588), .Z (n_639));
  HS65_GSS_XOR2X6 g23745__2346(.A (slv_reg_5_7), .B (n_643), .Z
       (n_637));
  HS65_GS_AOI12X2 g23690__1666(.A (slv_reg_1_5), .B (n_638), .C
       (n_590), .Z (n_636));
  HS65_GSS_XNOR2X6 g23747__7410(.A (slv_reg_2_7), .B (n_643), .Z
       (n_635));
  HS65_GS_AOI211X4 g23702__6417(.A (slv_reg_6_1), .B (n_574), .C
       (n_573), .D (n_583), .Z (n_634));
  HS65_GS_AOI21X6 g23692__5477(.A (slv_reg_5_4), .B (n_632), .C
       (n_593), .Z (n_633));
  HS65_GS_AOI211X4 g23693__2398(.A (slv_reg_0_4), .B (n_632), .C
       (n_184), .D (n_582), .Z (n_631));
  HS65_GSS_XNOR2X6 g23754__5107(.A (slv_reg_4_7), .B (n_643), .Z
       (n_630));
  HS65_GSS_XNOR2X6 g23700__6260(.A (slv_reg_6_6), .B (n_628), .Z
       (n_629));
  HS65_GS_AOI21X2 g23691__4319(.A (slv_reg_3_4), .B (n_632), .C
       (n_592), .Z (n_627));
  HS65_GSS_XNOR2X6 g23714__8428(.A (slv_reg_1_6), .B (n_628), .Z
       (n_626));
  HS65_GSS_XNOR2X6 g23719__5526(.A (n_759), .B (n_628), .Z (n_625));
  HS65_GSS_XNOR2X6 g23722__6783(.A (slv_reg_6_7), .B (n_643), .Z
       (n_624));
  HS65_GSS_XOR2X6 g23738__1617(.A (n_757), .B (n_643), .Z (n_621));
  HS65_GSS_XNOR2X6 g23699__2802(.A (slv_reg_7_6), .B (n_618), .Z
       (n_620));
  HS65_GSS_XNOR2X6 g23707__1705(.A (slv_reg_4_6), .B (n_618), .Z
       (n_619));
  HS65_GS_OA112X18 g23767__5122(.A (address_0), .B (n_510), .C (n_728),
       .D (n_565), .Z (n_658));
  HS65_GSS_XNOR2X6 g23718__8246(.A (slv_reg_5_6), .B (n_618), .Z
       (n_617));
  HS65_GSS_XNOR2X6 g23715__7098(.A (slv_reg_3_6), .B (n_618), .Z
       (n_616));
  HS65_GSS_XNOR2X6 g23710__6131(.A (slv_reg_0_6), .B (n_618), .Z
       (n_615));
  HS65_GS_OAI212X5 g23684__1881(.A (slv_reg_3_3), .B (n_622), .C
       (slv_reg_3_0), .D (n_667), .E (n_576), .Z (n_614));
  HS65_GSS_XOR2X6 g23751__5115(.A (slv_reg_1_4), .B (n_632), .Z
       (n_613));
  HS65_GSS_XNOR2X6 g23743__7482(.A (slv_reg_3_5), .B (n_638), .Z
       (n_612));
  HS65_GSS_XOR2X6 g23746__4733(.A (slv_reg_5_5), .B (n_638), .Z
       (n_611));
  HS65_GSS_XNOR2X6 g23748__6161(.A (slv_reg_6_4), .B (n_632), .Z
       (n_610));
  HS65_GSS_XNOR2X6 g23749__9315(.A (slv_reg_4_4), .B (n_632), .Z
       (n_609));
  HS65_GSS_XNOR2X6 g23750__9945(.A (slv_reg_7_4), .B (n_632), .Z
       (n_608));
  HS65_GSS_XNOR2X6 g23739__2883(.A (slv_reg_0_5), .B (n_638), .Z
       (n_607));
  HS65_GSS_XNOR2X6 g23752__2346(.A (n_762), .B (n_632), .Z (n_606));
  HS65_GSS_XNOR2X6 g23753__1666(.A (slv_reg_6_5), .B (n_638), .Z
       (n_605));
  HS65_GSS_XNOR2X6 g23755__7410(.A (slv_reg_7_5), .B (n_638), .Z
       (n_604));
  HS65_GS_OAI21X3 g23695__5477(.A (slv_reg_5_3), .B (n_622), .C
       (n_564), .Z (n_602));
  HS65_GSS_XNOR2X6 g23697__2398(.A (slv_reg_6_3), .B (n_622), .Z
       (n_601));
  HS65_GSS_XOR2X6 g23703__5107(.A (slv_reg_2_3), .B (n_622), .Z
       (n_600));
  HS65_GSS_XOR2X6 g23706__6260(.A (slv_reg_4_3), .B (n_622), .Z
       (n_599));
  HS65_GSS_XNOR2X6 g23709__4319(.A (slv_reg_0_3), .B (n_622), .Z
       (n_598));
  HS65_GSS_XNOR2X6 g23711__8428(.A (slv_reg_7_3), .B (n_622), .Z
       (n_597));
  HS65_GSS_XNOR2X6 g23712__5526(.A (slv_reg_1_3), .B (n_622), .Z
       (n_596));
  HS65_GSS_XNOR2X6 g23721__6783(.A (slv_reg_2_5), .B (n_638), .Z
       (n_595));
  HS65_GS_OAI112X5 g23723__3680(.A (n_771), .B (n_638), .C (n_726), .D
       (n_587), .Z (n_594));
  HS65_GS_OAI112X5 g23724__1617(.A (slv_reg_5_4), .B (n_632), .C
       (n_727), .D (n_589), .Z (n_593));
  HS65_GS_OAI112X5 g23725__2802(.A (slv_reg_3_4), .B (n_632), .C
       (n_727), .D (n_684), .Z (n_592));
  HS65_GS_OAI112X5 g23726__1705(.A (slv_reg_1_5), .B (n_638), .C
       (n_584), .D (n_589), .Z (n_590));
  HS65_GS_OAI112X5 g23727__5122(.A (slv_reg_4_5), .B (n_638), .C
       (n_727), .D (n_587), .Z (n_588));
  HS65_GS_OAI112X5 g23728__8246(.A (slv_reg_2_4), .B (n_632), .C
       (n_585), .D (n_584), .Z (n_586));
  HS65_GSS_XNOR2X6 g23759__7098(.A (slv_reg_6_0), .B (n_667), .Z
       (n_583));
  HS65_GS_NOR2X6 g23758__6131(.A (slv_reg_0_4), .B (n_632), .Z (n_582));
  HS65_GSS_XOR2X6 g23772__1881(.A (slv_reg_4_0), .B (n_667), .Z
       (n_581));
  HS65_GSS_XNOR2X6 g23769__5115(.A (slv_reg_7_0), .B (n_667), .Z
       (n_580));
  HS65_GS_CNIVX14 g23756(.A (n_618), .Z (n_628));
  HS65_GSS_XNOR2X6 g23777__7482(.A (slv_reg_1_0), .B (n_667), .Z
       (n_579));
  HS65_GSS_XNOR2X6 g23775__4733(.A (slv_reg_2_0), .B (n_667), .Z
       (n_578));
  HS65_GSS_XOR2X6 g23773__6161(.A (slv_reg_0_0), .B (n_667), .Z
       (n_577));
  HS65_GS_NAND2X7 g23720__9315(.A (slv_reg_3_3), .B (n_622), .Z
       (n_576));
  HS65_GS_OA112X18 g23865__9945(.A (address_0), .B (n_526), .C (n_473),
       .D (n_561), .Z (n_643));
  HS65_GSS_XNOR2X6 g23763__2883(.A (n_755), .B (n_574), .Z (n_575));
  HS65_GS_OAI112X5 g23764__2346(.A (slv_reg_6_1), .B (n_574), .C
       (n_585), .D (n_727), .Z (n_573));
  HS65_GSS_XNOR2X6 g23774__1666(.A (slv_reg_0_1), .B (n_574), .Z
       (n_572));
  HS65_GSS_XOR2X6 g23770__7410(.A (slv_reg_2_1), .B (n_574), .Z
       (n_571));
  HS65_GSS_XOR2X6 g23771__6417(.A (slv_reg_4_1), .B (n_574), .Z
       (n_570));
  HS65_GS_OAI112X5 g23768__5477(.A (n_508), .B (n_531), .C (n_534), .D
       (n_700), .Z (n_618));
  HS65_GSS_XNOR2X6 g23778__5107(.A (slv_reg_1_1), .B (n_574), .Z
       (n_568));
  HS65_GSS_XNOR2X6 g23779__6260(.A (slv_reg_3_1), .B (n_574), .Z
       (n_567));
  HS65_GSS_XOR2X6 g23780__4319(.A (slv_reg_5_1), .B (n_574), .Z
       (n_566));
  HS65_GS_NOR4ABX2 g23826__8428(.A (n_328), .B (n_364), .C (n_389), .D
       (n_535), .Z (n_565));
  HS65_GS_NAND2X7 g23830__5526(.A (slv_reg_5_0), .B (n_667), .Z
       (n_564));
  HS65_GSS_XNOR2X6 g23776__6783(.A (slv_reg_7_1), .B (n_574), .Z
       (n_563));
  HS65_GS_OA112X18 g23766__3680(.A (n_562), .B (n_500), .C (n_528), .D
       (n_519), .Z (n_622));
  HS65_GS_OA212X18 g23864__1617(.A (n_562), .B (n_449), .C (address_0),
       .D (n_532), .E (n_527), .Z (n_638));
  HS65_GS_AND3X18 g23866__2802(.A (n_515), .B (n_533), .C (n_529), .Z
       (n_632));
  HS65_GS_OA112X9 g23893__1705(.A (n_562), .B (n_470), .C (n_516), .D
       (n_410), .Z (n_561));
  HS65_GS_SDFPRQX9 slv_reg_reg_4_2(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_746), .TI (slv_reg_4_1), .TE (chip_scan_se), .Q
       (slv_reg_4_2));
  HS65_GS_SDFPRQX9 slv_reg_reg_6_5(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_747), .TI (slv_reg_6_4), .TE (chip_scan_se), .Q
       (slv_reg_6_5));
  HS65_GS_SDFPRQX9 slv_reg_reg_5_1(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_748), .TI (slv_reg_5_0), .TE (chip_scan_se), .Q
       (slv_reg_5_1));
  HS65_GS_SDFPRQX9 slv_reg_reg_6_7(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_749), .TI (slv_reg_6_6), .TE (chip_scan_se), .Q
       (slv_reg_6_7));
  HS65_GS_SDFPRQX9 slv_reg_reg_4_3(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_750), .TI (slv_reg_4_2), .TE (chip_scan_se), .Q
       (slv_reg_4_3));
  HS65_GS_SDFPRQX9 slv_reg_reg_4_1(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_751), .TI (slv_reg_4_0), .TE (chip_scan_se), .Q
       (slv_reg_4_1));
  HS65_GS_SDFPRQX9 slv_reg_reg_5_5(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_752), .TI (slv_reg_5_4), .TE (chip_scan_se), .Q
       (slv_reg_5_5));
  HS65_GS_SDFPRQX9 slv_reg_reg_9_0(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_753), .TI (n_756), .TE (chip_scan_se), .Q (slv_reg_9_0));
  HS65_GS_SDFPRQX9 slv_reg_reg_4_0(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_760), .TI (slv_reg_3_7), .TE (chip_scan_se), .Q
       (slv_reg_4_0));
  HS65_GS_SDFPRQX9 slv_reg_reg_4_6(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_765), .TI (slv_reg_4_5), .TE (chip_scan_se), .Q
       (slv_reg_4_6));
  HS65_GS_SDFPRQX9 slv_reg_reg_4_7(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_766), .TI (slv_reg_4_6), .TE (chip_scan_se), .Q
       (slv_reg_4_7));
  HS65_GS_SDFPRQX9 slv_reg_reg_4_5(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_767), .TI (slv_reg_4_4), .TE (chip_scan_se), .Q
       (slv_reg_4_5));
  HS65_GS_SDFPRQX9 slv_reg_reg_6_1(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_772), .TI (slv_reg_6_0), .TE (chip_scan_se), .Q
       (slv_reg_6_1));
  HS65_GS_SDFPRQX9 slv_reg_reg_5_0(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_773), .TI (slv_reg_4_7), .TE (chip_scan_se), .Q
       (slv_reg_5_0));
  HS65_GS_AO212X27 g23762__5122(.A (slv_reg_11_3), .B (n_546), .C
       (slv_reg_13_3), .D (n_543), .E (n_525), .Z (IP2Bus_Data[3]));
  HS65_GS_AO212X27 g23760__8246(.A (slv_reg_14_1), .B (n_545), .C
       (slv_reg_10_1), .D (n_524), .E (n_521), .Z (IP2Bus_Data[1]));
  HS65_GS_AO212X27 g23761__7098(.A (slv_reg_11_0), .B (n_546), .C
       (slv_reg_14_0), .D (n_545), .E (n_520), .Z (IP2Bus_Data[0]));
  HS65_GS_AO212X27 g23757__6131(.A (slv_reg_11_2), .B (n_546), .C
       (slv_reg_13_2), .D (n_543), .E (n_523), .Z (IP2Bus_Data[2]));
  HS65_GS_SDFPRQX9 slv_reg_reg_7_0(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_776), .TI (slv_reg_6_7), .TE (chip_scan_se), .Q
       (slv_reg_7_0));
  HS65_GS_SDFPRQX9 slv_reg_reg_7_5(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_777), .TI (slv_reg_7_4), .TE (chip_scan_se), .Q
       (slv_reg_7_5));
  HS65_GS_SDFPRQX9 slv_reg_reg_7_6(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_778), .TI (slv_reg_7_5), .TE (chip_scan_se), .Q
       (slv_reg_7_6));
  HS65_GS_SDFPRQX9 slv_reg_reg_7_7(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_779), .TI (slv_reg_7_6), .TE (chip_scan_se), .Q
       (slv_reg_7_7));
  HS65_GS_SDFPRQX9 slv_reg_reg_7_4(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_780), .TI (slv_reg_7_3), .TE (chip_scan_se), .Q
       (slv_reg_7_4));
  HS65_GS_SDFPRQX9 slv_reg_reg_5_2(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_781), .TI (slv_reg_5_1), .TE (chip_scan_se), .Q
       (slv_reg_5_2));
  HS65_GS_SDFPRQX9 slv_reg_reg_4_4(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_782), .TI (slv_reg_4_3), .TE (chip_scan_se), .Q
       (slv_reg_4_4));
  HS65_GS_SDFPRQX9 slv_reg_reg_7_1(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_783), .TI (slv_reg_7_0), .TE (chip_scan_se), .Q
       (slv_reg_7_1));
  HS65_GS_SDFPRQX9 slv_reg_reg_5_6(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_784), .TI (slv_reg_5_5), .TE (chip_scan_se), .Q
       (slv_reg_5_6));
  HS65_GS_SDFPRQX9 slv_reg_reg_5_7(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_785), .TI (slv_reg_5_6), .TE (chip_scan_se), .Q
       (slv_reg_5_7));
  HS65_GS_SDFPRQX9 slv_reg_reg_6_0(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_786), .TI (slv_reg_5_7), .TE (chip_scan_se), .Q
       (slv_reg_6_0));
  HS65_GS_SDFPRQX9 slv_reg_reg_6_2(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_787), .TI (slv_reg_6_1), .TE (chip_scan_se), .Q
       (slv_reg_6_2));
  HS65_GS_SDFPRQX9 slv_reg_reg_6_3(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_788), .TI (slv_reg_6_2), .TE (chip_scan_se), .Q
       (slv_reg_6_3));
  HS65_GS_SDFPRQX9 slv_reg_reg_6_4(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_789), .TI (slv_reg_6_3), .TE (chip_scan_se), .Q
       (slv_reg_6_4));
  HS65_GS_SDFPRQX9 slv_reg_reg_6_6(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_790), .TI (slv_reg_6_5), .TE (chip_scan_se), .Q
       (slv_reg_6_6));
  HS65_GS_SDFPRQX9 slv_reg_reg_7_2(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_791), .TI (slv_reg_7_1), .TE (chip_scan_se), .Q
       (slv_reg_7_2));
  HS65_GS_SDFPRQX9 slv_reg_reg_7_3(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_792), .TI (slv_reg_7_2), .TE (chip_scan_se), .Q
       (slv_reg_7_3));
  HS65_GS_SDFPRQX9 slv_reg_reg_5_4(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_793), .TI (slv_reg_5_3), .TE (chip_scan_se), .Q
       (slv_reg_5_4));
  HS65_GS_SDFPRQX9 slv_reg_reg_5_3(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_794), .TI (slv_reg_5_2), .TE (chip_scan_se), .Q
       (slv_reg_5_3));
  HS65_GS_AOI112X13 g23871__1881(.A (n_562), .B (n_517), .C (n_463), .D
       (n_459), .Z (n_667));
  HS65_GS_SDFPRQX9 slv_reg_reg_3_1(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_795), .TI (slv_reg_3_0), .TE (chip_scan_se), .Q
       (slv_reg_3_1));
  HS65_GS_SDFPRQX9 slv_reg_reg_2_1(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_796), .TI (slv_reg_2_0), .TE (chip_scan_se), .Q
       (slv_reg_2_1));
  HS65_GS_SDFPRQX9 slv_reg_reg_0_5(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_797), .TI (slv_reg_0_4), .TE (chip_scan_se), .Q
       (slv_reg_0_5));
  HS65_GS_SDFPRQX9 slv_reg_reg_1_3(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_798), .TI (slv_reg_1_2), .TE (chip_scan_se), .Q
       (slv_reg_1_3));
  HS65_GS_SDFPRQX9 slv_reg_reg_3_5(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_799), .TI (slv_reg_3_4), .TE (chip_scan_se), .Q
       (slv_reg_3_5));
  HS65_GS_SDFPRQX9 slv_reg_reg_1_0(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_800), .TI (slv_reg_0_7), .TE (chip_scan_se), .Q
       (slv_reg_1_0));
  HS65_GS_SDFPRQX9 slv_reg_reg_1_1(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_801), .TI (slv_reg_1_0), .TE (chip_scan_se), .Q
       (slv_reg_1_1));
  HS65_GS_SDFPRQX9 slv_reg_reg_0_1(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_802), .TI (slv_reg_0_0), .TE (chip_scan_se), .Q
       (slv_reg_0_1));
  HS65_GS_SDFPRQX9 slv_reg_reg_0_7(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_803), .TI (slv_reg_0_6), .TE (chip_scan_se), .Q
       (slv_reg_0_7));
  HS65_GS_SDFPRQX9 slv_reg_reg_2_2(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_804), .TI (slv_reg_2_1), .TE (chip_scan_se), .Q
       (slv_reg_2_2));
  HS65_GS_SDFPRQX9 slv_reg_reg_0_0(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_805), .TI (n_744), .TE (chip_scan_se), .Q (slv_reg_0_0));
  HS65_GS_SDFPRQX9 slv_reg_reg_0_2(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_806), .TI (slv_reg_0_1), .TE (chip_scan_se), .Q
       (slv_reg_0_2));
  HS65_GS_SDFPRQX9 slv_reg_reg_0_3(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_807), .TI (slv_reg_0_2), .TE (chip_scan_se), .Q
       (slv_reg_0_3));
  HS65_GS_SDFPRQX9 slv_reg_reg_0_6(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_808), .TI (slv_reg_0_5), .TE (chip_scan_se), .Q
       (slv_reg_0_6));
  HS65_GS_SDFPRQX9 slv_reg_reg_0_4(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_809), .TI (slv_reg_0_3), .TE (chip_scan_se), .Q
       (slv_reg_0_4));
  HS65_GS_SDFPRQX9 slv_reg_reg_1_5(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_810), .TI (slv_reg_1_4), .TE (chip_scan_se), .Q
       (slv_reg_1_5));
  HS65_GS_NOR4X9 g23878__7482(.A (n_511), .B (n_514), .C (n_413), .D
       (n_458), .Z (n_574));
  HS65_GS_OAI212X5 g23874__4733(.A (n_562), .B (n_486), .C (n_218), .D
       (n_412), .E (n_444), .Z (n_535));
  HS65_GS_NOR2X6 g23867__6161(.A (n_518), .B (n_513), .Z (n_534));
  HS65_GS_SDFPRQX9 slv_reg_reg_3_7(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_811), .TI (slv_reg_3_6), .TE (chip_scan_se), .Q
       (slv_reg_3_7));
  HS65_GS_SDFPRQX9 slv_reg_reg_2_3(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_812), .TI (slv_reg_2_2), .TE (chip_scan_se), .Q
       (slv_reg_2_3));
  HS65_GS_SDFPRQX9 slv_reg_reg_2_6(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_813), .TI (slv_reg_2_5), .TE (chip_scan_se), .Q
       (slv_reg_2_6));
  HS65_GS_SDFPRQX9 slv_reg_reg_2_7(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_814), .TI (slv_reg_2_6), .TE (chip_scan_se), .Q
       (slv_reg_2_7));
  HS65_GS_SDFPRQX9 slv_reg_reg_1_2(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_815), .TI (slv_reg_1_1), .TE (chip_scan_se), .Q
       (slv_reg_1_2));
  HS65_GS_SDFPRQX9 slv_reg_reg_3_2(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_816), .TI (slv_reg_3_1), .TE (chip_scan_se), .Q
       (slv_reg_3_2));
  HS65_GS_SDFPRQX9 slv_reg_reg_2_0(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_817), .TI (slv_reg_1_7), .TE (chip_scan_se), .Q
       (slv_reg_2_0));
  HS65_GS_SDFPRQX9 slv_reg_reg_1_7(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_818), .TI (slv_reg_1_6), .TE (chip_scan_se), .Q
       (slv_reg_1_7));
  HS65_GS_SDFPRQX9 slv_reg_reg_2_5(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_819), .TI (slv_reg_2_4), .TE (chip_scan_se), .Q
       (slv_reg_2_5));
  HS65_GS_SDFPRQX9 slv_reg_reg_3_6(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_820), .TI (slv_reg_3_5), .TE (chip_scan_se), .Q
       (slv_reg_3_6));
  HS65_GS_SDFPRQX9 slv_reg_reg_1_4(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_821), .TI (slv_reg_1_3), .TE (chip_scan_se), .Q
       (slv_reg_1_4));
  HS65_GS_SDFPRQX9 slv_reg_reg_1_6(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_822), .TI (slv_reg_1_5), .TE (chip_scan_se), .Q
       (slv_reg_1_6));
  HS65_GS_SDFPRQX9 slv_reg_reg_2_4(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_823), .TI (slv_reg_2_3), .TE (chip_scan_se), .Q
       (slv_reg_2_4));
  HS65_GS_SDFPRQX9 slv_reg_reg_3_3(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_824), .TI (slv_reg_3_2), .TE (chip_scan_se), .Q
       (slv_reg_3_3));
  HS65_GS_SDFPRQX9 slv_reg_reg_3_4(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_825), .TI (slv_reg_3_3), .TE (chip_scan_se), .Q
       (slv_reg_3_4));
  HS65_GS_SDFPRQX9 slv_reg_reg_3_0(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_826), .TI (slv_reg_2_7), .TE (chip_scan_se), .Q
       (slv_reg_3_0));
  HS65_GS_OA112X9 g23875__9315(.A (address_0), .B (n_469), .C (n_488),
       .D (n_365), .Z (n_533));
  HS65_GS_NOR2X6 g23880__9945(.A (n_393), .B (n_509), .Z (n_532));
  HS65_GS_AOI12X2 g23886__2883(.A (n_562), .B (n_476), .C (n_338), .Z
       (n_531));
  HS65_GS_AOI12X2 g23891__1666(.A (n_562), .B (n_471), .C (n_373), .Z
       (n_529));
  HS65_GS_NOR4ABX2 g23895__7410(.A (n_409), .B (n_350), .C (n_401), .D
       (n_472), .Z (n_528));
  HS65_GS_NOR2X6 g23897__6417(.A (n_498), .B (n_502), .Z (n_527));
  HS65_GS_NOR4ABX2 g23911__5477(.A (n_404), .B (n_408), .C (n_242), .D
       (n_485), .Z (n_526));
  HS65_GS_AO222X4 g23824__2398(.A (n_545), .B (slv_reg_14_3), .C
       (slv_reg_12_3), .D (n_522), .E (slv_reg_10_3), .F (n_524), .Z
       (n_525));
  HS65_GS_AO222X4 g23827__5107(.A (n_545), .B (slv_reg_14_2), .C
       (slv_reg_10_2), .D (n_524), .E (slv_reg_12_2), .F (n_522), .Z
       (n_523));
  HS65_GS_AO222X4 g23828__6260(.A (n_543), .B (slv_reg_13_1), .C
       (slv_reg_11_1), .D (n_546), .E (slv_reg_12_1), .F (n_522), .Z
       (n_521));
  HS65_GS_AO222X4 g23829__4319(.A (n_543), .B (slv_reg_13_0), .C
       (slv_reg_10_0), .D (n_524), .E (slv_reg_12_0), .F (n_522), .Z
       (n_520));
  HS65_GS_OA112X9 g23876__8428(.A (address_0), .B (n_462), .C (n_390),
       .D (n_464), .Z (n_519));
  HS65_GS_OAI32X5 g23890__5526(.A (n_562), .B (n_447), .C (n_221), .D
       (n_487), .E (n_457), .Z (n_518));
  HS65_GS_NAND2X7 g23912__6783(.A (n_450), .B (n_489), .Z (n_517));
  HS65_GS_AO31X9 g23950__3680(.A (n_501), .B (n_445), .C (n_432), .D
       (n_512), .Z (n_516));
  HS65_GS_AOI12X2 g23901__1617(.A (address_0), .B (n_435), .C (n_456),
       .Z (n_515));
  HS65_GS_AOI13X5 g23879__2802(.A (n_419), .B (n_308), .C (n_344), .D
       (address_0), .Z (n_514));
  HS65_GS_OAI222X2 g23888__1705(.A (n_366), .B (n_507), .C (n_512), .D
       (n_424), .E (n_562), .F (n_293), .Z (n_513));
  HS65_GS_CBI4I1X5 g23898__5122(.A (n_467), .B (n_381), .C (n_512), .D
       (n_160), .Z (n_511));
  HS65_GS_NOR4ABX2 g23910__8246(.A (n_273), .B (n_420), .C (n_257), .D
       (n_379), .Z (n_510));
  HS65_GS_OAI212X5 g23909__7098(.A (address_1), .B (n_375), .C (n_508),
       .D (n_507), .E (n_371), .Z (n_509));
  HS65_GS_NOR3AX4 g23877__6131(.A (Bus2IP_WrCE[8]), .B
       (Bus2IP_WrCE[9]), .C (n_503), .Z (n_554));
  HS65_GS_NOR3AX2 g23868__1881(.A (Bus2IP_WrCE[9]), .B
       (Bus2IP_WrCE[8]), .C (n_503), .Z (n_506));
  HS65_GS_CBI4I1X5 g23946__5115(.A (n_395), .B (n_501), .C (address_1),
       .D (n_465), .Z (n_502));
  HS65_GS_NOR3X4 g23944__7482(.A (n_296), .B (n_436), .C (n_499), .Z
       (n_500));
  HS65_GS_OAI212X5 g23942__4733(.A (n_512), .B (n_403), .C (n_411), .D
       (n_251), .E (n_278), .Z (n_498));
  HS65_GS_NAND4ABX3 g23914__6161(.A (n_497), .B (Bus2IP_WrCE[7]), .C
       (Bus2IP_WrCE[6]), .D (n_491), .Z (n_560));
  HS65_GS_NAND4ABX3 g23921__9315(.A (n_497), .B (Bus2IP_WrCE[4]), .C
       (Bus2IP_WrCE[5]), .D (n_494), .Z (n_556));
  HS65_GS_NAND4ABX3 g23920__9945(.A (n_497), .B (Bus2IP_WrCE[5]), .C
       (Bus2IP_WrCE[4]), .D (n_494), .Z (n_559));
  HS65_GS_NAND4ABX3 g23915__2883(.A (n_497), .B (Bus2IP_WrCE[6]), .C
       (Bus2IP_WrCE[7]), .D (n_491), .Z (n_542));
  HS65_GS_OA112X9 g23925__2346(.A (n_431), .B (n_243), .C (n_394), .D
       (n_340), .Z (n_489));
  HS65_GS_AO31X9 g23926__1666(.A (n_192), .B (n_501), .C (n_326), .D
       (n_487), .Z (n_488));
  HS65_GS_NOR4ABX4 g23900__7410(.A (n_134), .B (n_356), .C (n_475), .D
       (n_369), .Z (n_486));
  HS65_GS_NAND2X7 g23923__6417(.A (n_376), .B (n_426), .Z (n_485));
  HS65_GS_SDFPRQX9 slv_reg_reg_10_4(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_827), .TI (slv_reg_10_3), .TE (chip_scan_se), .Q
       (slv_reg_10_4));
  HS65_GS_SDFPRQX9 slv_reg_reg_10_3(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_828), .TI (slv_reg_10_2), .TE (chip_scan_se), .Q
       (slv_reg_10_3));
  HS65_GS_NAND4ABX3 g23917__5477(.A (n_483), .B (Bus2IP_WrCE[2]), .C
       (Bus2IP_WrCE[0]), .D (n_480), .Z (n_537));
  HS65_GS_NAND4ABX3 g23918__2398(.A (n_483), .B (Bus2IP_WrCE[0]), .C
       (Bus2IP_WrCE[2]), .D (n_480), .Z (n_536));
  HS65_GS_NAND4ABX3 g23919__5107(.A (n_483), .B (Bus2IP_WrCE[1]), .C
       (Bus2IP_WrCE[3]), .D (n_477), .Z (n_539));
  HS65_GS_NAND4ABX3 g23916__6260(.A (n_483), .B (Bus2IP_WrCE[3]), .C
       (Bus2IP_WrCE[1]), .D (n_477), .Z (n_538));
  HS65_GS_NAND4ABX3 g23955__4319(.A (n_208), .B (n_475), .C (n_398), .D
       (n_244), .Z (n_476));
  HS65_GS_OAI211X5 g23947__8428(.A (n_277), .B (n_368), .C (n_275), .D
       (n_388), .Z (n_474));
  HS65_GS_AOI211X4 g23948__5526(.A (n_466), .B (n_222), .C (n_313), .D
       (n_367), .Z (n_473));
  HS65_GS_OAI21X3 g23949__6783(.A (address_0), .B (n_405), .C (n_314),
       .Z (n_472));
  HS65_GS_OAI211X5 g23954__3680(.A (n_161), .B (n_259), .C (n_461), .D
       (n_397), .Z (n_471));
  HS65_GS_OA112X9 g23945__1617(.A (n_508), .B (n_324), .C (n_378), .D
       (n_309), .Z (n_470));
  HS65_GS_OA112X9 g23957__2802(.A (n_508), .B (n_399), .C (n_274), .D
       (n_318), .Z (n_469));
  HS65_GS_MUX21I1X6 g23988__1705(.D0 (n_400), .D1 (n_467), .S0 (n_466),
       .Z (n_468));
  HS65_GS_OA112X9 g23961__5122(.A (n_416), .B (n_320), .C (n_290), .D
       (n_354), .Z (n_465));
  HS65_GS_OAI13X5 g23899__8246(.A (n_341), .B (n_425), .C (n_406), .D
       (n_562), .Z (n_464));
  HS65_GS_OAI22X6 g23958__7098(.A (n_562), .B (n_337), .C (n_512), .D
       (n_434), .Z (n_463));
  HS65_GS_OA112X9 g23956__6131(.A (address_1), .B (n_319), .C (n_288),
       .D (n_461), .Z (n_462));
  HS65_GS_MX41X7 g23825__1881(.D0 (n_107), .D1 (n_170), .D2 (n_332),
       .D3 (chip_sdo_1), .S0 (n_331), .S1 (n_440), .S2 (n_437), .S3
       (n_329), .Z (n_460));
  HS65_GS_NAND4ABX3 g23951__5115(.A (n_336), .B (n_458), .C (n_281), .D
       (n_334), .Z (n_459));
  HS65_GS_OA112X9 g23924__7482(.A (n_466), .B (n_448), .C (n_443), .D
       (n_304), .Z (n_457));
  HS65_GS_AOI13X5 g23943__4733(.A (n_217), .B (n_507), .C (n_279), .D
       (n_512), .Z (n_456));
  HS65_GS_SDFPRQX9 slv_reg_reg_13_1(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_829), .TI (slv_reg_13_0), .TE (chip_scan_se), .Q
       (slv_reg_13_1));
  HS65_GS_SDFPRQX9 slv_reg_reg_13_2(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_830), .TI (slv_reg_13_1), .TE (chip_scan_se), .Q
       (slv_reg_13_2));
  HS65_GS_NOR3AX2 g23903__6161(.A (Bus2IP_RdCE[13]), .B
       (Bus2IP_RdCE[14]), .C (n_452), .Z (n_543));
  HS65_GS_NOR3AX2 g23904__9315(.A (Bus2IP_RdCE[14]), .B
       (Bus2IP_RdCE[13]), .C (n_452), .Z (n_545));
  HS65_GS_SDFPRQX9 endy_reg_1(.RN (n_696), .CP (n_490), .D (n_831), .TI
       (endy_0), .TE (chip_scan_se), .Q (endy_1));
  HS65_GS_NOR2X6 g23978__9945(.A (n_347), .B (n_363), .Z (n_450));
  HS65_GS_CB4I1X9 g23979__2883(.A (n_448), .B (n_345), .C (n_447), .D
       (n_360), .Z (n_449));
  HS65_GS_OA212X4 g23987__2346(.A (n_342), .B (n_445), .C (n_433), .D
       (n_391), .E (n_349), .Z (n_446));
  HS65_GS_AO12X9 g23969__1666(.A (n_327), .B (n_443), .C (n_512), .Z
       (n_444));
  HS65_GS_MX41X7 g23873__7410(.D0 (n_429), .D1 (n_833), .D2 (n_144),
       .D3 (n_28), .S0 (n_441), .S1 (n_428), .S2 (n_427), .S3 (n_440),
       .Z (n_442));
  HS65_GS_AND2X27 g23881__6417(.A (slv_reg_10_4), .B (n_524), .Z
       (IP2Bus_Data[4]));
  HS65_GS_SDFPRQX9 slv_reg_reg_14_1(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_834), .TI (slv_reg_14_0), .TE (chip_scan_se), .Q
       (slv_reg_14_1));
  HS65_GS_SDFPRQX9 slv_reg_reg_14_2(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_835), .TI (slv_reg_14_1), .TE (chip_scan_se), .Q
       (slv_reg_14_2));
  HS65_GS_SDFPRQX9 slv_reg_reg_14_3(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_836), .TI (slv_reg_14_2), .TE (chip_scan_se), .Q
       (slv_reg_14_3));
  HS65_GS_SDFPRQX9 slv_reg_reg_13_0(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_837), .TI (slv_reg_12_3), .TE (chip_scan_se), .Q
       (slv_reg_13_0));
  HS65_GS_SDFPRQX9 slv_reg_reg_14_0(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_838), .TI (slv_reg_13_3), .TE (chip_scan_se), .Q
       (slv_reg_14_0));
  HS65_GS_SDFPRQX9 slv_reg_reg_13_3(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_839), .TI (slv_reg_13_2), .TE (chip_scan_se), .Q
       (slv_reg_13_3));
  HS65_GS_SDFPRQX9 endy_reg_2(.RN (n_696), .CP (n_490), .D (n_840), .TI
       (endy_1), .TE (chip_scan_se), .Q (endy_2));
  HS65_GS_SDFPRQX9 endy_reg_0(.RN (n_696), .CP (n_490), .D (n_841), .TI
       (n_832), .TE (chip_scan_se), .Q (endy_0));
  HS65_GS_SDFPRQX9 endy_reg_3(.RN (n_696), .CP (n_490), .D (n_842), .TI
       (endy_2), .TE (chip_scan_se), .Q (chip_sdo_1));
  HS65_GS_AOI12X2 g24023__5477(.A (address_1), .B (n_392), .C (n_323),
       .Z (n_436));
  HS65_GS_OAI222X2 g24033__2398(.A (n_396), .B (n_418), .C (n_466), .D
       (n_434), .E (n_433), .F (n_417), .Z (n_435));
  HS65_GS_AOI211X4 g24040__5107(.A (n_431), .B (n_123), .C (n_147), .D
       (n_264), .Z (n_432));
  HS65_GS_MX41X7 g23896__6260(.D0 (n_429), .D1 (n_855), .D2 (n_66), .D3
       (n_466), .S0 (n_299), .S1 (n_428), .S2 (n_427), .S3 (n_440), .Z
       (n_430));
  HS65_GS_AOI211X4 g23965__4319(.A (address_2), .B (n_191), .C (n_261),
       .D (n_425), .Z (n_426));
  HS65_GS_AOI21X6 g23953__8428(.A (address_2), .B (n_200), .C (n_311),
       .Z (n_424));
  HS65_GS_OAI12X3 g23952__5526(.A (n_59), .B (n_199), .C (n_422), .Z
       (n_423));
  HS65_GS_NAND3AX6 g23902__6783(.A (n_421), .B (n_491), .C (n_494), .Z
       (n_503));
  HS65_GS_NAND2AX7 g23935__3680(.A (n_421), .B (n_62), .Z (n_497));
  HS65_GS_OA112X9 g23991__1617(.A (address_1), .B (n_247), .C (n_167),
       .D (n_294), .Z (n_420));
  HS65_GS_CB4I1X9 g23980__2802(.A (n_418), .B (n_417), .C (n_416), .D
       (n_315), .Z (n_419));
  HS65_GS_CB4I6X9 g23983__1705(.A (n_428), .B (n_427), .C (endx_0), .D
       (n_298), .Z (n_415));
  HS65_GS_MX41X7 g23986__5122(.D0 (n_69), .D1 (n_846), .D2 (n_382), .D3
       (n_508), .S0 (n_429), .S1 (n_428), .S2 (n_427), .S3 (n_440), .Z
       (n_414));
  HS65_GS_OAI222X2 g23989__8246(.A (n_325), .B (n_412), .C (n_562), .D
       (n_283), .E (n_411), .F (n_402), .Z (n_413));
  HS65_GS_CB4I1X9 g23971__7098(.A (n_387), .B (n_501), .C (n_372), .D
       (n_409), .Z (n_410));
  HS65_GS_AOI212X4 g24018__6131(.A (n_343), .B (n_254), .C (n_271), .D
       (n_380), .E (n_286), .Z (n_408));
  HS65_GS_AOI12X6 g24013__5115(.A (n_434), .B (n_467), .C (n_466), .Z
       (n_499));
  HS65_GS_OA112X9 g24022__7482(.A (n_377), .B (n_362), .C (n_180), .D
       (n_404), .Z (n_405));
  HS65_GS_AND3X9 g24025__4733(.A (n_402), .B (n_206), .C (n_153), .Z
       (n_403));
  HS65_GS_OAI211X5 g24030__6161(.A (n_487), .B (n_501), .C (n_335), .D
       (n_370), .Z (n_401));
  HS65_GS_NAND2X7 g24043__9315(.A (n_374), .B (n_434), .Z (n_400));
  HS65_GS_NOR3X4 g24001__9945(.A (n_135), .B (n_201), .C (n_210), .Z
       (n_399));
  HS65_GS_AOI31X5 g24080__2883(.A (n_53), .B (address_2), .C (n_96), .D
       (n_269), .Z (n_398));
  HS65_GS_OA112X9 g23967__2346(.A (n_355), .B (n_396), .C (n_395), .D
       (n_305), .Z (n_397));
  HS65_GS_OA212X4 g24021__1666(.A (n_310), .B (n_295), .C (address_1),
       .D (n_417), .E (n_404), .Z (n_394));
  HS65_GS_CBI4I1X5 g23964__7410(.A (n_392), .B (n_391), .C (address_2),
       .D (n_253), .Z (n_393));
  HS65_GS_CBI4I6X5 g23962__6417(.A (n_159), .B (n_389), .C (n_177), .D
       (n_211), .Z (n_390));
  HS65_GS_OA112X9 g23966__5477(.A (n_361), .B (n_387), .C (n_395), .D
       (n_228), .Z (n_388));
  HS65_GS_SDFPRQX9 slv_reg_reg_12_3(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_843), .TI (slv_reg_12_2), .TE (chip_scan_se), .Q
       (slv_reg_12_3));
  HS65_GS_SDFPRQX9 slv_reg_reg_11_1(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_844), .TI (slv_reg_11_0), .TE (chip_scan_se), .Q
       (slv_reg_11_1));
  HS65_GS_NOR4ABX2 g23913__2398(.A (Bus2IP_RdCE[12]), .B (n_300), .C
       (Bus2IP_RdCE[13]), .D (Bus2IP_RdCE[14]), .Z (n_522));
  HS65_GS_NOR3AX2 g23905__5107(.A (Bus2IP_RdCE[11]), .B
       (Bus2IP_RdCE[10]), .C (n_383), .Z (n_546));
  HS65_GS_NAND4ABX3 g23933__6260(.A (n_63), .B (n_303), .C (n_491), .D
       (n_494), .Z (n_483));
  HS65_GS_NOR3AX2 g23907__4319(.A (Bus2IP_RdCE[10]), .B
       (Bus2IP_RdCE[11]), .C (n_383), .Z (n_524));
  HS65_GS_AOI112X4 g24002__8428(.A (n_380), .B (n_215), .C (n_127), .D
       (n_475), .Z (n_381));
  HS65_GS_OAI211X5 g23970__5526(.A (n_466), .B (n_263), .C (n_235), .D
       (n_467), .Z (n_379));
  HS65_GS_CB4I1X9 g23998__6783(.A (n_238), .B (n_150), .C (n_377), .D
       (n_267), .Z (n_378));
  HS65_GS_AOI211X4 g23972__3680(.A (n_508), .B (n_359), .C (n_246), .D
       (n_353), .Z (n_376));
  HS65_GS_OA112X9 g23977__1617(.A (n_285), .B (n_256), .C (n_374), .D
       (n_220), .Z (n_375));
  HS65_GS_CBI4I1X5 g23981__2802(.A (n_374), .B (n_445), .C (n_372), .D
       (n_169), .Z (n_373));
  HS65_GS_OA212X4 g24017__1705(.A (n_346), .B (n_348), .C (n_291), .D
       (n_351), .E (n_370), .Z (n_371));
  HS65_GS_AOI22X6 g23984__5122(.A (n_255), .B (n_239), .C (n_508), .D
       (n_368), .Z (n_369));
  HS65_GS_OAI211X5 g23985__8246(.A (n_366), .B (n_467), .C (n_214), .D
       (n_240), .Z (n_367));
  HS65_GS_CB4I1X9 g23968__7098(.A (n_374), .B (n_368), .C (n_366), .D
       (n_297), .Z (n_365));
  HS65_GS_AO31X9 g24007__6131(.A (n_448), .B (n_307), .C (n_467), .D
       (address_1), .Z (n_364));
  HS65_GS_CBI4I1X5 g24006__1881(.A (n_362), .B (n_204), .C (n_361), .D
       (n_266), .Z (n_363));
  HS65_GS_CBI4I6X5 g24004__5115(.A (n_213), .B (n_359), .C (n_282), .D
       (n_292), .Z (n_360));
  HS65_GS_SDFPRQX9 slv_reg_reg_12_0(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_847), .TI (slv_reg_11_3), .TE (chip_scan_se), .Q
       (slv_reg_12_0));
  HS65_GS_SDFPRQX9 slv_reg_reg_12_1(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_848), .TI (slv_reg_12_0), .TE (chip_scan_se), .Q
       (slv_reg_12_1));
  HS65_GS_SDFPRQX9 slv_reg_reg_12_2(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_849), .TI (slv_reg_12_1), .TE (chip_scan_se), .Q
       (slv_reg_12_2));
  HS65_GS_SDFPRQX9 slv_reg_reg_11_3(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_850), .TI (slv_reg_11_2), .TE (chip_scan_se), .Q
       (slv_reg_11_3));
  HS65_GS_SDFPRQX9 slv_reg_reg_11_2(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_851), .TI (slv_reg_11_1), .TE (chip_scan_se), .Q
       (slv_reg_11_2));
  HS65_GS_SDFPRQX9 slv_reg_reg_11_0(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_852), .TI (slv_reg_10_4), .TE (chip_scan_se), .Q
       (slv_reg_11_0));
  HS65_GS_HA1X4 g23894__7482(.A0 (slv_reg_11_3), .B0 (n_145), .CO
       (n_357), .S0 (n_358));
  HS65_GS_OA112X9 g24019__4733(.A (n_431), .B (n_355), .C (n_241), .D
       (n_178), .Z (n_356));
  HS65_GS_NOR2X6 g24020__6161(.A (n_224), .B (n_353), .Z (n_354));
  HS65_GS_OA222X4 g24024__9315(.A (n_396), .B (n_249), .C (n_339), .D
       (n_368), .E (n_351), .F (n_176), .Z (n_352));
  HS65_GS_AO12X9 g24026__9945(.A (n_443), .B (n_391), .C (n_366), .Z
       (n_350));
  HS65_GS_OA212X4 g24027__2883(.A (n_433), .B (n_348), .C (n_260), .D
       (n_387), .E (n_128), .Z (n_349));
  HS65_GS_OAI22X6 g24028__2346(.A (n_508), .B (n_182), .C (n_346), .D
       (n_345), .Z (n_347));
  HS65_GS_OA22X9 g24029__1666(.A (n_343), .B (n_395), .C (n_342), .D
       (n_507), .Z (n_344));
  HS65_GS_OAI211X5 g24031__7410(.A (n_416), .B (n_203), .C (n_284), .D
       (n_108), .Z (n_341));
  HS65_GS_OA222X4 g24032__6417(.A (n_466), .B (n_395), .C (n_396), .D
       (n_345), .E (n_339), .F (n_392), .Z (n_340));
  HS65_GS_CBI4I1X5 g24035__5477(.A (n_289), .B (n_368), .C (n_447), .D
       (n_237), .Z (n_338));
  HS65_GS_NOR2X6 g23999__2398(.A (n_389), .B (n_230), .Z (n_337));
  HS65_GS_NAND2X7 g24042__5107(.A (n_163), .B (n_335), .Z (n_336));
  HS65_GS_OR2X9 g24044__6260(.A (n_372), .B (n_501), .Z (n_334));
  HS65_GS_MX41X7 g23889__4319(.D0 (n_72), .D1 (address_6), .D2 (n_332),
       .D3 (endy_2), .S0 (n_331), .S1 (n_440), .S2 (n_330), .S3
       (n_329), .Z (n_333));
  HS65_GS_OA112X9 g24055__8428(.A (n_229), .B (n_306), .C (n_287), .D
       (n_173), .Z (n_328));
  HS65_GS_OA112X9 g24057__5526(.A (n_65), .B (n_447), .C (n_171), .D
       (n_151), .Z (n_327));
  HS65_GS_OAI22X6 g24037__6783(.A (n_355), .B (n_412), .C (n_372), .D
       (n_445), .Z (n_458));
  HS65_GS_OA212X4 g24060__3680(.A (address_2), .B (n_268), .C (n_39),
       .D (n_325), .E (n_324), .Z (n_326));
  HS65_GS_OA112X9 g24084__1617(.A (n_321), .B (n_418), .C (n_148), .D
       (n_252), .Z (n_323));
  HS65_GS_OAI32X5 g24089__2802(.A (n_508), .B (n_321), .C (n_320), .D
       (n_447), .E (n_345), .Z (n_322));
  HS65_GS_OA12X9 g24011__1705(.A (address_2), .B (n_387), .C (n_318),
       .Z (n_319));
  HS65_GS_MX41X7 g23963__5122(.D0 (n_21), .D1 (n_245), .D2 (n_332), .D3
       (endy_1), .S0 (n_331), .S1 (n_440), .S2 (n_316), .S3 (n_329), .Z
       (n_317));
  HS65_GS_CBI4I6X5 g24010__8246(.A (n_149), .B (n_179), .C (n_270), .D
       (n_136), .Z (n_315));
  HS65_GS_IVX9 g24068(.A (n_313), .Z (n_314));
  HS65_GS_CB4I6X9 g23982__7098(.A (n_329), .B (n_331), .C (endy_0), .D
       (n_234), .Z (n_312));
  HS65_GS_OAI212X5 g23990__6131(.A (n_310), .B (n_345), .C (n_209), .D
       (n_133), .E (n_194), .Z (n_311));
  HS65_GS_NOR2X6 g24003__1881(.A (n_265), .B (n_248), .Z (n_309));
  HS65_GS_CB4I1X9 g24005__5115(.A (n_362), .B (n_307), .C (n_306), .D
       (n_305), .Z (n_308));
  HS65_GS_OA112X9 g24009__7482(.A (n_377), .B (n_118), .C (n_187), .D
       (n_166), .Z (n_304));
  HS65_GS_NAND3AX6 g23975__4733(.A (n_303), .B (n_480), .C (n_477), .Z
       (n_421));
  HS65_GS_AOI112X4 g23992__6161(.A (n_451), .B (n_190), .C (n_119), .D
       (n_302), .Z (n_422));
  HS65_GS_NAND2AX4 g23973__9315(.A (Bus2IP_RdCE[12]), .B (n_300), .Z
       (n_452));
  HS65_GS_SDFPRQX9 slv_reg_reg_10_2(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_853), .TI (slv_reg_10_1), .TE (chip_scan_se), .Q
       (slv_reg_10_2));
  HS65_GS_AO22X9 g24034__9945(.A (n_20), .B (n_429), .C (n_562), .D
       (n_440), .Z (n_298));
  HS65_GS_OA222X4 g24036__2883(.A (n_377), .B (n_348), .C (n_205), .D
       (n_416), .E (n_346), .F (n_402), .Z (n_297));
  HS65_GS_AOI12X2 g24041__2346(.A (n_295), .B (n_402), .C (n_346), .Z
       (n_296));
  HS65_GS_OA112X9 g24047__1666(.A (n_28), .B (n_325), .C (n_293), .D
       (n_137), .Z (n_294));
  HS65_GS_CBI4I1X5 g24049__7410(.A (n_291), .B (n_276), .C (n_377), .D
       (n_156), .Z (n_292));
  HS65_GS_CB4I1X9 g24053__6417(.A (n_280), .B (n_289), .C (n_351), .D
       (n_158), .Z (n_290));
  HS65_GS_OA112X9 g24058__5477(.A (n_342), .B (n_164), .C (n_287), .D
       (n_131), .Z (n_288));
  HS65_GS_OAI12X3 g24059__2398(.A (n_285), .B (n_416), .C (n_284), .Z
       (n_286));
  HS65_GS_AOI22X6 g24092__5107(.A (n_212), .B (n_197), .C (n_282), .D
       (n_138), .Z (n_283));
  HS65_GS_OA32X4 g24069__6260(.A (n_562), .B (n_310), .C (n_402), .D
       (n_280), .E (n_412), .Z (n_281));
  HS65_GS_AO12X9 g24073__4319(.A (n_307), .B (n_392), .C (n_310), .Z
       (n_279));
  HS65_GS_OA33X9 g24081__8428(.A (n_39), .B (n_487), .C (n_368), .D
       (n_562), .E (n_277), .F (n_276), .Z (n_278));
  HS65_GS_OAI21X3 g24064__5526(.A (n_431), .B (n_418), .C (n_275), .Z
       (n_425));
  HS65_GS_CB4I1X9 g24008__6783(.A (n_157), .B (n_276), .C (n_310), .D
       (n_189), .Z (n_274));
  HS65_GS_AOI32X5 g24148__3680(.A (address_6), .B (n_86), .C (n_271),
       .D (n_130), .E (n_270), .Z (n_273));
  HS65_GS_OAI21X3 g24138__1617(.A (n_377), .B (n_268), .C (n_267), .Z
       (n_269));
  HS65_GS_IVX9 g24098(.A (n_265), .Z (n_266));
  HS65_GS_OAI22X6 g24134__2802(.A (n_310), .B (n_268), .C (address_2),
       .D (n_263), .Z (n_264));
  HS65_GS_AO112X9 g24093__1705(.A (n_355), .B (n_320), .C (n_562), .D
       (n_431), .Z (n_409));
  HS65_GS_OAI32X5 g24096__5122(.A (n_250), .B (n_277), .C (n_236), .D
       (n_226), .E (n_368), .Z (n_313));
  HS65_GSS_XOR2X6 g23959__8246(.A (chip_sdo_1), .B (n_142), .Z (n_437));
  HS65_GSS_XOR2X6 g23960__7098(.A (n_833), .B (n_141), .Z (n_441));
  HS65_GS_IVX9 g24100(.A (n_475), .Z (n_434));
  HS65_GS_NAND2X7 g23976__6131(.A (n_302), .B (n_143), .Z (n_438));
  HS65_GS_NAND4ABX3 g23922__1881(.A (slv_reg_10_3), .B (slv_reg_10_4),
       .C (n_232), .D (n_140), .Z (n_455));
  HS65_GS_AO32X4 g24045__5115(.A (n_696), .B (EA_3), .C (n_585), .D
       (n_120), .E (user_int), .Z (n_262));
  HS65_GS_OAI211X5 g24046__7482(.A (n_260), .B (n_362), .C (n_225), .D
       (n_231), .Z (n_261));
  HS65_GS_CBI4I6X5 g24048__4733(.A (n_216), .B (n_152), .C (n_129), .D
       (n_53), .Z (n_259));
  HS65_GS_CBI4I6X5 g24051__6161(.A (n_155), .B (n_256), .C (n_418), .D
       (n_508), .Z (n_257));
  HS65_GS_OAI13X5 g24052__9315(.A (n_83), .B (n_186), .C (n_254), .D
       (n_39), .Z (n_255));
  HS65_GS_CB4I1X9 g24054__9945(.A (n_227), .B (n_276), .C (n_361), .D
       (n_252), .Z (n_253));
  HS65_GS_OA112X9 g24056__2883(.A (n_285), .B (n_250), .C (n_249), .D
       (n_345), .Z (n_251));
  HS65_GS_OAI32X5 g24085__2346(.A (address_4), .B (n_285), .C (n_277),
       .D (n_366), .E (n_247), .Z (n_248));
  HS65_GS_OAI311X5 g24083__1666(.A (n_245), .B (n_207), .C (n_447), .D
       (n_106), .E (n_287), .Z (n_246));
  HS65_GS_AO12X9 g24070__7410(.A (n_249), .B (n_247), .C (address_2),
       .Z (n_244));
  HS65_GS_OA12X9 g24072__6417(.A (address_1), .B (n_418), .C (n_392),
       .Z (n_243));
  HS65_GS_AOI21X2 g24074__5477(.A (n_417), .B (n_241), .C (n_508), .Z
       (n_242));
  HS65_GS_AO12X9 g24075__2398(.A (n_223), .B (n_348), .C (n_396), .Z
       (n_240));
  HS65_GS_OA22X9 g24076__5107(.A (n_466), .B (n_122), .C (n_310), .D
       (n_238), .Z (n_239));
  HS65_GS_OA12X9 g24077__6260(.A (n_256), .B (n_236), .C (n_374), .Z
       (n_237));
  HS65_GS_AO12X9 g24078__4319(.A (n_362), .B (n_402), .C (n_377), .Z
       (n_235));
  HS65_GS_AO22X9 g24082__8428(.A (n_53), .B (n_440), .C (n_233), .D
       (n_332), .Z (n_234));
  HS65_GS_NAND4ABX3 g24063__5526(.A (reseta_bit_slv_reg0), .B (n_232),
       .C (n_49), .D (n_60), .Z (n_303));
  HS65_GS_CB4I6X9 g24061__6783(.A (n_28), .B (n_238), .C (n_241), .D
       (n_53), .Z (n_305));
  HS65_GS_OA12X9 g24062__3680(.A (address_1), .B (n_448), .C (n_231),
       .Z (n_461));
  HS65_GS_SDFPRQX9 slv_reg_reg_10_0(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_861), .TI (slv_reg_9_0), .TE (chip_scan_se), .Q
       (slv_reg_10_0));
  HS65_GS_SDFPRQX9 slv_reg_reg_10_1(.RN (n_696), .CP (Bus2IP_Clk), .D
       (n_857), .TI (slv_reg_10_0), .TE (chip_scan_se), .Q
       (slv_reg_10_1));
  HS65_GS_OAI32X5 g24086__1617(.A (n_250), .B (n_229), .C (n_342), .D
       (n_433), .E (n_247), .Z (n_230));
  HS65_GS_OA212X4 g24088__2802(.A (n_310), .B (n_121), .C (n_227), .D
       (n_226), .E (n_225), .Z (n_228));
  HS65_GS_OAI22X6 g24090__1705(.A (n_219), .B (n_346), .C (n_433), .D
       (n_223), .Z (n_224));
  HS65_GS_CNIVX7 g24099(.A (n_391), .Z (n_222));
  HS65_GS_AND2X4 g24109__5122(.A (n_417), .B (n_320), .Z (n_221));
  HS65_GS_OA222X4 g24087__8246(.A (n_39), .B (n_219), .C (n_447), .D
       (n_218), .E (n_250), .F (n_154), .Z (n_220));
  HS65_GS_OAI21X3 g24195__7098(.A (n_23), .B (n_216), .C (n_215), .Z
       (n_217));
  HS65_GS_AOI21X2 g24129__6131(.A (n_213), .B (n_212), .C (n_211), .Z
       (n_214));
  HS65_GS_OAI32X5 g24135__1881(.A (address_5), .B (n_209), .C (n_168),
       .D (n_377), .E (n_219), .Z (n_210));
  HS65_GS_OAI212X5 g24144__5115(.A (n_207), .B (n_431), .C (n_209), .D
       (n_84), .E (n_263), .Z (n_208));
  HS65_GS_OA311X9 g24146__7482(.A (address_7), .B (n_2), .C (n_205), .D
       (n_188), .E (n_113), .Z (n_206));
  HS65_GS_NOR2X6 g24116__4733(.A (n_366), .B (n_320), .Z (n_265));
  HS65_GS_OA22X9 g24095__6161(.A (n_431), .B (n_204), .C (n_447), .D
       (n_203), .Z (n_318));
  HS65_GS_OR4X4 g23974__9315(.A (Bus2IP_RdCE[13]), .B (n_202), .C
       (Bus2IP_RdCE[12]), .D (Bus2IP_RdCE[14]), .Z (n_383));
  HS65_GS_AOI12X2 g24097__9945(.A (n_241), .B (n_249), .C (n_508), .Z
       (n_406));
  HS65_GS_NOR3X1 g24012__2883(.A (Bus2IP_RdCE[10]), .B
       (Bus2IP_RdCE[11]), .C (n_202), .Z (n_300));
  HS65_GS_OAI32X5 g24094__2346(.A (n_209), .B (n_193), .C (n_342), .D
       (n_433), .E (n_204), .Z (n_353));
  HS65_GS_NAND2X7 g24112__1666(.A (n_212), .B (n_201), .Z (n_370));
  HS65_GS_OR2X9 g24113__7410(.A (n_411), .B (n_387), .Z (n_335));
  HS65_GS_NAND2X7 g24118__6417(.A (n_39), .B (n_200), .Z (n_404));
  HS65_GS_OA112X9 g24152__5477(.A (n_584), .B (n_199), .C (n_126), .D
       (n_111), .Z (n_427));
  HS65_GS_NOR2X6 g24127__2398(.A (n_39), .B (n_387), .Z (n_475));
  HS65_GS_NAND2X7 g24125__5107(.A (n_39), .B (n_197), .Z (n_501));
  HS65_GS_HA1X4 g24038__6260(.A0 (endx_0), .B0 (n_451), .CO (n_302),
       .S0 (n_196));
  HS65_GS_AOI21X2 g24106__4319(.A (reseta_bit_slv_reg0), .B (n_484), .C
       (n_1), .Z (n_195));
  HS65_GS_CB4I1X9 g24050__8428(.A (n_193), .B (n_162), .C (n_377), .D
       (n_249), .Z (n_194));
  HS65_GS_NAND2X7 g24110__5526(.A (n_321), .B (n_191), .Z (n_192));
  HS65_GS_NAND4ABX3 g24079__6783(.A (n_100), .B (endy_0), .C
       (chip_sdo_1), .D (n_833), .Z (n_190));
  HS65_GS_OA222X4 g24091__3680(.A (n_181), .B (n_447), .C (n_431), .D
       (n_227), .E (n_366), .F (n_188), .Z (n_189));
  HS65_GS_CBI4I1X5 g24102__1617(.A (address_4), .B (n_380), .C (n_186),
       .D (n_321), .Z (n_187));
  HS65_GS_AO12X9 g24103__2802(.A (n_184), .B (reseta_bit_slv_reg0), .C
       (n_183), .Z (n_185));
  HS65_GS_OA31X9 g24104__1705(.A (n_23), .B (n_181), .C (n_431), .D
       (n_225), .Z (n_182));
  HS65_GS_NAND2X7 g24105__5122(.A (n_282), .B (n_179), .Z (n_180));
  HS65_GS_AO31X9 g24039__8246(.A (n_95), .B (n_165), .C (n_276), .D
       (n_310), .Z (n_178));
  HS65_GS_NAND2X7 g24107__7098(.A (n_348), .B (n_392), .Z (n_177));
  HS65_GS_AND2X4 g24108__6131(.A (n_392), .B (n_418), .Z (n_176));
  HS65_GS_NAND2X7 g24115__1881(.A (n_343), .B (n_112), .Z (n_284));
  HS65_GS_OR2X9 g24114__5115(.A (address_2), .B (n_448), .Z (n_275));
  HS65_GS_NOR2X6 g24119__7482(.A (n_172), .B (n_348), .Z (n_389));
  HS65_GS_NAND2X7 g24117__4733(.A (n_39), .B (n_191), .Z (n_443));
  HS65_GS_OR2X9 g24121__6161(.A (n_39), .B (n_402), .Z (n_445));
  HS65_GS_OR2X9 g24122__9315(.A (n_39), .B (n_417), .Z (n_507));
  HS65_GS_NAND2X7 g24067__9945(.A (n_232), .B (n_139), .Z (n_386));
  HS65_GS_AO12X9 g24141__2883(.A (n_396), .B (n_172), .C (n_203), .Z
       (n_173));
  HS65_GS_CBI4I1X5 g24202__2346(.A (address_6), .B (n_466), .C (n_170),
       .D (n_271), .Z (n_171));
  HS65_GS_NAND3X5 g24199__1666(.A (n_168), .B (n_508), .C (n_215), .Z
       (n_169));
  HS65_GS_CB4I6X9 g24128__7410(.A (n_433), .B (n_250), .C (n_172), .D
       (n_285), .Z (n_167));
  HS65_GS_AO12X9 g24130__6417(.A (n_165), .B (n_164), .C (n_447), .Z
       (n_166));
  HS65_GS_AO112X9 g24133__5477(.A (n_226), .B (n_256), .C (n_562), .D
       (n_162), .Z (n_163));
  HS65_GS_OA12X9 g24136__2398(.A (n_342), .B (n_291), .C (n_53), .Z
       (n_161));
  HS65_GS_NAND4ABX3 g24139__5107(.A (n_132), .B (n_181), .C
       (address_0), .D (n_159), .Z (n_160));
  HS65_GS_AO12X9 g24140__6260(.A (n_157), .B (n_268), .C (n_306), .Z
       (n_158));
  HS65_GS_AO12X9 g24194__4319(.A (n_155), .B (n_154), .C (n_256), .Z
       (n_156));
  HS65_GS_AOI22X6 g24143__8428(.A (n_2), .B (n_186), .C (address_2), .D
       (n_152), .Z (n_153));
  HS65_GS_AO212X4 g24147__5526(.A (address_2), .B (n_162), .C (n_466),
       .D (n_229), .E (address_4), .Z (n_151));
  HS65_GS_CNIVX7 g24190(.A (n_149), .Z (n_150));
  HS65_GS_IVX7 g24155(.A (n_147), .Z (n_148));
  HS65_GS_NAND4ABX3 g24208__6783(.A (n_466), .B (n_250), .C
       (address_6), .D (n_245), .Z (n_267));
  HS65_GS_AO12X9 g24151__3680(.A (n_291), .B (n_162), .C (n_250), .Z
       (n_324));
  HS65_GS_NAND2X7 g24123__1617(.A (n_28), .B (n_359), .Z (n_391));
  HS65_GS_OR2X9 g24124__2802(.A (n_39), .B (n_448), .Z (n_395));
  HS65_GS_OR2X9 g24126__1705(.A (n_39), .B (n_345), .Z (n_467));
  HS65_GS_HA1X4 g23993__5122(.A0 (slv_reg_11_2), .B0 (n_70), .CO
       (n_145), .S0 (n_146));
  HS65_GS_HA1X4 g23995__8246(.A0 (n_833), .B0 (n_99), .CO (n_143), .S0
       (n_144));
  HS65_GS_HA1X4 g23996__7098(.A0 (endy_2), .B0 (n_67), .CO (n_142), .S0
       (n_330));
  HS65_GS_HA1X4 g23994__6131(.A0 (n_855), .B0 (n_68), .CO (n_141), .S0
       (n_299));
  HS65_GS_NOR3X4 g23997__1881(.A (slv_reg_10_2), .B (slv_reg_10_1), .C
       (n_139), .Z (n_140));
  HS65_GS_IVX9 g24160(.A (n_418), .Z (n_138));
  HS65_GS_CNIVX7 g24156(.A (n_136), .Z (n_137));
  HS65_GS_AOI12X2 g24131__5115(.A (n_205), .B (n_218), .C (n_310), .Z
       (n_135));
  HS65_GS_AO12X9 g24132__7482(.A (n_181), .B (n_362), .C (address_2),
       .Z (n_134));
  HS65_GS_OA12X9 g24137__4733(.A (address_5), .B (n_132), .C (n_362),
       .Z (n_133));
  HS65_GS_OAI12X3 g24142__6161(.A (n_130), .B (n_186), .C (n_129), .Z
       (n_131));
  HS65_GS_OA22X9 g24145__9315(.A (n_339), .B (n_117), .C (n_155), .D
       (n_351), .Z (n_128));
  HS65_GS_OAI32X5 g24149__9945(.A (n_466), .B (n_250), .C (n_229), .D
       (n_377), .E (n_238), .Z (n_127));
  HS65_GS_IVX9 g24157(.A (n_204), .Z (n_201));
  HS65_GS_OA222X4 g24154__2883(.A (n_34), .B (n_584), .C (n_43), .D
       (n_727), .E (n_726), .F (n_126), .Z (n_429));
  HS65_GS_AOI112X4 g24120__2346(.A (EA_1), .B (n_110), .C (n_589), .D
       (n_109), .Z (n_331));
  HS65_GS_OA12X9 g24153__1666(.A (n_727), .B (n_587), .C (n_101), .Z
       (n_428));
  HS65_GS_NAND2X7 g24174__7410(.A (n_35), .B (n_97), .Z (n_295));
  HS65_GS_IVX9 g24161(.A (n_368), .Z (n_200));
  HS65_GS_NOR2X6 g24169__6417(.A (n_431), .B (n_164), .Z (n_147));
  HS65_GS_NOR2X6 g24172__5477(.A (n_164), .B (n_351), .Z (n_211));
  HS65_GS_IVX9 g24191(.A (n_223), .Z (n_197));
  HS65_GS_NAND2X7 g24204__2398(.A (n_89), .B (n_254), .Z (n_252));
  HS65_GS_NOR3X4 g24207__5107(.A (n_245), .B (n_41), .C (n_132), .Z
       (n_149));
  HS65_GS_NAND3X5 g24256__6260(.A (address_6), .B (n_39), .C (n_81), .Z
       (n_263));
  HS65_GS_IVX9 g24158(.A (n_359), .Z (n_307));
  HS65_GS_OR2X9 g24211__4319(.A (n_250), .B (n_291), .Z (n_374));
  HS65_GS_IVX9 g24159(.A (n_191), .Z (n_320));
  HS65_GS_NAND2X7 g24185__8428(.A (address_4), .B (n_123), .Z (n_387));
  HS65_GS_AND2X4 g24167__5526(.A (n_121), .B (n_276), .Z (n_122));
  HS65_GS_NAND2X7 g24168__6783(.A (n_696), .B (n_119), .Z (n_120));
  HS65_GS_NAND2X7 g24171__3680(.A (n_118), .B (n_276), .Z (n_179));
  HS65_GS_AND2X4 g24170__1617(.A (n_119), .B (slv_reg_9_0), .Z (n_183));
  HS65_GS_NAND4ABX3 g24150__2802(.A (Bus2IP_RdCE[5]), .B
       (Bus2IP_RdCE[4]), .C (n_61), .D (n_64), .Z (n_202));
  HS65_GS_NOR2X6 g24173__1705(.A (n_433), .B (n_117), .Z (n_136));
  HS65_GS_NAND2X7 g24175__5122(.A (n_213), .B (n_85), .Z (n_231));
  HS65_GS_OR2X9 g24176__8246(.A (n_310), .B (n_118), .Z (n_225));
  HS65_GS_OR2X9 g24177__7098(.A (n_28), .B (n_162), .Z (n_247));
  HS65_GS_NOR2X6 g24187__6131(.A (n_41), .B (n_362), .Z (n_191));
  HS65_GS_OR2X9 g24178__1881(.A (n_562), .B (n_416), .Z (n_412));
  HS65_GS_OR2X9 g24179__5115(.A (n_2), .B (n_121), .Z (n_241));
  HS65_GS_NOR2X6 g24184__7482(.A (n_35), .B (n_355), .Z (n_359));
  HS65_GS_OR2X9 g24181__4733(.A (address_4), .B (n_121), .Z (n_204));
  HS65_GS_OR2X9 g24180__6161(.A (n_53), .B (n_121), .Z (n_249));
  HS65_GS_OR2X9 g24182__9315(.A (n_53), .B (n_362), .Z (n_448));
  HS65_GS_NAND2X7 g24183__9945(.A (address_4), .B (n_130), .Z (n_417));
  HS65_GS_OR2X9 g24186__2883(.A (address_4), .B (n_203), .Z (n_345));
  HS65_GS_OR2X9 g24188__2346(.A (address_4), .B (n_227), .Z (n_418));
  HS65_GS_OR2X9 g24198__1666(.A (n_447), .B (n_117), .Z (n_113));
  HS65_GS_OAI32X5 g24201__7410(.A (address_5), .B (address_6), .C
       (n_28), .D (address_7), .E (n_209), .Z (n_112));
  HS65_GS_AOI21X2 g24203__6417(.A (n_110), .B (n_589), .C (n_109), .Z
       (n_111));
  HS65_GS_NAND3X5 g24197__5477(.A (n_82), .B (address_1), .C (n_216),
       .Z (n_108));
  HS65_GSS_XOR2X6 g24071__2398(.A (chip_sdo_1), .B (n_98), .Z (n_107));
  HS65_GS_OA32X4 g24193__5107(.A (address_6), .B (n_53), .C (n_433), .D
       (n_339), .E (n_181), .Z (n_106));
  HS65_GS_AND2X4 g24205__6260(.A (n_238), .B (n_203), .Z (n_236));
  HS65_GS_NAND2X7 g24226__4319(.A (n_35), .B (n_380), .Z (n_289));
  HS65_GS_OR2X9 g24223__8428(.A (address_5), .B (n_207), .Z (n_280));
  HS65_GS_IVX9 g24216(.A (n_254), .Z (n_219));
  HS65_GS_OR2X9 g24230__5526(.A (address_6), .B (n_205), .Z (n_325));
  HS65_GS_IVX9 g24250(.A (n_484), .Z (n_232));
  HS65_GS_OR2X9 g24209__6783(.A (n_260), .B (n_355), .Z (n_287));
  HS65_GS_OR2X9 g24210__3680(.A (n_35), .B (n_203), .Z (n_223));
  HS65_GS_OR2X9 g24212__1617(.A (n_41), .B (n_238), .Z (n_348));
  HS65_GS_OR2X9 g24214__2802(.A (n_53), .B (n_162), .Z (n_392));
  HS65_GS_OR2X9 g24213__1705(.A (address_4), .B (n_355), .Z (n_402));
  HS65_GS_CB4I6X9 g24215__5122(.A (EA_2), .B (EA_1), .C (EA_3), .D
       (n_119), .Z (n_440));
  HS65_GS_OR2X9 g24189__8246(.A (n_35), .B (n_238), .Z (n_368));
  HS65_GS_AOI21X2 g24192__7098(.A (n_75), .B (n_587), .C (n_589), .Z
       (n_101));
  HS65_GS_NAND2X7 g24101__6131(.A (n_99), .B (n_98), .Z (n_100));
  HS65_GS_IVX9 g24219(.A (n_162), .Z (n_97));
  HS65_GS_OAI211X5 g24196__1881(.A (n_170), .B (n_39), .C (n_285), .D
       (n_193), .Z (n_96));
  HS65_GS_IVX9 g24221(.A (n_396), .Z (n_159));
  HS65_GS_IVX9 g24218(.A (n_227), .Z (n_123));
  HS65_GS_OR3X9 g24206__5115(.A (n_209), .B (n_95), .C (n_433), .Z
       (n_293));
  HS65_GS_NAND2X7 g24254__7482(.A (n_35), .B (n_55), .Z (n_157));
  HS65_GS_IVX9 g24249(.A (n_256), .Z (n_215));
  HS65_GS_IVX9 g24246(.A (n_129), .Z (n_172));
  HS65_GS_IVX9 g24220(.A (n_130), .Z (n_291));
  HS65_GS_IVX9 g24222(.A (n_355), .Z (n_152));
  HS65_GS_IVX9 g24274(.A (n_380), .Z (n_154));
  HS65_GS_NAND2X7 g24255__4733(.A (address_1), .B (n_89), .Z (n_361));
  HS65_GS_IVX9 g24247(.A (n_212), .Z (n_226));
  HS65_GS_OR2X9 g24231__6161(.A (n_23), .B (n_205), .Z (n_164));
  HS65_GS_NOR2X6 g24261__9315(.A (n_110), .B (n_585), .Z (n_332));
  HS65_GS_NOR2X6 g24235__9945(.A (address_7), .B (n_181), .Z (n_254));
  HS65_GS_NAND3X5 g24272__2883(.A (EA_3), .B (EA_2), .C (n_684), .Z
       (n_484));
  HS65_GS_NOR2X6 g24111__2346(.A (slv_reg_10_1), .B (n_46), .Z (n_139));
  HS65_GS_IVX9 g24248(.A (n_346), .Z (n_270));
  HS65_GS_NOR2X6 g24224__1666(.A (EA_1), .B (n_726), .Z (n_109));
  HS65_GS_NAND2X7 g24225__7410(.A (n_41), .B (n_216), .Z (n_188));
  HS65_GS_NAND2X7 g24227__6417(.A (n_584), .B (n_587), .Z (n_184));
  HS65_GS_IVX9 g24245(.A (n_165), .Z (n_213));
  HS65_GS_NAND2X7 g24257__5477(.A (address_0), .B (n_86), .Z (n_411));
  HS65_GS_OR2X9 g24229__2398(.A (n_53), .B (n_95), .Z (n_118));
  HS65_GS_NAND2X7 g24228__5107(.A (n_35), .B (n_168), .Z (n_218));
  HS65_GS_NOR2X6 g24240__6260(.A (address_5), .B (n_285), .Z (n_130));
  HS65_GS_IVX9 g24217(.A (n_85), .Z (n_351));
  HS65_GS_OR2X9 g24237__4319(.A (address_5), .B (n_155), .Z (n_227));
  HS65_GS_AND2X4 g24242__8428(.A (n_726), .B (n_589), .Z (n_451));
  HS65_GS_OR2X9 g24233__5526(.A (n_245), .B (n_95), .Z (n_121));
  HS65_GS_NAND2X7 g24267__6783(.A (n_2), .B (n_86), .Z (n_416));
  HS65_GS_OR2X9 g24234__3680(.A (n_245), .B (n_285), .Z (n_203));
  HS65_GS_OR2X9 g24241__1617(.A (n_28), .B (n_433), .Z (n_396));
  HS65_GS_NAND2X7 g24238__2802(.A (n_245), .B (n_168), .Z (n_238));
  HS65_GS_OR2X9 g24239__1705(.A (n_245), .B (n_155), .Z (n_162));
  HS65_GS_NAND2X7 g24243__5122(.A (address_5), .B (n_168), .Z (n_362));
  HS65_GS_IVX9 g24302(.A (n_83), .Z (n_84));
  HS65_GS_IVX9 g24305(.A (n_250), .Z (n_82));
  HS65_GS_IVX9 g24275(.A (n_181), .Z (n_81));
  HS65_GS_NOR2X6 g24312__8246(.A (n_35), .B (n_39), .Z (n_271));
  HS65_GS_NAND2X7 g24313__7098(.A (address_6), .B (n_35), .Z (n_207));
  HS65_GS_NAND2X7 g24259__6131(.A (address_4), .B (n_168), .Z (n_117));
  HS65_GS_NOR2X6 g24266__1881(.A (n_39), .B (n_342), .Z (n_129));
  HS65_GS_AND2X4 g24258__5115(.A (n_285), .B (n_155), .Z (n_132));
  HS65_GS_NOR2X6 g24262__7482(.A (n_75), .B (n_684), .Z (n_329));
  HS65_GS_OR2X9 g24263__4733(.A (n_35), .B (n_155), .Z (n_268));
  HS65_GS_NOR2X6 g24264__6161(.A (n_35), .B (n_285), .Z (n_186));
  HS65_GS_NOR2X6 g24268__9315(.A (n_508), .B (n_377), .Z (n_212));
  HS65_GS_AND2X4 g24232__9945(.A (n_584), .B (n_684), .Z (n_119));
  HS65_GS_NOR2X6 g24293__2883(.A (address_6), .B (n_245), .Z (n_380));
  HS65_GS_OR2X9 g24271__2346(.A (address_4), .B (n_377), .Z (n_256));
  HS65_GS_OR2X9 g24269__1666(.A (n_35), .B (n_193), .Z (n_276));
  HS65_GS_OR2X9 g24244__7410(.A (address_5), .B (n_95), .Z (n_355));
  HS65_GS_HA1X4 g24166__6417(.A0 (endy_1), .B0 (endy_2), .CO (n_98),
       .S0 (n_72));
  HS65_GS_HA1X4 g24164__5477(.A0 (slv_reg_11_0), .B0 (slv_reg_11_1),
       .CO (n_70), .S0 (n_71));
  HS65_GS_HA1X4 g24165__2398(.A0 (endx_0), .B0 (n_846), .CO (n_68), .S0
       (n_69));
  HS65_GS_HA1X4 g24162__5107(.A0 (endy_1), .B0 (endy_0), .CO (n_67),
       .S0 (n_316));
  HS65_GS_HA1X4 g24163__6260(.A0 (n_846), .B0 (n_855), .CO (n_99), .S0
       (n_66));
  HS65_GS_CNIVX7 g24277(.A (n_168), .Z (n_65));
  HS65_GS_NOR4X4 g24253__4319(.A (Bus2IP_RdCE[2]), .B (Bus2IP_RdCE[3]),
       .C (Bus2IP_RdCE[8]), .D (Bus2IP_RdCE[9]), .Z (n_64));
  HS65_GS_IVX9 g24273(.A (n_62), .Z (n_63));
  HS65_GS_NOR4X4 g24252__8428(.A (Bus2IP_RdCE[0]), .B (Bus2IP_RdCE[1]),
       .C (Bus2IP_RdCE[6]), .D (Bus2IP_RdCE[7]), .Z (n_61));
  HS65_GS_NOR3X4 g24251__5526(.A (Bus2IP_WrCE[14]), .B
       (Bus2IP_WrCE[10]), .C (Bus2IP_WrCE[11]), .Z (n_60));
  HS65_GS_IVX7 g24276(.A (n_726), .Z (n_59));
  HS65_GS_NOR2X6 g24236__6783(.A (address_1), .B (n_310), .Z (n_85));
  HS65_GS_IVX9 g24280(.A (n_684), .Z (n_126));
  HS65_GS_IVX9 g24281(.A (n_727), .Z (n_110));
  HS65_GS_NAND3X5 g24265__3680(.A (address_5), .B (n_170), .C (n_35),
       .Z (n_165));
  HS65_GS_NAND2X7 g24317__1617(.A (address_4), .B (n_245), .Z (n_205));
  HS65_GS_NAND2X7 g24270__2802(.A (n_39), .B (n_343), .Z (n_346));
  HS65_GS_NAND2X7 g24294__1705(.A (address_4), .B (address_5), .Z
       (n_181));
  HS65_GS_IVX9 g24303(.A (n_95), .Z (n_55));
  HS65_GS_IVX9 g24307(.A (n_447), .Z (n_89));
  HS65_GS_NOR2X6 g24310__5122(.A (n_23), .B (n_245), .Z (n_83));
  HS65_GS_NAND2X7 g24260__8246(.A (n_508), .B (n_321), .Z (n_306));
  HS65_GS_OR2X9 g24319__7098(.A (address_3), .B (address_4), .Z
       (n_209));
  HS65_GS_IVX9 g24306(.A (n_86), .Z (n_366));
  HS65_GS_NAND2X7 g24324__6131(.A (n_35), .B (address_3), .Z (n_250));
  HS65_GS_NOR2X6 g24282__1881(.A (Bus2IP_WrCE[12]), .B
       (Bus2IP_WrCE[13]), .Z (n_49));
  HS65_GS_OR4X4 g24200__5115(.A (slv_reg_10_3), .B (slv_reg_10_4), .C
       (slv_reg_10_2), .D (slv_reg_10_0), .Z (n_46));
  HS65_GS_IVX9 g24279(.A (n_584), .Z (n_75));
  HS65_GS_NOR2X6 g24283__7482(.A (Bus2IP_WrCE[8]), .B (Bus2IP_WrCE[9]),
       .Z (n_62));
  HS65_GS_NOR2X6 g24284__4733(.A (Bus2IP_WrCE[0]), .B (Bus2IP_WrCE[2]),
       .Z (n_477));
  HS65_GS_NOR2X6 g24285__6161(.A (Bus2IP_WrCE[1]), .B (Bus2IP_WrCE[3]),
       .Z (n_480));
  HS65_GS_AND2X4 g24325__9315(.A (address_1), .B (n_466), .Z (n_86));
  HS65_GS_IVX9 g24278(.A (n_343), .Z (n_277));
  HS65_GS_NOR2X6 g24287__9945(.A (n_170), .B (n_245), .Z (n_216));
  HS65_GS_NOR2X6 g24289__2883(.A (Bus2IP_WrCE[6]), .B (Bus2IP_WrCE[7]),
       .Z (n_494));
  HS65_GS_AND2X4 g24292__2346(.A (n_43), .B (EA_1), .Z (n_589));
  HS65_GS_AND2X18 g24296__7410(.A (n_23), .B (address_7), .Z (n_168));
  HS65_GS_OR2X9 g24320__6417(.A (address_1), .B (n_562), .Z (n_512));
  HS65_GS_OR2X9 g24301__2398(.A (n_23), .B (n_170), .Z (n_285));
  HS65_GS_IVX9 g24309(.A (n_321), .Z (n_431));
  HS65_GS_IVX9 g24387(.A (n_53), .Z (n_41));
  HS65_GS_IVX9 g24304(.A (n_585), .Z (n_199));
  HS65_GS_IVX9 g24308(.A (n_310), .Z (n_282));
  HS65_GS_NAND2X7 g24311__5107(.A (n_39), .B (n_508), .Z (n_260));
  HS65_GS_NAND2X7 g24290__6260(.A (n_245), .B (address_7), .Z (n_193));
  HS65_GS_NAND2X7 g24314__4319(.A (n_170), .B (n_245), .Z (n_229));
  HS65_GS_NAND2X7 g24316__8428(.A (n_508), .B (n_2), .Z (n_339));
  HS65_GS_NAND2X7 g24315__5526(.A (n_466), .B (address_0), .Z (n_372));
  HS65_GS_NOR2X6 g24288__6783(.A (Bus2IP_WrCE[4]), .B (Bus2IP_WrCE[5]),
       .Z (n_491));
  HS65_GS_AND2X4 g24291__3680(.A (n_34), .B (EA_0), .Z (n_587));
  HS65_GS_NAND2X7 g24318__1617(.A (address_6), .B (n_170), .Z (n_95));
  HS65_GS_AND2X4 g24299__2802(.A (n_43), .B (n_34), .Z (n_684));
  HS65_GS_NAND2X14 g24322__1705(.A (n_23), .B (n_170), .Z (n_155));
  HS65_GS_NAND2X7 g24323__5122(.A (n_508), .B (address_2), .Z (n_342));
  HS65_GS_OR2X9 g24328__8246(.A (n_2), .B (address_2), .Z (n_447));
  HS65_GS_OR2X9 g24327__7098(.A (address_3), .B (n_466), .Z (n_377));
  HS65_GS_IVX9 g24379(.A (address_3), .Z (n_2));
  HS65_GS_CNIVX7 g24371(.A (n_39), .Z (n_28));
  HS65_GS_NAND2X7 g24286__6131(.A (address_0), .B (address_1), .Z
       (n_487));
  HS65_GS_AND2X4 g24297__1881(.A (address_1), .B (address_2), .Z
       (n_343));
  HS65_GS_AND2X4 g24321__5115(.A (EA_1), .B (EA_0), .Z (n_585));
  HS65_GS_OR2X9 g24326__7482(.A (address_1), .B (address_2), .Z
       (n_433));
  HS65_GS_NOR2X6 g24330__4733(.A (address_3), .B (address_2), .Z
       (n_321));
  HS65_GS_BFX9 g24388(.A (n_35), .Z (n_53));
  HS65_GS_NOR2X6 g24298__6161(.A (EA_2), .B (EA_3), .Z (n_584));
  HS65_GS_NAND2X7 g24329__9315(.A (address_3), .B (address_2), .Z
       (n_310));
  HS65_GS_CNIVX7 g24358(.A (endy_1), .Z (n_21));
  HS65_GS_IVX9 g24356(.A (endx_0), .Z (n_20));
  HS65_GS_IVX9 g24426(.A (n_846), .Z (n_382));
  HS65_GS_IVX9 g24439(.A (address_6), .Z (n_23));
  HS65_GS_IVX9 g24422(.A (endy_0), .Z (n_233));
  HS65_GS_IVX9 g24427(.A (address_7), .Z (n_170));
  HS65_GS_IVX18 g24407(.A (address_4), .Z (n_35));
  HS65_GS_IVX9 g24441(.A (address_5), .Z (n_245));
  HS65_GS_IVX18 g24444(.A (address_2), .Z (n_466));
  HS65_GS_IVX18 g24443(.A (address_1), .Z (n_508));
  HS65_GS_IVX2 g24446(.A (Bus2IP_Reset), .Z (n_696));
  HS65_GS_IVX7 g24339(.A (slv_reg_9_0), .Z (n_1));
  HS65_GS_CNIVX7 g24350(.A (EA_0), .Z (n_43));
  HS65_GS_IVX9 g24421(.A (EA_1), .Z (n_34));
  HS65_GS_BFX9 g24376(.A (address_3), .Z (n_39));
  HS65_GS_IVX2 g24445(.A (Bus2IP_Clk), .Z (n_490));
  HS65_GS_IVX9 g24442(.A (address_0), .Z (n_562));
  HS65_GS_CB4I1X9 g2(.A (n_468), .B (n_446), .C (address_0), .D
       (n_352), .Z (n_700));
  HS65_GS_NOR2AX3 g24583(.A (EA_3), .B (EA_2), .Z (n_726));
  HS65_GS_NOR2AX3 g24584(.A (EA_2), .B (EA_3), .Z (n_727));
  HS65_GS_NOR4X4 g24585(.A (n_322), .B (n_406), .C (n_474), .D (n_499),
       .Z (n_728));
  HS65_GS_AOI12X4 g24586(.A (n_769), .B (n_667), .C (n_729), .Z
       (n_730));
  HS65_GSS_XNOR2X6 g3(.A (n_775), .B (n_622), .Z (n_729));
  HS65_GS_SDFPRQTX4 EA_reg_3(.RN (n_696), .CP (Bus2IP_Clk), .D (n_695),
       .TI (n_733), .TE (chip_scan_se), .Q (EA_3), .TQ (n_731));
  HS65_GS_SDFPRQTX4 EA_reg_1(.RN (n_696), .CP (Bus2IP_Clk), .D (n_694),
       .TI (n_734), .TE (chip_scan_se), .Q (EA_1), .TQ (n_732));
  HS65_GS_SDFPRQTX4 EA_reg_2(.RN (n_696), .CP (Bus2IP_Clk), .D (n_693),
       .TI (n_732), .TE (chip_scan_se), .Q (EA_2), .TQ (n_733));
  HS65_GS_SDFPRQTX4 EA_reg_0(.RN (n_696), .CP (Bus2IP_Clk), .D (n_689),
       .TI (chip_sdi_2), .TE (chip_scan_se), .Q (EA_0), .TQ (n_734));
  HS65_GSS_SDFPRQNX18 address_reg_7(.RN (n_696), .CP (n_490), .D
       (n_460), .TI (address_6), .TE (chip_scan_se), .QN (address_7));
  HS65_GS_SDFPRQNX9 address_reg_3(.RN (n_696), .CP (n_490), .D (n_442),
       .TI (address_2), .TE (chip_scan_se), .QN (address_3));
  HS65_GS_SDFPRQNX9 address_reg_0(.RN (n_696), .CP (n_490), .D (n_415),
       .TI (chip_sdi_1), .TE (chip_scan_se), .QN (address_0));
  HS65_GS_SDFPRQNX9 address_reg_1(.RN (n_696), .CP (n_490), .D (n_414),
       .TI (address_0), .TE (chip_scan_se), .QN (address_1));
  HS65_GSS_SDFPRQNX18 address_reg_2(.RN (n_696), .CP (n_490), .D
       (n_430), .TI (address_1), .TE (chip_scan_se), .QN (address_2));
  HS65_GSS_SDFPRQNX18 address_reg_4(.RN (n_696), .CP (n_490), .D
       (n_312), .TI (address_3), .TE (chip_scan_se), .QN (address_4));
  HS65_GSS_SDFPRQX35 address_reg_6(.RN (n_696), .CP (n_490), .D
       (n_333), .TI (address_5), .TE (chip_scan_se), .Q (address_6));
  HS65_GSS_SDFPRQNX27 address_reg_5(.RN (n_696), .CP (n_490), .D
       (n_317), .TI (address_4), .TE (chip_scan_se), .QN (address_5));
  HS65_GSS_SDFPQX27 user_int_reg(.CP (Bus2IP_Clk), .D (n_262), .TI
       (slv_reg_14_3), .TE (chip_scan_se), .Q (user_int));
  HS65_GS_SDFPRQTX4 reseta_bit_slv_reg0_reg(.RN (n_696), .CP
       (Bus2IP_Clk), .D (n_185), .TI (n_731), .TE (chip_scan_se), .Q
       (reseta_bit_slv_reg0), .TQ (n_744));
  HS65_GS_SDFPRQTX4 endx_reg_0(.RN (n_696), .CP (n_490), .D (n_196),
       .TI (address_7), .TE (chip_scan_se), .Q (endx_0), .TQ (n_745));
  HS65_GS_MUX21X4 g19(.D0 (Bus2IP_Data[2]), .D1 (slv_reg_4_2), .S0
       (n_559), .Z (n_746));
  HS65_GS_MUX21X4 g24602(.D0 (Bus2IP_Data[5]), .D1 (slv_reg_6_5), .S0
       (n_560), .Z (n_747));
  HS65_GS_MUX21X4 g20(.D0 (Bus2IP_Data[1]), .D1 (slv_reg_5_1), .S0
       (n_556), .Z (n_748));
  HS65_GS_MUX21X4 g24603(.D0 (Bus2IP_Data[7]), .D1 (slv_reg_6_7), .S0
       (n_560), .Z (n_749));
  HS65_GS_MUX21X4 g24604(.D0 (Bus2IP_Data[3]), .D1 (slv_reg_4_3), .S0
       (n_559), .Z (n_750));
  HS65_GS_MUX21X4 g24605(.D0 (Bus2IP_Data[1]), .D1 (slv_reg_4_1), .S0
       (n_559), .Z (n_751));
  HS65_GS_MUX21X4 g24606(.D0 (Bus2IP_Data[5]), .D1 (slv_reg_5_5), .S0
       (n_556), .Z (n_752));
  HS65_GS_MUX21X4 g24607(.D0 (n_195), .D1 (Bus2IP_Data[0]), .S0
       (n_506), .Z (n_753));
  HS65_GS_SDFPHRQTX9 slv_reg_reg_8_1(.RN (n_696), .CP (Bus2IP_Clk), .D
       (Bus2IP_Data[1]), .E (n_554), .TI (n_768), .TE (chip_scan_se),
       .Q (n_755), .TQ (n_754));
  HS65_GS_SDFPHRQTX9 slv_reg_reg_8_7(.RN (n_696), .CP (Bus2IP_Clk), .D
       (Bus2IP_Data[7]), .E (n_554), .TI (n_758), .TE (chip_scan_se),
       .Q (n_757), .TQ (n_756));
  HS65_GS_SDFPHRQTX9 slv_reg_reg_8_6(.RN (n_696), .CP (Bus2IP_Clk), .D
       (Bus2IP_Data[6]), .E (n_554), .TI (n_770), .TE (chip_scan_se),
       .Q (n_759), .TQ (n_758));
  HS65_GS_MUX21X4 g24614(.D0 (Bus2IP_Data[0]), .D1 (slv_reg_4_0), .S0
       (n_559), .Z (n_760));
  HS65_GS_SDFPHRQTX9 slv_reg_reg_8_4(.RN (n_696), .CP (Bus2IP_Clk), .D
       (Bus2IP_Data[4]), .E (n_554), .TI (n_774), .TE (chip_scan_se),
       .Q (n_762), .TQ (n_761));
  HS65_GS_SDFPHRQTX9 slv_reg_reg_8_2(.RN (n_696), .CP (Bus2IP_Clk), .D
       (Bus2IP_Data[2]), .E (n_554), .TI (n_754), .TE (chip_scan_se),
       .Q (n_764), .TQ (n_763));
  HS65_GS_MUX21X4 g24619(.D0 (Bus2IP_Data[6]), .D1 (slv_reg_4_6), .S0
       (n_559), .Z (n_765));
  HS65_GS_MUX21X4 g24620(.D0 (Bus2IP_Data[7]), .D1 (slv_reg_4_7), .S0
       (n_559), .Z (n_766));
  HS65_GS_MUX21X4 g24621(.D0 (Bus2IP_Data[5]), .D1 (slv_reg_4_5), .S0
       (n_559), .Z (n_767));
  HS65_GS_SDFPHRQTX9 slv_reg_reg_8_0(.RN (n_696), .CP (Bus2IP_Clk), .D
       (Bus2IP_Data[0]), .E (n_554), .TI (slv_reg_7_7), .TE
       (chip_scan_se), .Q (n_769), .TQ (n_768));
  HS65_GS_SDFPHRQTX9 slv_reg_reg_8_5(.RN (n_696), .CP (Bus2IP_Clk), .D
       (Bus2IP_Data[5]), .E (n_554), .TI (n_761), .TE (chip_scan_se),
       .Q (n_771), .TQ (n_770));
  HS65_GS_MUX21X4 g24626(.D0 (Bus2IP_Data[1]), .D1 (slv_reg_6_1), .S0
       (n_560), .Z (n_772));
  HS65_GS_MUX21X4 g24627(.D0 (Bus2IP_Data[0]), .D1 (slv_reg_5_0), .S0
       (n_556), .Z (n_773));
  HS65_GS_SDFPHRQTX9 slv_reg_reg_8_3(.RN (n_696), .CP (Bus2IP_Clk), .D
       (Bus2IP_Data[3]), .E (n_554), .TI (n_763), .TE (chip_scan_se),
       .Q (n_775), .TQ (n_774));
  HS65_GS_MUX21X4 g24630(.D0 (Bus2IP_Data[0]), .D1 (slv_reg_7_0), .S0
       (n_542), .Z (n_776));
  HS65_GS_MUX21X4 g24631(.D0 (Bus2IP_Data[5]), .D1 (slv_reg_7_5), .S0
       (n_542), .Z (n_777));
  HS65_GS_MUX21X4 g24632(.D0 (Bus2IP_Data[6]), .D1 (slv_reg_7_6), .S0
       (n_542), .Z (n_778));
  HS65_GS_MUX21X4 g24633(.D0 (Bus2IP_Data[7]), .D1 (slv_reg_7_7), .S0
       (n_542), .Z (n_779));
  HS65_GS_MUX21X4 g24634(.D0 (Bus2IP_Data[4]), .D1 (slv_reg_7_4), .S0
       (n_542), .Z (n_780));
  HS65_GS_MUX21X4 g24635(.D0 (Bus2IP_Data[2]), .D1 (slv_reg_5_2), .S0
       (n_556), .Z (n_781));
  HS65_GS_MUX21X4 g24636(.D0 (Bus2IP_Data[4]), .D1 (slv_reg_4_4), .S0
       (n_559), .Z (n_782));
  HS65_GS_MUX21X4 g24637(.D0 (Bus2IP_Data[1]), .D1 (slv_reg_7_1), .S0
       (n_542), .Z (n_783));
  HS65_GS_MUX21X4 g24638(.D0 (Bus2IP_Data[6]), .D1 (slv_reg_5_6), .S0
       (n_556), .Z (n_784));
  HS65_GS_MUX21X4 g24639(.D0 (Bus2IP_Data[7]), .D1 (slv_reg_5_7), .S0
       (n_556), .Z (n_785));
  HS65_GS_MUX21X4 g24640(.D0 (Bus2IP_Data[0]), .D1 (slv_reg_6_0), .S0
       (n_560), .Z (n_786));
  HS65_GS_MUX21X4 g24641(.D0 (Bus2IP_Data[2]), .D1 (slv_reg_6_2), .S0
       (n_560), .Z (n_787));
  HS65_GS_MUX21X4 g24642(.D0 (Bus2IP_Data[3]), .D1 (slv_reg_6_3), .S0
       (n_560), .Z (n_788));
  HS65_GS_MUX21X4 g24643(.D0 (Bus2IP_Data[4]), .D1 (slv_reg_6_4), .S0
       (n_560), .Z (n_789));
  HS65_GS_MUX21X4 g24644(.D0 (Bus2IP_Data[6]), .D1 (slv_reg_6_6), .S0
       (n_560), .Z (n_790));
  HS65_GS_MUX21X4 g24645(.D0 (Bus2IP_Data[2]), .D1 (slv_reg_7_2), .S0
       (n_542), .Z (n_791));
  HS65_GS_MUX21X4 g24646(.D0 (Bus2IP_Data[3]), .D1 (slv_reg_7_3), .S0
       (n_542), .Z (n_792));
  HS65_GS_MUX21X4 g24647(.D0 (Bus2IP_Data[4]), .D1 (slv_reg_5_4), .S0
       (n_556), .Z (n_793));
  HS65_GS_MUX21X4 g24648(.D0 (Bus2IP_Data[3]), .D1 (slv_reg_5_3), .S0
       (n_556), .Z (n_794));
  HS65_GS_MUX21X4 g24649(.D0 (Bus2IP_Data[1]), .D1 (slv_reg_3_1), .S0
       (n_539), .Z (n_795));
  HS65_GS_MUX21X4 g24650(.D0 (Bus2IP_Data[1]), .D1 (slv_reg_2_1), .S0
       (n_536), .Z (n_796));
  HS65_GS_MUX21X4 g24651(.D0 (Bus2IP_Data[5]), .D1 (slv_reg_0_5), .S0
       (n_537), .Z (n_797));
  HS65_GS_MUX21X4 g24652(.D0 (Bus2IP_Data[3]), .D1 (slv_reg_1_3), .S0
       (n_538), .Z (n_798));
  HS65_GS_MUX21X4 g24653(.D0 (Bus2IP_Data[5]), .D1 (slv_reg_3_5), .S0
       (n_539), .Z (n_799));
  HS65_GS_MUX21X4 g24654(.D0 (Bus2IP_Data[0]), .D1 (slv_reg_1_0), .S0
       (n_538), .Z (n_800));
  HS65_GS_MUX21X4 g24655(.D0 (Bus2IP_Data[1]), .D1 (slv_reg_1_1), .S0
       (n_538), .Z (n_801));
  HS65_GS_MUX21X4 g24656(.D0 (Bus2IP_Data[1]), .D1 (slv_reg_0_1), .S0
       (n_537), .Z (n_802));
  HS65_GS_MUX21X4 g24657(.D0 (Bus2IP_Data[7]), .D1 (slv_reg_0_7), .S0
       (n_537), .Z (n_803));
  HS65_GS_MUX21X4 g24658(.D0 (Bus2IP_Data[2]), .D1 (slv_reg_2_2), .S0
       (n_536), .Z (n_804));
  HS65_GS_MUX21X4 g24659(.D0 (Bus2IP_Data[0]), .D1 (slv_reg_0_0), .S0
       (n_537), .Z (n_805));
  HS65_GS_MUX21X4 g24660(.D0 (Bus2IP_Data[2]), .D1 (slv_reg_0_2), .S0
       (n_537), .Z (n_806));
  HS65_GS_MUX21X4 g24661(.D0 (Bus2IP_Data[3]), .D1 (slv_reg_0_3), .S0
       (n_537), .Z (n_807));
  HS65_GS_MUX21X4 g24662(.D0 (Bus2IP_Data[6]), .D1 (slv_reg_0_6), .S0
       (n_537), .Z (n_808));
  HS65_GS_MUX21X4 g24663(.D0 (Bus2IP_Data[4]), .D1 (slv_reg_0_4), .S0
       (n_537), .Z (n_809));
  HS65_GS_MUX21X4 g24664(.D0 (Bus2IP_Data[5]), .D1 (slv_reg_1_5), .S0
       (n_538), .Z (n_810));
  HS65_GS_MUX21X4 g24665(.D0 (Bus2IP_Data[7]), .D1 (slv_reg_3_7), .S0
       (n_539), .Z (n_811));
  HS65_GS_MUX21X4 g24666(.D0 (Bus2IP_Data[3]), .D1 (slv_reg_2_3), .S0
       (n_536), .Z (n_812));
  HS65_GS_MUX21X4 g24667(.D0 (Bus2IP_Data[6]), .D1 (slv_reg_2_6), .S0
       (n_536), .Z (n_813));
  HS65_GS_MUX21X4 g24668(.D0 (Bus2IP_Data[7]), .D1 (slv_reg_2_7), .S0
       (n_536), .Z (n_814));
  HS65_GS_MUX21X4 g24669(.D0 (Bus2IP_Data[2]), .D1 (slv_reg_1_2), .S0
       (n_538), .Z (n_815));
  HS65_GS_MUX21X4 g24670(.D0 (Bus2IP_Data[2]), .D1 (slv_reg_3_2), .S0
       (n_539), .Z (n_816));
  HS65_GS_MUX21X4 g24671(.D0 (Bus2IP_Data[0]), .D1 (slv_reg_2_0), .S0
       (n_536), .Z (n_817));
  HS65_GS_MUX21X4 g24672(.D0 (Bus2IP_Data[7]), .D1 (slv_reg_1_7), .S0
       (n_538), .Z (n_818));
  HS65_GS_MUX21X4 g24673(.D0 (Bus2IP_Data[5]), .D1 (slv_reg_2_5), .S0
       (n_536), .Z (n_819));
  HS65_GS_MUX21X4 g24674(.D0 (Bus2IP_Data[6]), .D1 (slv_reg_3_6), .S0
       (n_539), .Z (n_820));
  HS65_GS_MUX21X4 g24675(.D0 (Bus2IP_Data[4]), .D1 (slv_reg_1_4), .S0
       (n_538), .Z (n_821));
  HS65_GS_MUX21X4 g24676(.D0 (Bus2IP_Data[6]), .D1 (slv_reg_1_6), .S0
       (n_538), .Z (n_822));
  HS65_GS_MUX21X4 g24677(.D0 (Bus2IP_Data[4]), .D1 (slv_reg_2_4), .S0
       (n_536), .Z (n_823));
  HS65_GS_MUX21X4 g24678(.D0 (Bus2IP_Data[3]), .D1 (slv_reg_3_3), .S0
       (n_539), .Z (n_824));
  HS65_GS_MUX21X4 g24679(.D0 (Bus2IP_Data[4]), .D1 (slv_reg_3_4), .S0
       (n_539), .Z (n_825));
  HS65_GS_MUX21X4 g24680(.D0 (Bus2IP_Data[0]), .D1 (slv_reg_3_0), .S0
       (n_539), .Z (n_826));
  HS65_GS_MUX21X4 g24681(.D0 (n_357), .D1 (slv_reg_10_4), .S0 (n_484),
       .Z (n_827));
  HS65_GS_MUX21X4 g24682(.D0 (n_358), .D1 (slv_reg_10_3), .S0 (n_484),
       .Z (n_828));
  HS65_GS_MUX21X4 g24683(.D0 (n_846), .D1 (slv_reg_13_1), .S0 (n_455),
       .Z (n_829));
  HS65_GS_MUX21X4 g24684(.D0 (n_855), .D1 (slv_reg_13_2), .S0 (n_455),
       .Z (n_830));
  HS65_GS_MUX21X4 g24685(.D0 (n_316), .D1 (endy_1), .S0 (n_438), .Z
       (n_831));
  HS65_GS_SDFPHRQTX9 endx_reg_3(.RN (n_696), .CP (n_490), .D (n_441),
       .E (n_451), .TI (n_854), .TE (chip_scan_se), .Q (n_833), .TQ
       (n_832));
  HS65_GS_MUX21X4 g24688(.D0 (endy_1), .D1 (slv_reg_14_1), .S0 (n_455),
       .Z (n_834));
  HS65_GS_MUX21X4 g24689(.D0 (endy_2), .D1 (slv_reg_14_2), .S0 (n_455),
       .Z (n_835));
  HS65_GS_MUX21X4 g24690(.D0 (chip_sdo_1), .D1 (slv_reg_14_3), .S0
       (n_455), .Z (n_836));
  HS65_GS_MUX21X4 g24691(.D0 (endx_0), .D1 (slv_reg_13_0), .S0 (n_455),
       .Z (n_837));
  HS65_GS_MUX21X4 g24692(.D0 (endy_0), .D1 (slv_reg_14_0), .S0 (n_455),
       .Z (n_838));
  HS65_GS_MUX21X4 g24693(.D0 (n_833), .D1 (slv_reg_13_3), .S0 (n_455),
       .Z (n_839));
  HS65_GS_MUX21X4 g24694(.D0 (n_330), .D1 (endy_2), .S0 (n_438), .Z
       (n_840));
  HS65_GS_MUX21X4 g24695(.D0 (n_233), .D1 (endy_0), .S0 (n_438), .Z
       (n_841));
  HS65_GS_MUX21X4 g24696(.D0 (n_437), .D1 (chip_sdo_1), .S0 (n_438), .Z
       (n_842));
  HS65_GS_MUX21X4 g24697(.D0 (chip_sdo_1), .D1 (slv_reg_12_3), .S0
       (n_386), .Z (n_843));
  HS65_GS_MUX21X4 g24698(.D0 (n_846), .D1 (slv_reg_11_1), .S0 (n_386),
       .Z (n_844));
  HS65_GS_SDFPHRQTX9 endx_reg_1(.RN (n_696), .CP (n_490), .D (n_382),
       .E (n_302), .TI (n_745), .TE (chip_scan_se), .Q (n_846), .TQ
       (n_845));
  HS65_GS_MUX21X4 g24701(.D0 (endy_0), .D1 (slv_reg_12_0), .S0 (n_386),
       .Z (n_847));
  HS65_GS_MUX21X4 g24702(.D0 (endy_1), .D1 (slv_reg_12_1), .S0 (n_386),
       .Z (n_848));
  HS65_GS_MUX21X4 g24703(.D0 (endy_2), .D1 (slv_reg_12_2), .S0 (n_386),
       .Z (n_849));
  HS65_GS_MUX21X4 g24704(.D0 (n_833), .D1 (slv_reg_11_3), .S0 (n_386),
       .Z (n_850));
  HS65_GS_MUX21X4 g24705(.D0 (n_855), .D1 (slv_reg_11_2), .S0 (n_386),
       .Z (n_851));
  HS65_GS_MUX21X4 g24706(.D0 (endx_0), .D1 (slv_reg_11_0), .S0 (n_386),
       .Z (n_852));
  HS65_GS_MUX21X4 g24707(.D0 (n_146), .D1 (slv_reg_10_2), .S0 (n_484),
       .Z (n_853));
  HS65_GS_SDFPHRQTX9 endx_reg_2(.RN (n_696), .CP (n_490), .D (n_299),
       .E (n_451), .TI (n_845), .TE (chip_scan_se), .Q (n_855), .TQ
       (n_854));
  HS65_GS_MUX21X4 g24711(.D0 (n_71), .D1 (slv_reg_10_1), .S0 (n_484),
       .Z (n_857));
  HS65_GS_MUX21I1X6 g24712(.D0 (slv_reg_11_0), .D1 (slv_reg_10_0), .S0
       (n_484), .Z (n_861));
endmodule

