
// Generated by Cadence Genus(TM) Synthesis Solution 21.12-s068_1
// Generated on: Jun 18 2026 20:11:41 -03 (Jun 18 2026 23:11:41 UTC)

// Verification Directory fv/multiplier_param_N8 

module multiplier_param_N8(in1, in2, start, reset, clk, out, done,
     chip_scan_se, chip_scan_tm, chip_sdi_1, chip_sdo_1);
  input [7:0] in1, in2;
  input start, reset, clk, chip_scan_se, chip_scan_tm, chip_sdi_1;
  output [15:0] out;
  output done, chip_sdo_1;
  wire [7:0] in1, in2;
  wire start, reset, clk, chip_scan_se, chip_scan_tm, chip_sdi_1;
  wire [15:0] out;
  wire done, chip_sdo_1;
  wire add_58_20_n_292, add_58_20_n_294, add_58_20_n_296,
       add_58_20_n_298, add_58_20_n_300, add_58_20_n_302,
       add_58_20_n_304, add_58_20_n_306;
  wire add_58_20_n_308, add_58_20_n_310, add_58_20_n_312,
       add_58_20_n_314, add_58_20_n_316, add_58_20_n_318,
       add_58_20_n_320, count_0;
  wire count_1, count_2, count_3, n_0, n_1, n_2, n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_29;
  wire n_30, n_31, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_52, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_123, n_124;
  wire n_142, n_143, n_144, n_145, n_147, n_149, n_151, n_153;
  wire n_156, n_158, n_161, n_162, n_163, n_164, n_165, n_166;
  wire n_167, par_out_a_0, par_out_a_1, par_out_a_2, par_out_a_3,
       par_out_a_4, par_out_a_5, par_out_a_6;
  wire par_out_a_7, par_out_a_8, par_out_a_9, par_out_a_10,
       par_out_a_11, par_out_a_12, par_out_a_13, par_out_a_14;
  wire par_out_a_15, par_out_b_0, par_out_b_1, par_out_b_2,
       par_out_b_3, par_out_b_4, par_out_b_5, par_out_b_6;
  wire par_out_b_7, state_0, state_1;
  HS65_GS_IVX9 g608(.A (start), .Z (n_52));
  HS65_GS_NOR2X6 g959__2398(.A (par_out_a_15), .B (par_out_b_0), .Z
       (n_91));
  HS65_GS_NOR2X6 g961__5107(.A (par_out_a_14), .B (n_29), .Z (n_46));
  HS65_GS_NOR2X6 g962__6260(.A (par_out_a_14), .B (par_out_b_0), .Z
       (n_90));
  HS65_GS_NOR2X6 g964__4319(.A (par_out_a_13), .B (n_29), .Z (n_45));
  HS65_GS_NOR2X6 g965__8428(.A (par_out_a_13), .B (par_out_b_0), .Z
       (n_89));
  HS65_GS_NOR2X6 g967__5526(.A (par_out_a_12), .B (n_29), .Z (n_44));
  HS65_GS_NOR2X6 g968__6783(.A (par_out_a_12), .B (par_out_b_0), .Z
       (n_88));
  HS65_GS_NOR2X6 g970__3680(.A (par_out_a_11), .B (n_29), .Z (n_43));
  HS65_GS_NOR2X6 g971__1617(.A (par_out_a_11), .B (par_out_b_0), .Z
       (n_87));
  HS65_GS_NOR2X6 g973__2802(.A (par_out_a_10), .B (n_29), .Z (n_42));
  HS65_GS_NOR2X6 g974__1705(.A (par_out_a_10), .B (par_out_b_0), .Z
       (n_86));
  HS65_GS_NOR2X6 g976__5122(.A (par_out_a_9), .B (n_29), .Z (n_41));
  HS65_GS_NOR2X6 g977__8246(.A (par_out_a_9), .B (par_out_b_0), .Z
       (n_85));
  HS65_GS_NOR2X6 g979__7098(.A (par_out_a_8), .B (n_29), .Z (n_40));
  HS65_GS_NOR2X6 g980__6131(.A (par_out_a_8), .B (par_out_b_0), .Z
       (n_84));
  HS65_GS_NOR2X6 g982__1881(.A (par_out_b_0), .B (par_out_a_0), .Z
       (n_76));
  HS65_GS_NOR2X6 g983__5115(.A (par_out_b_0), .B (par_out_a_1), .Z
       (n_77));
  HS65_GS_NOR2X6 g984__7482(.A (par_out_a_7), .B (n_29), .Z (n_39));
  HS65_GS_NOR2X6 g985__4733(.A (par_out_a_7), .B (par_out_b_0), .Z
       (n_83));
  HS65_GS_NOR2X6 g986__6161(.A (par_out_a_4), .B (par_out_b_0), .Z
       (n_80));
  HS65_GS_NOR2X6 g987__9315(.A (par_out_a_5), .B (par_out_b_0), .Z
       (n_81));
  HS65_GS_NOR2X6 g988__9945(.A (par_out_a_6), .B (par_out_b_0), .Z
       (n_82));
  HS65_GS_NOR2X6 g989__2883(.A (par_out_a_3), .B (par_out_b_0), .Z
       (n_79));
  HS65_GS_NOR2X6 g990__2346(.A (par_out_a_2), .B (par_out_b_0), .Z
       (n_78));
  HS65_GS_SDFPRQNX9 par_out_b_reg_0(.RN (n_0), .CP (clk), .D (n_145),
       .TI (par_out_a_15), .TE (chip_scan_se), .QN (par_out_b_0));
  HS65_GS_SDFPRQNX9 par_out_a_reg_7(.RN (n_0), .CP (clk), .D (n_161),
       .TI (par_out_a_6), .TE (chip_scan_se), .QN (par_out_a_7));
  HS65_GS_SDFPRQX9 par_out_b_reg_1(.RN (n_0), .CP (clk), .D (n_147),
       .TI (par_out_b_0), .TE (chip_scan_se), .Q (par_out_b_1));
  HS65_GS_SDFPRQNX9 par_out_a_reg_6(.RN (n_0), .CP (clk), .D (n_162),
       .TI (par_out_a_5), .TE (chip_scan_se), .QN (par_out_a_6));
  HS65_GS_SDFPRQX9 par_out_b_reg_2(.RN (n_0), .CP (clk), .D (n_149),
       .TI (par_out_b_1), .TE (chip_scan_se), .Q (par_out_b_2));
  HS65_GS_SDFPRQNX9 par_out_a_reg_5(.RN (n_0), .CP (clk), .D (n_163),
       .TI (par_out_a_4), .TE (chip_scan_se), .QN (par_out_a_5));
  HS65_GS_SDFPRQX9 par_out_b_reg_3(.RN (n_0), .CP (clk), .D (n_151),
       .TI (par_out_b_2), .TE (chip_scan_se), .Q (par_out_b_3));
  HS65_GS_SDFPRQNX9 par_out_a_reg_4(.RN (n_0), .CP (clk), .D (n_164),
       .TI (par_out_a_3), .TE (chip_scan_se), .QN (par_out_a_4));
  HS65_GS_SDFPRQX9 par_out_b_reg_4(.RN (n_0), .CP (clk), .D (n_153),
       .TI (par_out_b_3), .TE (chip_scan_se), .Q (par_out_b_4));
  HS65_GS_SDFPRQNX9 par_out_a_reg_3(.RN (n_0), .CP (clk), .D (n_165),
       .TI (par_out_a_2), .TE (chip_scan_se), .QN (par_out_a_3));
  HS65_GS_SDFPRQNX9 par_out_a_reg_2(.RN (n_0), .CP (clk), .D (n_166),
       .TI (par_out_a_1), .TE (chip_scan_se), .QN (par_out_a_2));
  HS65_GS_SDFPRQX9 par_out_b_reg_5(.RN (n_0), .CP (clk), .D (n_156),
       .TI (par_out_b_4), .TE (chip_scan_se), .Q (par_out_b_5));
  HS65_GS_SDFPRQNX9 par_out_a_reg_1(.RN (n_0), .CP (clk), .D (n_167),
       .TI (par_out_a_0), .TE (chip_scan_se), .QN (par_out_a_1));
  HS65_GS_SDFPRQX9 par_out_b_reg_6(.RN (n_0), .CP (clk), .D (n_158),
       .TI (par_out_b_5), .TE (chip_scan_se), .Q (par_out_b_6));
  HS65_GS_AND2X4 g1014__1666(.A (n_29), .B (in2[7]), .Z (n_31));
  HS65_GS_AND2X4 g1015__7410(.A (n_29), .B (in1[0]), .Z (n_30));
  HS65_GS_BFX9 g1017(.A (n_27), .Z (n_29));
  HS65_GS_OR2X9 g1019__6417(.A (count_2), .B (n_74), .Z (n_75));
  HS65_GS_OR2X9 g1020__5477(.A (count_1), .B (count_0), .Z (n_74));
  HS65_GS_NOR2AX19 g1021__2398(.A (state_1), .B (state_0), .Z (done));
  HS65_GS_NAND2AX7 g1022__5107(.A (state_1), .B (state_0), .Z (n_110));
  HS65_GS_IVX7 g1024(.A (reset), .Z (n_0));
  HS65_GS_NOR3AX9 g2__6260(.A (count_3), .B (n_110), .C (n_75), .Z
       (n_27));
  HS65_GS_OAI32X5 g665__4319(.A (n_52), .B (state_1), .C (state_0), .D
       (n_110), .E (n_4), .Z (n_26));
  HS65_GS_AO112X9 g683__8428(.A (count_3), .B (n_75), .C (n_110), .D
       (n_4), .Z (n_25));
  HS65_GS_NOR2AX3 g684__5526(.A (n_4), .B (n_110), .Z (n_24));
  HS65_GS_AND2X4 g687__6783(.A (n_101), .B (n_5), .Z (n_23));
  HS65_GS_AND2X4 g688__3680(.A (n_108), .B (n_5), .Z (n_22));
  HS65_GS_AND2X4 g689__1617(.A (n_106), .B (n_5), .Z (n_21));
  HS65_GS_AND2X4 g690__2802(.A (n_105), .B (n_5), .Z (n_20));
  HS65_GS_AND2X4 g691__1705(.A (n_104), .B (n_5), .Z (n_19));
  HS65_GS_AND2X4 g692__5122(.A (n_94), .B (n_5), .Z (n_18));
  HS65_GS_AND2X4 g693__8246(.A (n_103), .B (n_5), .Z (n_17));
  HS65_GS_AND2X4 g694__7098(.A (n_102), .B (n_5), .Z (n_16));
  HS65_GS_AND2X4 g695__6131(.A (n_107), .B (n_5), .Z (n_15));
  HS65_GS_AOI21X2 g696__1881(.A (n_1), .B (n_75), .C (n_110), .Z
       (n_14));
  HS65_GS_AND2X4 g697__5115(.A (n_96), .B (n_5), .Z (n_13));
  HS65_GS_AND2X4 g698__7482(.A (n_99), .B (n_5), .Z (n_12));
  HS65_GS_AND2X4 g699__4733(.A (n_98), .B (n_5), .Z (n_11));
  HS65_GS_AND2X4 g700__6161(.A (n_97), .B (n_5), .Z (n_10));
  HS65_GS_AND2X4 g701__9315(.A (n_95), .B (n_5), .Z (n_9));
  HS65_GS_AND2X4 g702__9945(.A (n_5), .B (n_109), .Z (n_8));
  HS65_GS_AOI21X2 g703__2883(.A (n_2), .B (n_74), .C (n_110), .Z (n_7));
  HS65_GS_AND2X4 g704__2346(.A (n_100), .B (n_5), .Z (n_6));
  HS65_GSS_XOR2X6 g706__1666(.A (state_0), .B (state_1), .Z (n_5));
  HS65_GS_NAND2AX7 g707__7410(.A (n_110), .B (count_0), .Z (n_3));
  HS65_GS_NOR2X6 g708__6417(.A (count_3), .B (n_75), .Z (n_4));
  HS65_GS_NAND2X7 g709__5477(.A (count_1), .B (count_0), .Z (n_2));
  HS65_GS_NAND2X7 g710__2398(.A (count_2), .B (n_74), .Z (n_1));
  HS65_GSS_XOR3X2 add_58_20_g366__5107(.A (out[15]), .B (n_91), .C
       (add_58_20_n_292), .Z (n_94));
  HS65_GS_FA1X4 add_58_20_g367__6260(.A0 (out[14]), .B0 (n_90), .CI
       (add_58_20_n_294), .CO (add_58_20_n_292), .S0 (n_95));
  HS65_GS_FA1X4 add_58_20_g368__4319(.A0 (out[13]), .B0 (n_89), .CI
       (add_58_20_n_296), .CO (add_58_20_n_294), .S0 (n_96));
  HS65_GS_FA1X4 add_58_20_g369__8428(.A0 (out[12]), .B0 (n_88), .CI
       (add_58_20_n_298), .CO (add_58_20_n_296), .S0 (n_97));
  HS65_GS_FA1X4 add_58_20_g370__5526(.A0 (out[11]), .B0 (n_87), .CI
       (add_58_20_n_300), .CO (add_58_20_n_298), .S0 (n_98));
  HS65_GS_FA1X4 add_58_20_g371__6783(.A0 (out[10]), .B0 (n_86), .CI
       (add_58_20_n_302), .CO (add_58_20_n_300), .S0 (n_99));
  HS65_GS_FA1X4 add_58_20_g372__3680(.A0 (out[9]), .B0 (n_85), .CI
       (add_58_20_n_304), .CO (add_58_20_n_302), .S0 (n_100));
  HS65_GS_FA1X4 add_58_20_g373__1617(.A0 (out[8]), .B0 (n_84), .CI
       (add_58_20_n_306), .CO (add_58_20_n_304), .S0 (n_101));
  HS65_GS_FA1X4 add_58_20_g374__2802(.A0 (out[7]), .B0 (n_83), .CI
       (add_58_20_n_308), .CO (add_58_20_n_306), .S0 (n_102));
  HS65_GS_FA1X4 add_58_20_g375__1705(.A0 (out[6]), .B0 (n_82), .CI
       (add_58_20_n_310), .CO (add_58_20_n_308), .S0 (n_103));
  HS65_GS_FA1X4 add_58_20_g376__5122(.A0 (out[5]), .B0 (n_81), .CI
       (add_58_20_n_312), .CO (add_58_20_n_310), .S0 (n_104));
  HS65_GS_FA1X4 add_58_20_g377__8246(.A0 (out[4]), .B0 (n_80), .CI
       (add_58_20_n_314), .CO (add_58_20_n_312), .S0 (n_105));
  HS65_GS_FA1X4 add_58_20_g378__7098(.A0 (out[3]), .B0 (n_79), .CI
       (add_58_20_n_316), .CO (add_58_20_n_314), .S0 (n_106));
  HS65_GS_FA1X4 add_58_20_g379__6131(.A0 (out[2]), .B0 (n_78), .CI
       (add_58_20_n_318), .CO (add_58_20_n_316), .S0 (n_107));
  HS65_GS_FA1X4 add_58_20_g380__1881(.A0 (out[1]), .B0 (n_77), .CI
       (add_58_20_n_320), .CO (add_58_20_n_318), .S0 (n_108));
  HS65_GS_HA1X4 add_58_20_g381__5115(.A0 (n_76), .B0 (out[0]), .CO
       (add_58_20_n_320), .S0 (n_109));
  HS65_GS_SDFPRQNX9 par_out_a_reg_15(.RN (n_0), .CP (clk), .D (n_46),
       .TI (par_out_a_14), .TE (chip_scan_se), .QN (par_out_a_15));
  HS65_GS_SDFPRQNX9 par_out_a_reg_14(.RN (n_0), .CP (clk), .D (n_45),
       .TI (par_out_a_13), .TE (chip_scan_se), .QN (par_out_a_14));
  HS65_GS_SDFPRQNX9 par_out_a_reg_13(.RN (n_0), .CP (clk), .D (n_44),
       .TI (par_out_a_12), .TE (chip_scan_se), .QN (par_out_a_13));
  HS65_GS_SDFPRQNX9 par_out_a_reg_12(.RN (n_0), .CP (clk), .D (n_43),
       .TI (par_out_a_11), .TE (chip_scan_se), .QN (par_out_a_12));
  HS65_GS_SDFPRQNX9 par_out_a_reg_11(.RN (n_0), .CP (clk), .D (n_42),
       .TI (par_out_a_10), .TE (chip_scan_se), .QN (par_out_a_11));
  HS65_GS_SDFPRQNX9 par_out_a_reg_10(.RN (n_0), .CP (clk), .D (n_41),
       .TI (par_out_a_9), .TE (chip_scan_se), .QN (par_out_a_10));
  HS65_GS_SDFPRQNX9 par_out_a_reg_9(.RN (n_0), .CP (clk), .D (n_40),
       .TI (par_out_a_8), .TE (chip_scan_se), .QN (par_out_a_9));
  HS65_GS_SDFPRQNX9 par_out_a_reg_8(.RN (n_0), .CP (clk), .D (n_39),
       .TI (par_out_a_7), .TE (chip_scan_se), .QN (par_out_a_8));
  HS65_GS_SDFPRQNX9 par_out_a_reg_0(.RN (n_0), .CP (clk), .D (n_30),
       .TI (out[15]), .TE (chip_scan_se), .QN (par_out_a_0));
  HS65_GS_SDFPRQX9 par_out_b_reg_7(.RN (n_0), .CP (clk), .D (n_31), .TI
       (par_out_b_6), .TE (chip_scan_se), .Q (par_out_b_7));
  HS65_GS_SDFPRQTX4 state_reg_0(.RN (n_0), .CP (clk), .D (n_26), .TI
       (par_out_b_7), .TE (chip_scan_se), .Q (state_0), .TQ (n_123));
  HS65_GS_SDFPSQTX9 count_reg_3(.SN (n_0), .CP (clk), .D (n_25), .TI
       (n_142), .TE (chip_scan_se), .Q (count_3), .TQ (n_124));
  HS65_GS_SDFPRQTX4 state_reg_1(.RN (n_0), .CP (clk), .D (n_24), .TI
       (n_123), .TE (chip_scan_se), .Q (state_1), .TQ (chip_sdo_1));
  HS65_GSS_SDFPRQX27 out_reg_0(.RN (n_0), .CP (clk), .D (n_8), .TI
       (n_124), .TE (chip_scan_se), .Q (out[0]));
  HS65_GSS_SDFPRQX27 out_reg_1(.RN (n_0), .CP (clk), .D (n_22), .TI
       (out[0]), .TE (chip_scan_se), .Q (out[1]));
  HS65_GSS_SDFPRQX27 out_reg_2(.RN (n_0), .CP (clk), .D (n_15), .TI
       (out[1]), .TE (chip_scan_se), .Q (out[2]));
  HS65_GSS_SDFPRQX27 out_reg_3(.RN (n_0), .CP (clk), .D (n_21), .TI
       (out[2]), .TE (chip_scan_se), .Q (out[3]));
  HS65_GSS_SDFPRQX27 out_reg_4(.RN (n_0), .CP (clk), .D (n_20), .TI
       (out[3]), .TE (chip_scan_se), .Q (out[4]));
  HS65_GSS_SDFPRQX27 out_reg_5(.RN (n_0), .CP (clk), .D (n_19), .TI
       (out[4]), .TE (chip_scan_se), .Q (out[5]));
  HS65_GSS_SDFPRQX27 out_reg_6(.RN (n_0), .CP (clk), .D (n_17), .TI
       (out[5]), .TE (chip_scan_se), .Q (out[6]));
  HS65_GSS_SDFPRQX27 out_reg_7(.RN (n_0), .CP (clk), .D (n_16), .TI
       (out[6]), .TE (chip_scan_se), .Q (out[7]));
  HS65_GSS_SDFPRQX27 out_reg_8(.RN (n_0), .CP (clk), .D (n_23), .TI
       (out[7]), .TE (chip_scan_se), .Q (out[8]));
  HS65_GSS_SDFPRQX27 out_reg_9(.RN (n_0), .CP (clk), .D (n_6), .TI
       (out[8]), .TE (chip_scan_se), .Q (out[9]));
  HS65_GSS_SDFPRQX27 out_reg_10(.RN (n_0), .CP (clk), .D (n_12), .TI
       (out[9]), .TE (chip_scan_se), .Q (out[10]));
  HS65_GSS_SDFPRQX27 out_reg_11(.RN (n_0), .CP (clk), .D (n_11), .TI
       (out[10]), .TE (chip_scan_se), .Q (out[11]));
  HS65_GSS_SDFPRQX27 out_reg_12(.RN (n_0), .CP (clk), .D (n_10), .TI
       (out[11]), .TE (chip_scan_se), .Q (out[12]));
  HS65_GSS_SDFPRQX27 out_reg_13(.RN (n_0), .CP (clk), .D (n_13), .TI
       (out[12]), .TE (chip_scan_se), .Q (out[13]));
  HS65_GSS_SDFPRQX27 out_reg_14(.RN (n_0), .CP (clk), .D (n_9), .TI
       (out[13]), .TE (chip_scan_se), .Q (out[14]));
  HS65_GSS_SDFPRQX27 out_reg_15(.RN (n_0), .CP (clk), .D (n_18), .TI
       (out[14]), .TE (chip_scan_se), .Q (out[15]));
  HS65_GS_SDFPRQTX4 count_reg_2(.RN (n_0), .CP (clk), .D (n_14), .TI
       (n_143), .TE (chip_scan_se), .Q (count_2), .TQ (n_142));
  HS65_GS_SDFPRQTX4 count_reg_1(.RN (n_0), .CP (clk), .D (n_7), .TI
       (n_144), .TE (chip_scan_se), .Q (count_1), .TQ (n_143));
  HS65_GS_SDFPSQTX9 count_reg_0(.SN (n_0), .CP (clk), .D (n_3), .TI
       (chip_sdi_1), .TE (chip_scan_se), .Q (count_0), .TQ (n_144));
  HS65_GS_MUX21X4 g14(.D0 (par_out_b_1), .D1 (in2[0]), .S0 (n_27), .Z
       (n_145));
  HS65_GS_MUX21X4 g20(.D0 (par_out_b_2), .D1 (in2[1]), .S0 (n_27), .Z
       (n_147));
  HS65_GS_MUX21X4 g19(.D0 (par_out_b_3), .D1 (in2[2]), .S0 (n_27), .Z
       (n_149));
  HS65_GS_MUX21X4 g1060(.D0 (par_out_b_4), .D1 (in2[3]), .S0 (n_27), .Z
       (n_151));
  HS65_GS_MUX21X4 g1062(.D0 (par_out_b_5), .D1 (in2[4]), .S0 (n_27), .Z
       (n_153));
  HS65_GS_MUX21X4 g1065(.D0 (par_out_b_6), .D1 (in2[5]), .S0 (n_27), .Z
       (n_156));
  HS65_GS_MUX21X4 g1066(.D0 (par_out_b_7), .D1 (in2[6]), .S0 (n_27), .Z
       (n_158));
  HS65_GS_MUX21I1X6 g2(.D0 (par_out_a_6), .D1 (in1[7]), .S0 (n_27), .Z
       (n_161));
  HS65_GS_MUX21I1X6 g1067(.D0 (par_out_a_5), .D1 (in1[6]), .S0 (n_27),
       .Z (n_162));
  HS65_GS_MUX21I1X6 g1068(.D0 (par_out_a_4), .D1 (in1[5]), .S0 (n_27),
       .Z (n_163));
  HS65_GS_MUX21I1X6 g1069(.D0 (par_out_a_3), .D1 (in1[4]), .S0 (n_27),
       .Z (n_164));
  HS65_GS_MUX21I1X6 g1070(.D0 (par_out_a_2), .D1 (in1[3]), .S0 (n_27),
       .Z (n_165));
  HS65_GS_MUX21I1X6 g1071(.D0 (par_out_a_1), .D1 (in1[2]), .S0 (n_27),
       .Z (n_166));
  HS65_GS_MUX21I1X6 g1072(.D0 (par_out_a_0), .D1 (in1[1]), .S0 (n_27),
       .Z (n_167));
endmodule

