
//input ports
add mapped point in1[63] in1[63] -type PI PI
add mapped point in1[62] in1[62] -type PI PI
add mapped point in1[61] in1[61] -type PI PI
add mapped point in1[60] in1[60] -type PI PI
add mapped point in1[59] in1[59] -type PI PI
add mapped point in1[58] in1[58] -type PI PI
add mapped point in1[57] in1[57] -type PI PI
add mapped point in1[56] in1[56] -type PI PI
add mapped point in1[55] in1[55] -type PI PI
add mapped point in1[54] in1[54] -type PI PI
add mapped point in1[53] in1[53] -type PI PI
add mapped point in1[52] in1[52] -type PI PI
add mapped point in1[51] in1[51] -type PI PI
add mapped point in1[50] in1[50] -type PI PI
add mapped point in1[49] in1[49] -type PI PI
add mapped point in1[48] in1[48] -type PI PI
add mapped point in1[47] in1[47] -type PI PI
add mapped point in1[46] in1[46] -type PI PI
add mapped point in1[45] in1[45] -type PI PI
add mapped point in1[44] in1[44] -type PI PI
add mapped point in1[43] in1[43] -type PI PI
add mapped point in1[42] in1[42] -type PI PI
add mapped point in1[41] in1[41] -type PI PI
add mapped point in1[40] in1[40] -type PI PI
add mapped point in1[39] in1[39] -type PI PI
add mapped point in1[38] in1[38] -type PI PI
add mapped point in1[37] in1[37] -type PI PI
add mapped point in1[36] in1[36] -type PI PI
add mapped point in1[35] in1[35] -type PI PI
add mapped point in1[34] in1[34] -type PI PI
add mapped point in1[33] in1[33] -type PI PI
add mapped point in1[32] in1[32] -type PI PI
add mapped point in1[31] in1[31] -type PI PI
add mapped point in1[30] in1[30] -type PI PI
add mapped point in1[29] in1[29] -type PI PI
add mapped point in1[28] in1[28] -type PI PI
add mapped point in1[27] in1[27] -type PI PI
add mapped point in1[26] in1[26] -type PI PI
add mapped point in1[25] in1[25] -type PI PI
add mapped point in1[24] in1[24] -type PI PI
add mapped point in1[23] in1[23] -type PI PI
add mapped point in1[22] in1[22] -type PI PI
add mapped point in1[21] in1[21] -type PI PI
add mapped point in1[20] in1[20] -type PI PI
add mapped point in1[19] in1[19] -type PI PI
add mapped point in1[18] in1[18] -type PI PI
add mapped point in1[17] in1[17] -type PI PI
add mapped point in1[16] in1[16] -type PI PI
add mapped point in1[15] in1[15] -type PI PI
add mapped point in1[14] in1[14] -type PI PI
add mapped point in1[13] in1[13] -type PI PI
add mapped point in1[12] in1[12] -type PI PI
add mapped point in1[11] in1[11] -type PI PI
add mapped point in1[10] in1[10] -type PI PI
add mapped point in1[9] in1[9] -type PI PI
add mapped point in1[8] in1[8] -type PI PI
add mapped point in1[7] in1[7] -type PI PI
add mapped point in1[6] in1[6] -type PI PI
add mapped point in1[5] in1[5] -type PI PI
add mapped point in1[4] in1[4] -type PI PI
add mapped point in1[3] in1[3] -type PI PI
add mapped point in1[2] in1[2] -type PI PI
add mapped point in1[1] in1[1] -type PI PI
add mapped point in1[0] in1[0] -type PI PI
add mapped point in2[63] in2[63] -type PI PI
add mapped point in2[62] in2[62] -type PI PI
add mapped point in2[61] in2[61] -type PI PI
add mapped point in2[60] in2[60] -type PI PI
add mapped point in2[59] in2[59] -type PI PI
add mapped point in2[58] in2[58] -type PI PI
add mapped point in2[57] in2[57] -type PI PI
add mapped point in2[56] in2[56] -type PI PI
add mapped point in2[55] in2[55] -type PI PI
add mapped point in2[54] in2[54] -type PI PI
add mapped point in2[53] in2[53] -type PI PI
add mapped point in2[52] in2[52] -type PI PI
add mapped point in2[51] in2[51] -type PI PI
add mapped point in2[50] in2[50] -type PI PI
add mapped point in2[49] in2[49] -type PI PI
add mapped point in2[48] in2[48] -type PI PI
add mapped point in2[47] in2[47] -type PI PI
add mapped point in2[46] in2[46] -type PI PI
add mapped point in2[45] in2[45] -type PI PI
add mapped point in2[44] in2[44] -type PI PI
add mapped point in2[43] in2[43] -type PI PI
add mapped point in2[42] in2[42] -type PI PI
add mapped point in2[41] in2[41] -type PI PI
add mapped point in2[40] in2[40] -type PI PI
add mapped point in2[39] in2[39] -type PI PI
add mapped point in2[38] in2[38] -type PI PI
add mapped point in2[37] in2[37] -type PI PI
add mapped point in2[36] in2[36] -type PI PI
add mapped point in2[35] in2[35] -type PI PI
add mapped point in2[34] in2[34] -type PI PI
add mapped point in2[33] in2[33] -type PI PI
add mapped point in2[32] in2[32] -type PI PI
add mapped point in2[31] in2[31] -type PI PI
add mapped point in2[30] in2[30] -type PI PI
add mapped point in2[29] in2[29] -type PI PI
add mapped point in2[28] in2[28] -type PI PI
add mapped point in2[27] in2[27] -type PI PI
add mapped point in2[26] in2[26] -type PI PI
add mapped point in2[25] in2[25] -type PI PI
add mapped point in2[24] in2[24] -type PI PI
add mapped point in2[23] in2[23] -type PI PI
add mapped point in2[22] in2[22] -type PI PI
add mapped point in2[21] in2[21] -type PI PI
add mapped point in2[20] in2[20] -type PI PI
add mapped point in2[19] in2[19] -type PI PI
add mapped point in2[18] in2[18] -type PI PI
add mapped point in2[17] in2[17] -type PI PI
add mapped point in2[16] in2[16] -type PI PI
add mapped point in2[15] in2[15] -type PI PI
add mapped point in2[14] in2[14] -type PI PI
add mapped point in2[13] in2[13] -type PI PI
add mapped point in2[12] in2[12] -type PI PI
add mapped point in2[11] in2[11] -type PI PI
add mapped point in2[10] in2[10] -type PI PI
add mapped point in2[9] in2[9] -type PI PI
add mapped point in2[8] in2[8] -type PI PI
add mapped point in2[7] in2[7] -type PI PI
add mapped point in2[6] in2[6] -type PI PI
add mapped point in2[5] in2[5] -type PI PI
add mapped point in2[4] in2[4] -type PI PI
add mapped point in2[3] in2[3] -type PI PI
add mapped point in2[2] in2[2] -type PI PI
add mapped point in2[1] in2[1] -type PI PI
add mapped point in2[0] in2[0] -type PI PI
add mapped point start start -type PI PI
add mapped point reset reset -type PI PI
add mapped point clk clk -type PI PI

//output ports
add mapped point out[127] out[127] -type PO PO
add mapped point out[126] out[126] -type PO PO
add mapped point out[125] out[125] -type PO PO
add mapped point out[124] out[124] -type PO PO
add mapped point out[123] out[123] -type PO PO
add mapped point out[122] out[122] -type PO PO
add mapped point out[121] out[121] -type PO PO
add mapped point out[120] out[120] -type PO PO
add mapped point out[119] out[119] -type PO PO
add mapped point out[118] out[118] -type PO PO
add mapped point out[117] out[117] -type PO PO
add mapped point out[116] out[116] -type PO PO
add mapped point out[115] out[115] -type PO PO
add mapped point out[114] out[114] -type PO PO
add mapped point out[113] out[113] -type PO PO
add mapped point out[112] out[112] -type PO PO
add mapped point out[111] out[111] -type PO PO
add mapped point out[110] out[110] -type PO PO
add mapped point out[109] out[109] -type PO PO
add mapped point out[108] out[108] -type PO PO
add mapped point out[107] out[107] -type PO PO
add mapped point out[106] out[106] -type PO PO
add mapped point out[105] out[105] -type PO PO
add mapped point out[104] out[104] -type PO PO
add mapped point out[103] out[103] -type PO PO
add mapped point out[102] out[102] -type PO PO
add mapped point out[101] out[101] -type PO PO
add mapped point out[100] out[100] -type PO PO
add mapped point out[99] out[99] -type PO PO
add mapped point out[98] out[98] -type PO PO
add mapped point out[97] out[97] -type PO PO
add mapped point out[96] out[96] -type PO PO
add mapped point out[95] out[95] -type PO PO
add mapped point out[94] out[94] -type PO PO
add mapped point out[93] out[93] -type PO PO
add mapped point out[92] out[92] -type PO PO
add mapped point out[91] out[91] -type PO PO
add mapped point out[90] out[90] -type PO PO
add mapped point out[89] out[89] -type PO PO
add mapped point out[88] out[88] -type PO PO
add mapped point out[87] out[87] -type PO PO
add mapped point out[86] out[86] -type PO PO
add mapped point out[85] out[85] -type PO PO
add mapped point out[84] out[84] -type PO PO
add mapped point out[83] out[83] -type PO PO
add mapped point out[82] out[82] -type PO PO
add mapped point out[81] out[81] -type PO PO
add mapped point out[80] out[80] -type PO PO
add mapped point out[79] out[79] -type PO PO
add mapped point out[78] out[78] -type PO PO
add mapped point out[77] out[77] -type PO PO
add mapped point out[76] out[76] -type PO PO
add mapped point out[75] out[75] -type PO PO
add mapped point out[74] out[74] -type PO PO
add mapped point out[73] out[73] -type PO PO
add mapped point out[72] out[72] -type PO PO
add mapped point out[71] out[71] -type PO PO
add mapped point out[70] out[70] -type PO PO
add mapped point out[69] out[69] -type PO PO
add mapped point out[68] out[68] -type PO PO
add mapped point out[67] out[67] -type PO PO
add mapped point out[66] out[66] -type PO PO
add mapped point out[65] out[65] -type PO PO
add mapped point out[64] out[64] -type PO PO
add mapped point out[63] out[63] -type PO PO
add mapped point out[62] out[62] -type PO PO
add mapped point out[61] out[61] -type PO PO
add mapped point out[60] out[60] -type PO PO
add mapped point out[59] out[59] -type PO PO
add mapped point out[58] out[58] -type PO PO
add mapped point out[57] out[57] -type PO PO
add mapped point out[56] out[56] -type PO PO
add mapped point out[55] out[55] -type PO PO
add mapped point out[54] out[54] -type PO PO
add mapped point out[53] out[53] -type PO PO
add mapped point out[52] out[52] -type PO PO
add mapped point out[51] out[51] -type PO PO
add mapped point out[50] out[50] -type PO PO
add mapped point out[49] out[49] -type PO PO
add mapped point out[48] out[48] -type PO PO
add mapped point out[47] out[47] -type PO PO
add mapped point out[46] out[46] -type PO PO
add mapped point out[45] out[45] -type PO PO
add mapped point out[44] out[44] -type PO PO
add mapped point out[43] out[43] -type PO PO
add mapped point out[42] out[42] -type PO PO
add mapped point out[41] out[41] -type PO PO
add mapped point out[40] out[40] -type PO PO
add mapped point out[39] out[39] -type PO PO
add mapped point out[38] out[38] -type PO PO
add mapped point out[37] out[37] -type PO PO
add mapped point out[36] out[36] -type PO PO
add mapped point out[35] out[35] -type PO PO
add mapped point out[34] out[34] -type PO PO
add mapped point out[33] out[33] -type PO PO
add mapped point out[32] out[32] -type PO PO
add mapped point out[31] out[31] -type PO PO
add mapped point out[30] out[30] -type PO PO
add mapped point out[29] out[29] -type PO PO
add mapped point out[28] out[28] -type PO PO
add mapped point out[27] out[27] -type PO PO
add mapped point out[26] out[26] -type PO PO
add mapped point out[25] out[25] -type PO PO
add mapped point out[24] out[24] -type PO PO
add mapped point out[23] out[23] -type PO PO
add mapped point out[22] out[22] -type PO PO
add mapped point out[21] out[21] -type PO PO
add mapped point out[20] out[20] -type PO PO
add mapped point out[19] out[19] -type PO PO
add mapped point out[18] out[18] -type PO PO
add mapped point out[17] out[17] -type PO PO
add mapped point out[16] out[16] -type PO PO
add mapped point out[15] out[15] -type PO PO
add mapped point out[14] out[14] -type PO PO
add mapped point out[13] out[13] -type PO PO
add mapped point out[12] out[12] -type PO PO
add mapped point out[11] out[11] -type PO PO
add mapped point out[10] out[10] -type PO PO
add mapped point out[9] out[9] -type PO PO
add mapped point out[8] out[8] -type PO PO
add mapped point out[7] out[7] -type PO PO
add mapped point out[6] out[6] -type PO PO
add mapped point out[5] out[5] -type PO PO
add mapped point out[4] out[4] -type PO PO
add mapped point out[3] out[3] -type PO PO
add mapped point out[2] out[2] -type PO PO
add mapped point out[1] out[1] -type PO PO
add mapped point out[0] out[0] -type PO PO
add mapped point done done -type PO PO

//inout ports




//Sequential Pins
add mapped point par_out_a[0]/q par_out_a_reg_0/QN  -type DFF DFF
add mapped point par_out_a[1]/q par_out_a_reg_1/QN  -type DFF DFF
add mapped point par_out_a[2]/q par_out_a_reg_2/QN  -type DFF DFF
add mapped point par_out_a[3]/q par_out_a_reg_3/QN  -type DFF DFF
add mapped point par_out_a[4]/q par_out_a_reg_4/QN  -type DFF DFF
add mapped point par_out_a[5]/q par_out_a_reg_5/QN  -type DFF DFF
add mapped point par_out_a[6]/q par_out_a_reg_6/Q  -type DFF DFF
add mapped point par_out_a[7]/q par_out_a_reg_7/QN  -type DFF DFF
add mapped point par_out_a[8]/q par_out_a_reg_8/QN  -type DFF DFF
add mapped point par_out_a[9]/q par_out_a_reg_9/QN  -type DFF DFF
add mapped point par_out_a[10]/q par_out_a_reg_10/QN  -type DFF DFF
add mapped point par_out_a[11]/q par_out_a_reg_11/QN  -type DFF DFF
add mapped point par_out_a[12]/q par_out_a_reg_12/QN  -type DFF DFF
add mapped point par_out_a[13]/q par_out_a_reg_13/QN  -type DFF DFF
add mapped point par_out_a[14]/q par_out_a_reg_14/QN  -type DFF DFF
add mapped point par_out_a[15]/q par_out_a_reg_15/QN  -type DFF DFF
add mapped point par_out_a[16]/q par_out_a_reg_16/QN  -type DFF DFF
add mapped point par_out_a[17]/q par_out_a_reg_17/QN  -type DFF DFF
add mapped point par_out_a[18]/q par_out_a_reg_18/QN  -type DFF DFF
add mapped point par_out_a[19]/q par_out_a_reg_19/QN  -type DFF DFF
add mapped point par_out_a[20]/q par_out_a_reg_20/QN  -type DFF DFF
add mapped point par_out_a[21]/q par_out_a_reg_21/QN  -type DFF DFF
add mapped point par_out_a[22]/q par_out_a_reg_22/QN  -type DFF DFF
add mapped point par_out_a[23]/q par_out_a_reg_23/QN  -type DFF DFF
add mapped point par_out_a[24]/q par_out_a_reg_24/QN  -type DFF DFF
add mapped point par_out_a[25]/q par_out_a_reg_25/QN  -type DFF DFF
add mapped point par_out_a[26]/q par_out_a_reg_26/QN  -type DFF DFF
add mapped point par_out_a[27]/q par_out_a_reg_27/QN  -type DFF DFF
add mapped point par_out_a[28]/q par_out_a_reg_28/QN  -type DFF DFF
add mapped point par_out_a[29]/q par_out_a_reg_29/QN  -type DFF DFF
add mapped point par_out_a[30]/q par_out_a_reg_30/QN  -type DFF DFF
add mapped point par_out_a[31]/q par_out_a_reg_31/QN  -type DFF DFF
add mapped point par_out_a[32]/q par_out_a_reg_32/QN  -type DFF DFF
add mapped point par_out_a[33]/q par_out_a_reg_33/QN  -type DFF DFF
add mapped point par_out_a[34]/q par_out_a_reg_34/QN  -type DFF DFF
add mapped point par_out_a[35]/q par_out_a_reg_35/QN  -type DFF DFF
add mapped point par_out_a[36]/q par_out_a_reg_36/QN  -type DFF DFF
add mapped point par_out_a[37]/q par_out_a_reg_37/QN  -type DFF DFF
add mapped point par_out_a[38]/q par_out_a_reg_38/QN  -type DFF DFF
add mapped point par_out_a[39]/q par_out_a_reg_39/QN  -type DFF DFF
add mapped point par_out_a[40]/q par_out_a_reg_40/QN  -type DFF DFF
add mapped point par_out_a[41]/q par_out_a_reg_41/QN  -type DFF DFF
add mapped point par_out_a[42]/q par_out_a_reg_42/QN  -type DFF DFF
add mapped point par_out_a[43]/q par_out_a_reg_43/QN  -type DFF DFF
add mapped point par_out_a[44]/q par_out_a_reg_44/QN  -type DFF DFF
add mapped point par_out_a[45]/q par_out_a_reg_45/QN  -type DFF DFF
add mapped point par_out_a[46]/q par_out_a_reg_46/QN  -type DFF DFF
add mapped point par_out_a[47]/q par_out_a_reg_47/QN  -type DFF DFF
add mapped point par_out_a[48]/q par_out_a_reg_48/QN  -type DFF DFF
add mapped point par_out_a[49]/q par_out_a_reg_49/QN  -type DFF DFF
add mapped point par_out_a[50]/q par_out_a_reg_50/QN  -type DFF DFF
add mapped point par_out_a[51]/q par_out_a_reg_51/QN  -type DFF DFF
add mapped point par_out_a[52]/q par_out_a_reg_52/QN  -type DFF DFF
add mapped point par_out_a[53]/q par_out_a_reg_53/QN  -type DFF DFF
add mapped point par_out_a[54]/q par_out_a_reg_54/QN  -type DFF DFF
add mapped point par_out_a[55]/q par_out_a_reg_55/QN  -type DFF DFF
add mapped point par_out_a[56]/q par_out_a_reg_56/QN  -type DFF DFF
add mapped point par_out_a[57]/q par_out_a_reg_57/QN  -type DFF DFF
add mapped point par_out_a[58]/q par_out_a_reg_58/QN  -type DFF DFF
add mapped point par_out_a[59]/q par_out_a_reg_59/QN  -type DFF DFF
add mapped point par_out_a[60]/q par_out_a_reg_60/QN  -type DFF DFF
add mapped point par_out_a[61]/q par_out_a_reg_61/QN  -type DFF DFF
add mapped point par_out_a[62]/q par_out_a_reg_62/QN  -type DFF DFF
add mapped point par_out_a[63]/q par_out_a_reg_63/QN  -type DFF DFF
add mapped point par_out_a[64]/q par_out_a_reg_64/QN  -type DFF DFF
add mapped point par_out_a[65]/q par_out_a_reg_65/QN  -type DFF DFF
add mapped point par_out_a[66]/q par_out_a_reg_66/QN  -type DFF DFF
add mapped point par_out_a[67]/q par_out_a_reg_67/QN  -type DFF DFF
add mapped point par_out_a[68]/q par_out_a_reg_68/QN  -type DFF DFF
add mapped point par_out_a[69]/q par_out_a_reg_69/QN  -type DFF DFF
add mapped point par_out_a[70]/q par_out_a_reg_70/QN  -type DFF DFF
add mapped point par_out_a[71]/q par_out_a_reg_71/QN  -type DFF DFF
add mapped point par_out_a[72]/q par_out_a_reg_72/QN  -type DFF DFF
add mapped point par_out_a[73]/q par_out_a_reg_73/QN  -type DFF DFF
add mapped point par_out_a[74]/q par_out_a_reg_74/QN  -type DFF DFF
add mapped point par_out_a[75]/q par_out_a_reg_75/QN  -type DFF DFF
add mapped point par_out_a[76]/q par_out_a_reg_76/QN  -type DFF DFF
add mapped point par_out_a[77]/q par_out_a_reg_77/QN  -type DFF DFF
add mapped point par_out_a[78]/q par_out_a_reg_78/QN  -type DFF DFF
add mapped point par_out_a[79]/q par_out_a_reg_79/QN  -type DFF DFF
add mapped point par_out_a[80]/q par_out_a_reg_80/QN  -type DFF DFF
add mapped point par_out_a[81]/q par_out_a_reg_81/QN  -type DFF DFF
add mapped point par_out_a[82]/q par_out_a_reg_82/QN  -type DFF DFF
add mapped point par_out_a[83]/q par_out_a_reg_83/QN  -type DFF DFF
add mapped point par_out_a[84]/q par_out_a_reg_84/QN  -type DFF DFF
add mapped point par_out_a[85]/q par_out_a_reg_85/QN  -type DFF DFF
add mapped point par_out_a[86]/q par_out_a_reg_86/QN  -type DFF DFF
add mapped point par_out_a[87]/q par_out_a_reg_87/QN  -type DFF DFF
add mapped point par_out_a[88]/q par_out_a_reg_88/QN  -type DFF DFF
add mapped point par_out_a[89]/q par_out_a_reg_89/QN  -type DFF DFF
add mapped point par_out_a[90]/q par_out_a_reg_90/QN  -type DFF DFF
add mapped point par_out_a[91]/q par_out_a_reg_91/QN  -type DFF DFF
add mapped point par_out_a[92]/q par_out_a_reg_92/QN  -type DFF DFF
add mapped point par_out_a[93]/q par_out_a_reg_93/QN  -type DFF DFF
add mapped point par_out_a[94]/q par_out_a_reg_94/QN  -type DFF DFF
add mapped point par_out_a[95]/q par_out_a_reg_95/QN  -type DFF DFF
add mapped point par_out_a[96]/q par_out_a_reg_96/QN  -type DFF DFF
add mapped point par_out_a[97]/q par_out_a_reg_97/QN  -type DFF DFF
add mapped point par_out_a[98]/q par_out_a_reg_98/QN  -type DFF DFF
add mapped point par_out_a[99]/q par_out_a_reg_99/QN  -type DFF DFF
add mapped point par_out_a[100]/q par_out_a_reg_100/QN  -type DFF DFF
add mapped point par_out_a[101]/q par_out_a_reg_101/QN  -type DFF DFF
add mapped point par_out_a[102]/q par_out_a_reg_102/QN  -type DFF DFF
add mapped point par_out_a[103]/q par_out_a_reg_103/QN  -type DFF DFF
add mapped point par_out_a[104]/q par_out_a_reg_104/QN  -type DFF DFF
add mapped point par_out_a[105]/q par_out_a_reg_105/QN  -type DFF DFF
add mapped point par_out_a[106]/q par_out_a_reg_106/QN  -type DFF DFF
add mapped point par_out_a[107]/q par_out_a_reg_107/QN  -type DFF DFF
add mapped point par_out_a[108]/q par_out_a_reg_108/QN  -type DFF DFF
add mapped point par_out_a[109]/q par_out_a_reg_109/QN  -type DFF DFF
add mapped point par_out_a[110]/q par_out_a_reg_110/QN  -type DFF DFF
add mapped point par_out_a[111]/q par_out_a_reg_111/QN  -type DFF DFF
add mapped point par_out_a[112]/q par_out_a_reg_112/QN  -type DFF DFF
add mapped point par_out_a[113]/q par_out_a_reg_113/QN  -type DFF DFF
add mapped point par_out_a[114]/q par_out_a_reg_114/QN  -type DFF DFF
add mapped point par_out_a[115]/q par_out_a_reg_115/QN  -type DFF DFF
add mapped point par_out_a[116]/q par_out_a_reg_116/QN  -type DFF DFF
add mapped point par_out_a[117]/q par_out_a_reg_117/QN  -type DFF DFF
add mapped point par_out_a[118]/q par_out_a_reg_118/QN  -type DFF DFF
add mapped point par_out_a[119]/q par_out_a_reg_119/QN  -type DFF DFF
add mapped point par_out_a[120]/q par_out_a_reg_120/QN  -type DFF DFF
add mapped point par_out_a[121]/q par_out_a_reg_121/QN  -type DFF DFF
add mapped point par_out_a[122]/q par_out_a_reg_122/QN  -type DFF DFF
add mapped point par_out_a[123]/q par_out_a_reg_123/QN  -type DFF DFF
add mapped point par_out_a[124]/q par_out_a_reg_124/QN  -type DFF DFF
add mapped point par_out_a[125]/q par_out_a_reg_125/QN  -type DFF DFF
add mapped point par_out_a[126]/q par_out_a_reg_126/QN  -type DFF DFF
add mapped point par_out_a[127]/q par_out_a_reg_127/QN  -type DFF DFF
add mapped point par_out_b[0]/q par_out_b_reg_0/QN  -type DFF DFF
add mapped point par_out_b[1]/q par_out_b_reg_1/Q  -type DFF DFF
add mapped point par_out_b[2]/q par_out_b_reg_2/Q  -type DFF DFF
add mapped point par_out_b[3]/q par_out_b_reg_3/Q  -type DFF DFF
add mapped point par_out_b[4]/q par_out_b_reg_4/Q  -type DFF DFF
add mapped point par_out_b[5]/q par_out_b_reg_5/Q  -type DFF DFF
add mapped point par_out_b[6]/q par_out_b_reg_6/Q  -type DFF DFF
add mapped point par_out_b[7]/q par_out_b_reg_7/Q  -type DFF DFF
add mapped point par_out_b[8]/q par_out_b_reg_8/Q  -type DFF DFF
add mapped point par_out_b[9]/q par_out_b_reg_9/Q  -type DFF DFF
add mapped point par_out_b[10]/q par_out_b_reg_10/Q  -type DFF DFF
add mapped point par_out_b[11]/q par_out_b_reg_11/Q  -type DFF DFF
add mapped point par_out_b[12]/q par_out_b_reg_12/Q  -type DFF DFF
add mapped point par_out_b[13]/q par_out_b_reg_13/Q  -type DFF DFF
add mapped point par_out_b[14]/q par_out_b_reg_14/Q  -type DFF DFF
add mapped point par_out_b[15]/q par_out_b_reg_15/Q  -type DFF DFF
add mapped point par_out_b[16]/q par_out_b_reg_16/Q  -type DFF DFF
add mapped point par_out_b[17]/q par_out_b_reg_17/Q  -type DFF DFF
add mapped point par_out_b[18]/q par_out_b_reg_18/Q  -type DFF DFF
add mapped point par_out_b[19]/q par_out_b_reg_19/Q  -type DFF DFF
add mapped point par_out_b[20]/q par_out_b_reg_20/Q  -type DFF DFF
add mapped point par_out_b[21]/q par_out_b_reg_21/Q  -type DFF DFF
add mapped point par_out_b[22]/q par_out_b_reg_22/Q  -type DFF DFF
add mapped point par_out_b[23]/q par_out_b_reg_23/Q  -type DFF DFF
add mapped point par_out_b[24]/q par_out_b_reg_24/Q  -type DFF DFF
add mapped point par_out_b[25]/q par_out_b_reg_25/Q  -type DFF DFF
add mapped point par_out_b[26]/q par_out_b_reg_26/Q  -type DFF DFF
add mapped point par_out_b[27]/q par_out_b_reg_27/Q  -type DFF DFF
add mapped point par_out_b[28]/q par_out_b_reg_28/Q  -type DFF DFF
add mapped point par_out_b[29]/q par_out_b_reg_29/Q  -type DFF DFF
add mapped point par_out_b[30]/q par_out_b_reg_30/Q  -type DFF DFF
add mapped point par_out_b[31]/q par_out_b_reg_31/Q  -type DFF DFF
add mapped point par_out_b[32]/q par_out_b_reg_32/Q  -type DFF DFF
add mapped point par_out_b[33]/q par_out_b_reg_33/Q  -type DFF DFF
add mapped point par_out_b[34]/q par_out_b_reg_34/Q  -type DFF DFF
add mapped point par_out_b[35]/q par_out_b_reg_35/Q  -type DFF DFF
add mapped point par_out_b[36]/q par_out_b_reg_36/Q  -type DFF DFF
add mapped point par_out_b[37]/q par_out_b_reg_37/Q  -type DFF DFF
add mapped point par_out_b[38]/q par_out_b_reg_38/Q  -type DFF DFF
add mapped point par_out_b[39]/q par_out_b_reg_39/Q  -type DFF DFF
add mapped point par_out_b[40]/q par_out_b_reg_40/Q  -type DFF DFF
add mapped point par_out_b[41]/q par_out_b_reg_41/Q  -type DFF DFF
add mapped point par_out_b[42]/q par_out_b_reg_42/Q  -type DFF DFF
add mapped point par_out_b[43]/q par_out_b_reg_43/Q  -type DFF DFF
add mapped point par_out_b[44]/q par_out_b_reg_44/Q  -type DFF DFF
add mapped point par_out_b[45]/q par_out_b_reg_45/Q  -type DFF DFF
add mapped point par_out_b[46]/q par_out_b_reg_46/Q  -type DFF DFF
add mapped point par_out_b[47]/q par_out_b_reg_47/Q  -type DFF DFF
add mapped point par_out_b[48]/q par_out_b_reg_48/Q  -type DFF DFF
add mapped point par_out_b[49]/q par_out_b_reg_49/Q  -type DFF DFF
add mapped point par_out_b[50]/q par_out_b_reg_50/Q  -type DFF DFF
add mapped point par_out_b[51]/q par_out_b_reg_51/Q  -type DFF DFF
add mapped point par_out_b[52]/q par_out_b_reg_52/Q  -type DFF DFF
add mapped point par_out_b[53]/q par_out_b_reg_53/Q  -type DFF DFF
add mapped point par_out_b[54]/q par_out_b_reg_54/Q  -type DFF DFF
add mapped point par_out_b[55]/q par_out_b_reg_55/Q  -type DFF DFF
add mapped point par_out_b[56]/q par_out_b_reg_56/Q  -type DFF DFF
add mapped point par_out_b[57]/q par_out_b_reg_57/Q  -type DFF DFF
add mapped point par_out_b[58]/q par_out_b_reg_58/Q  -type DFF DFF
add mapped point par_out_b[59]/q par_out_b_reg_59/Q  -type DFF DFF
add mapped point par_out_b[60]/q par_out_b_reg_60/Q  -type DFF DFF
add mapped point par_out_b[61]/q par_out_b_reg_61/Q  -type DFF DFF
add mapped point par_out_b[62]/q par_out_b_reg_62/Q  -type DFF DFF
add mapped point par_out_b[63]/q par_out_b_reg_63/Q  -type DFF DFF
add mapped point count[0]/q count_reg_0/Q  -type DFF DFF
add mapped point count[1]/q count_reg_1/Q  -type DFF DFF
add mapped point count[2]/q count_reg_2/Q  -type DFF DFF
add mapped point count[3]/q count_reg_3/Q  -type DFF DFF
add mapped point count[4]/q count_reg_4/Q  -type DFF DFF
add mapped point count[5]/q count_reg_5/Q  -type DFF DFF
add mapped point count[6]/q count_reg_6/Q  -type DFF DFF
add mapped point out[0]/q out_reg_0/Q  -type DFF DFF
add mapped point out[1]/q out_reg_1/Q  -type DFF DFF
add mapped point out[2]/q out_reg_2/Q  -type DFF DFF
add mapped point out[3]/q out_reg_3/Q  -type DFF DFF
add mapped point out[4]/q out_reg_4/Q  -type DFF DFF
add mapped point out[5]/q out_reg_5/Q  -type DFF DFF
add mapped point out[6]/q out_reg_6/Q  -type DFF DFF
add mapped point out[7]/q out_reg_7/Q  -type DFF DFF
add mapped point out[8]/q out_reg_8/Q  -type DFF DFF
add mapped point out[9]/q out_reg_9/Q  -type DFF DFF
add mapped point out[10]/q out_reg_10/Q  -type DFF DFF
add mapped point out[11]/q out_reg_11/Q  -type DFF DFF
add mapped point out[12]/q out_reg_12/Q  -type DFF DFF
add mapped point out[13]/q out_reg_13/Q  -type DFF DFF
add mapped point out[14]/q out_reg_14/Q  -type DFF DFF
add mapped point out[15]/q out_reg_15/Q  -type DFF DFF
add mapped point out[16]/q out_reg_16/Q  -type DFF DFF
add mapped point out[17]/q out_reg_17/Q  -type DFF DFF
add mapped point out[18]/q out_reg_18/Q  -type DFF DFF
add mapped point out[19]/q out_reg_19/Q  -type DFF DFF
add mapped point out[20]/q out_reg_20/Q  -type DFF DFF
add mapped point out[21]/q out_reg_21/Q  -type DFF DFF
add mapped point out[22]/q out_reg_22/Q  -type DFF DFF
add mapped point out[23]/q out_reg_23/Q  -type DFF DFF
add mapped point out[24]/q out_reg_24/Q  -type DFF DFF
add mapped point out[25]/q out_reg_25/Q  -type DFF DFF
add mapped point out[26]/q out_reg_26/Q  -type DFF DFF
add mapped point out[27]/q out_reg_27/Q  -type DFF DFF
add mapped point out[28]/q out_reg_28/Q  -type DFF DFF
add mapped point out[29]/q out_reg_29/Q  -type DFF DFF
add mapped point out[30]/q out_reg_30/Q  -type DFF DFF
add mapped point out[31]/q out_reg_31/Q  -type DFF DFF
add mapped point out[32]/q out_reg_32/Q  -type DFF DFF
add mapped point out[33]/q out_reg_33/Q  -type DFF DFF
add mapped point out[34]/q out_reg_34/Q  -type DFF DFF
add mapped point out[35]/q out_reg_35/Q  -type DFF DFF
add mapped point out[36]/q out_reg_36/Q  -type DFF DFF
add mapped point out[37]/q out_reg_37/Q  -type DFF DFF
add mapped point out[38]/q out_reg_38/Q  -type DFF DFF
add mapped point out[39]/q out_reg_39/Q  -type DFF DFF
add mapped point out[40]/q out_reg_40/Q  -type DFF DFF
add mapped point out[41]/q out_reg_41/Q  -type DFF DFF
add mapped point out[42]/q out_reg_42/Q  -type DFF DFF
add mapped point out[43]/q out_reg_43/Q  -type DFF DFF
add mapped point out[44]/q out_reg_44/Q  -type DFF DFF
add mapped point out[45]/q out_reg_45/Q  -type DFF DFF
add mapped point out[46]/q out_reg_46/Q  -type DFF DFF
add mapped point out[47]/q out_reg_47/Q  -type DFF DFF
add mapped point out[48]/q out_reg_48/Q  -type DFF DFF
add mapped point out[49]/q out_reg_49/Q  -type DFF DFF
add mapped point out[50]/q out_reg_50/Q  -type DFF DFF
add mapped point out[51]/q out_reg_51/Q  -type DFF DFF
add mapped point out[52]/q out_reg_52/Q  -type DFF DFF
add mapped point out[53]/q out_reg_53/Q  -type DFF DFF
add mapped point out[54]/q out_reg_54/Q  -type DFF DFF
add mapped point out[55]/q out_reg_55/Q  -type DFF DFF
add mapped point out[56]/q out_reg_56/Q  -type DFF DFF
add mapped point out[57]/q out_reg_57/Q  -type DFF DFF
add mapped point out[58]/q out_reg_58/Q  -type DFF DFF
add mapped point out[59]/q out_reg_59/Q  -type DFF DFF
add mapped point out[60]/q out_reg_60/Q  -type DFF DFF
add mapped point out[61]/q out_reg_61/Q  -type DFF DFF
add mapped point out[62]/q out_reg_62/Q  -type DFF DFF
add mapped point out[63]/q out_reg_63/Q  -type DFF DFF
add mapped point out[64]/q out_reg_64/Q  -type DFF DFF
add mapped point out[65]/q out_reg_65/Q  -type DFF DFF
add mapped point out[66]/q out_reg_66/Q  -type DFF DFF
add mapped point out[67]/q out_reg_67/Q  -type DFF DFF
add mapped point out[68]/q out_reg_68/Q  -type DFF DFF
add mapped point out[69]/q out_reg_69/Q  -type DFF DFF
add mapped point out[70]/q out_reg_70/Q  -type DFF DFF
add mapped point out[71]/q out_reg_71/Q  -type DFF DFF
add mapped point out[72]/q out_reg_72/Q  -type DFF DFF
add mapped point out[73]/q out_reg_73/Q  -type DFF DFF
add mapped point out[74]/q out_reg_74/Q  -type DFF DFF
add mapped point out[75]/q out_reg_75/Q  -type DFF DFF
add mapped point out[76]/q out_reg_76/Q  -type DFF DFF
add mapped point out[77]/q out_reg_77/Q  -type DFF DFF
add mapped point out[78]/q out_reg_78/Q  -type DFF DFF
add mapped point out[79]/q out_reg_79/Q  -type DFF DFF
add mapped point out[80]/q out_reg_80/Q  -type DFF DFF
add mapped point out[81]/q out_reg_81/Q  -type DFF DFF
add mapped point out[82]/q out_reg_82/Q  -type DFF DFF
add mapped point out[83]/q out_reg_83/Q  -type DFF DFF
add mapped point out[84]/q out_reg_84/Q  -type DFF DFF
add mapped point out[85]/q out_reg_85/Q  -type DFF DFF
add mapped point out[86]/q out_reg_86/Q  -type DFF DFF
add mapped point out[87]/q out_reg_87/Q  -type DFF DFF
add mapped point out[88]/q out_reg_88/Q  -type DFF DFF
add mapped point out[89]/q out_reg_89/Q  -type DFF DFF
add mapped point out[90]/q out_reg_90/Q  -type DFF DFF
add mapped point out[91]/q out_reg_91/Q  -type DFF DFF
add mapped point out[92]/q out_reg_92/Q  -type DFF DFF
add mapped point out[93]/q out_reg_93/Q  -type DFF DFF
add mapped point out[94]/q out_reg_94/Q  -type DFF DFF
add mapped point out[95]/q out_reg_95/Q  -type DFF DFF
add mapped point out[96]/q out_reg_96/Q  -type DFF DFF
add mapped point out[97]/q out_reg_97/Q  -type DFF DFF
add mapped point out[98]/q out_reg_98/Q  -type DFF DFF
add mapped point out[99]/q out_reg_99/Q  -type DFF DFF
add mapped point out[100]/q out_reg_100/Q  -type DFF DFF
add mapped point out[101]/q out_reg_101/Q  -type DFF DFF
add mapped point out[102]/q out_reg_102/Q  -type DFF DFF
add mapped point out[103]/q out_reg_103/Q  -type DFF DFF
add mapped point out[104]/q out_reg_104/Q  -type DFF DFF
add mapped point out[105]/q out_reg_105/Q  -type DFF DFF
add mapped point out[106]/q out_reg_106/Q  -type DFF DFF
add mapped point out[107]/q out_reg_107/Q  -type DFF DFF
add mapped point out[108]/q out_reg_108/Q  -type DFF DFF
add mapped point out[109]/q out_reg_109/Q  -type DFF DFF
add mapped point out[110]/q out_reg_110/Q  -type DFF DFF
add mapped point out[111]/q out_reg_111/Q  -type DFF DFF
add mapped point out[112]/q out_reg_112/Q  -type DFF DFF
add mapped point out[113]/q out_reg_113/Q  -type DFF DFF
add mapped point out[114]/q out_reg_114/Q  -type DFF DFF
add mapped point out[115]/q out_reg_115/Q  -type DFF DFF
add mapped point out[116]/q out_reg_116/Q  -type DFF DFF
add mapped point out[117]/q out_reg_117/Q  -type DFF DFF
add mapped point out[118]/q out_reg_118/Q  -type DFF DFF
add mapped point out[119]/q out_reg_119/Q  -type DFF DFF
add mapped point out[120]/q out_reg_120/Q  -type DFF DFF
add mapped point out[121]/q out_reg_121/Q  -type DFF DFF
add mapped point out[122]/q out_reg_122/Q  -type DFF DFF
add mapped point out[123]/q out_reg_123/Q  -type DFF DFF
add mapped point out[124]/q out_reg_124/Q  -type DFF DFF
add mapped point out[125]/q out_reg_125/Q  -type DFF DFF
add mapped point out[126]/q out_reg_126/Q  -type DFF DFF
add mapped point out[127]/q out_reg_127/Q  -type DFF DFF
add mapped point state[0]/q state_reg_0/Q  -type DFF DFF
add mapped point state[1]/q state_reg_1/Q  -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
